import { NextResponse } from "next/server";
import { readSportWorksheet } from "../../../../lib/sportSheets";
export const dynamic="force-dynamic";export const revalidate=0;
type R=Record<string,string>;type G={date:string,week:number,away:string,home:string,ms:number|null,mt:number|null,am:number,at:number,ar:R,hr:R};
const t=(v:unknown)=>String(v??"").trim();const n=(v:unknown,d=0)=>{const x=Number(t(v));return Number.isFinite(x)?x:d};const k=(s:string)=>s.toUpperCase().replace(/[^A-Z0-9]/g,"");const dk=(s:string)=>t(s).slice(0,10);const mean=(a:number[])=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0;const r=(x:number|null,d=4)=>x==null?null:Number(x.toFixed(d));
function corr(x:number[],y:number[]){if(x.length<5)return null;const mx=mean(x),my=mean(y);let a=0,b=0,c=0;for(let i=0;i<x.length;i++){const dx=x[i]-mx,dy=y[i]-my;a+=dx*dy;b+=dx*dx;c+=dy*dy}return b&&c?a/Math.sqrt(b*c):null}
function sKey(x:R){const id=t(x["Game ID"]);return id?`id:${id}`:`${dk(x.Date)}|${k(t(x["Away Team"]))}|${k(t(x["Home Team"]))}`};function schedKeys(x:R){const o:string[]=[];const id=t(x["Game ID"]);if(id)o.push(`id:${id}`);o.push(`${dk(x["Game Date"])}|${k(t(x["Away Team"]))}|${k(t(x["Home Team"]))}`);return o}function pw(x:R){return n(x["Projection Week"],n(x.Week,0))}
function pct(v:unknown,d:number){let x=n(v,d);if(x>1.5)x/=100;return x}
function comp(off:R,def:R){return{overall:.60*(n(off["Offense Rating"])-n(def["Defense Rating"])),pass:10*(n(off["Pass EPA/PPA"])-n(def["Pass Defense Edge"])),rush:8*(n(off["Rush EPA/PPA"])-n(def["Rush Defense Edge"])),success:22*((pct(off["Success Rate Offense"],.42)-.42)-n(def["Success Rate Defense Edge"])),explosive:1.8*((n(off["Explosiveness Offense"],1)-1)-n(def["Explosiveness Defense Edge"])),line:1.2*((n(off["Line Yards Offense"],2.7)-2.7)-n(def["Line Yards Defense Edge"])),havoc:-9*((n(def["Havoc Created"],.16)-.16)+(n(off["Havoc Allowed"],.16)-.16)),finishing:.75*((n(off["Finishing Drives Offense"],4.2)-4.2)-n(def["Finishing Drives Defense Edge"])),field_position:.16*((n(off["Field Position Offense"],29)-29)-n(def["Field Position Defense Edge"])),third_down:8*((pct(off["Third Down Rate"],.40)-.40)-n(def["Third Down Defense Edge"])),red_zone:5*((pct(off["Red Zone TD Rate"],.62)-.62)-n(def["Red Zone Defense Edge"])),turnover:-8*((pct(off["Turnover Rate"],.12)-.12)-(pct(def["Takeaway Rate"],.12)-.12)),sack:-7*((pct(off["Sack Rate Allowed"],.065)-.065)+(pct(def["Sack Rate Created"],.065)-.065))}}
function stat(rows:G[],name:string,kind:"spread"|"total"){const xs:number[]=[],ya:number[]=[],ym:number[]=[],yr:number[]=[];for(const g of rows){const ac=comp(g.ar,g.hr),hc=comp(g.hr,g.ar);const x=kind==="spread"?(hc as any)[name]-(ac as any)[name]:(hc as any)[name]+(ac as any)[name];const market=kind==="spread"?(g.ms==null?null:-g.ms):g.mt;if(market==null)continue;const actual=kind==="spread"?g.am:g.at;const model=kind==="spread"?null:null;xs.push(x);ya.push(actual);ym.push(actual-market);yr.push(kind==="spread"?0:0)}return{component:name,n:xs.length,actualCorr:r(corr(xs,ya)),marketResidualCorr:r(corr(xs,ym)),meanContribution:r(mean(xs)),sdContribution:r(Math.sqrt(mean(xs.map(v=>(v-mean(xs))**2))))}}
function quart(rows:G[],name:string,kind:"spread"|"total"){const vals=rows.map(g=>{const ac=comp(g.ar,g.hr),hc=comp(g.hr,g.ar),x=kind==="spread"?(hc as any)[name]-(ac as any)[name]:(hc as any)[name]+(ac as any)[name],market=kind==="spread"?(g.ms==null?null:-g.ms):g.mt;return market==null?null:{x,res:(kind==="spread"?g.am:g.at)-market}}).filter(Boolean) as {x:number,res:number}[];vals.sort((a,b)=>a.x-b.x);const q=Math.max(1,Math.floor(vals.length/4)),lo=vals.slice(0,q),hi=vals.slice(-q);return{component:name,lowMean:r(mean(lo.map(x=>x.res))),highMean:r(mean(hi.map(x=>x.res))),spread:r(mean(hi.map(x=>x.res))-mean(lo.map(x=>x.res)))}}
export async function GET(){const [slate,schedule,ratings,log]=await Promise.all([readSportWorksheet("NCAAF","daily_slate") as Promise<R[]>,readSportWorksheet("NCAAF","schedule") as Promise<R[]>,readSportWorksheet("NCAAF","team_ratings") as Promise<R[]>,readSportWorksheet("NCAAF","model_change_log") as Promise<R[]>]);const actual=new Map<string,{a:number,h:number}>();for(const x of schedule){const a=n(x["Away Score"],NaN),h=n(x["Home Score"],NaN);if(!Number.isFinite(a)||!Number.isFinite(h)||(a===0&&h===0))continue;for(const q of schedKeys(x))actual.set(q,{a,h})}const bt=new Map<string,R[]>();for(const x of ratings){const q=k(t(x.Team));if(!q)continue;if(!bt.has(q))bt.set(q,[]);bt.get(q)!.push(x)}for(const v of bt.values())v.sort((a,b)=>pw(a)-pw(b));const gr=(team:string,w:number)=>{const a=bt.get(k(team))||[];return a.filter(x=>pw(x)<=w).at(-1)||a.at(0)||null};const dd=new Map<string,R>();for(const x of slate)dd.set(sKey(x),x);const games:G[]=[];for(const x of dd.values()){const a=actual.get(sKey(x))||actual.get(`${dk(x.Date)}|${k(t(x["Away Team"]))}|${k(t(x["Home Team"]))}`),w=n(x.Week,0);if(!a||!w)continue;const ar=gr(t(x["Away Team"]),w),hr=gr(t(x["Home Team"]),w);if(!ar||!hr)continue;games.push({date:dk(x.Date),week:w,away:t(x["Away Team"]),home:t(x["Home Team"]),ms:t(x["Market Home Spread"])?n(x["Market Home Spread"]):null,mt:t(x["Market Total"])?n(x["Market Total"]):null,am:a.h-a.a,at:a.h+a.a,ar,hr})}games.sort((a,b)=>a.date.localeCompare(b.date));const dates=[...new Set(games.map(g=>g.date))].sort(),hd=dates.at(-1)||"",dev=games.filter(g=>g.date<hd),hold=games.filter(g=>g.date===hd),names=Object.keys(comp(games[0].ar,games[0].hr));const pack=(kind:"spread"|"total")=>names.map(name=>({development:stat(dev,name,kind),holdout:stat(hold,name,kind),developmentQuartiles:quart(dev,name,kind),holdoutQuartiles:quart(hold,name,kind)})).sort((a,b)=>Math.min(Math.abs(b.development.marketResidualCorr??0),Math.abs(b.holdout.marketResidualCorr??0))-Math.min(Math.abs(a.development.marketResidualCorr??0),Math.abs(a.holdout.marketResidualCorr??0)));return NextResponse.json({source:{games:games.length,development:dev.length,holdout:hold.length,holdoutDate:hd},spread:pack("spread"),total:pack("total"),modelLog:log.slice(-12)});}
