import { NextResponse } from "next/server";
import { readSportWorksheet } from "../../../../lib/sportSheets";
export const dynamic="force-dynamic";export const revalidate=0;export const maxDuration=60;
type R=Record<string,string>;type G={date:string;week:number,pm:number,am:number,ar:R,hr:R};
const t=(v:unknown)=>String(v??"").trim(),num=(v:unknown)=>{const x=Number(t(v));return Number.isFinite(x)?x:null},key=(s:string)=>s.toUpperCase().replace(/[^A-Z0-9]/g,""),dk=(s:string)=>t(s).slice(0,10),avg=(a:number[])=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0,r=(x:number)=>Number(x.toFixed(4));
function sKey(x:R){const id=t(x["Game ID"]);return id?`id:${id}`:`${dk(x.Date)}|${key(t(x["Away Team"]))}|${key(t(x["Home Team"]))}`}
function schedKeys(x:R){const z=[] as string[];const id=t(x["Game ID"]);if(id)z.push(`id:${id}`);z.push(`${dk(x["Game Date"])}|${key(t(x["Away Team"]))}|${key(t(x["Home Team"]))}`);return z}
function teamName(x:R){for(const q of ["Team","School","team","school","Name"])if(t(x[q]))return t(x[q]);return ""}function projWeek(x:R){for(const q of ["Projection Week","Week","week"]){const v=num(x[q]);if(v!=null)return v}return 0}
const GROUPS:Record<string,string[]>={
 finishing:["Finishing Drives Offense","Finishing Drives Defense Edge"],
 drive_efficiency:["Points Per Drive","Points Allowed Per Drive"],
 third_down:["Third Down Rate","Third Down Defense Edge"],
 passing:["Pass EPA/PPA","Pass Defense Edge"],
 rushing:["Rush EPA/PPA","Rush Defense Edge"],
 success_rate:["Success Rate Offense","Success Rate Defense Edge"],
 explosiveness:["Explosiveness Offense","Explosiveness Defense Edge"],
 line_play:["Line Yards Offense","Line Yards Defense Edge","Power Success","Stuff Rate Edge"],
 disruption:["Havoc Allowed","Havoc Created","Sack Rate Allowed","Sack Rate Created"],
 turnovers:["Turnover Rate","Takeaway Rate"],
 field_position:["Field Position Offense","Field Position Defense Edge"],
 downs_profile:["Standard Downs Offense","Standard Downs Defense Edge","Passing Downs Offense","Passing Downs Defense Edge"],
 special_teams:["Special Teams Rating"],
 talent_roster:["Talent Rating","Recruiting Rating","Portal Rating","Returning Production","Returning Passing","Returning Receiving","Returning Rushing"],
 continuity:["QB Continuity","Coaching Continuity","Coordinator Continuity"],
 pace_style:["Pace Seconds Per Play","Plays Per Game","Possessions Per Game"]
};
function fv(g:G,cols:string[]){return cols.map(c=>{const h=num(g.hr[c]),a=num(g.ar[c]);return h==null||a==null?0:h-a})}
function solve(M:number[][],b:number[]){const n=b.length,A=M.map((x,i)=>[...x,b[i]]);for(let i=0;i<n;i++){let p=i;for(let j=i+1;j<n;j++)if(Math.abs(A[j][i])>Math.abs(A[p][i]))p=j;[A[i],A[p]]=[A[p],A[i]];if(Math.abs(A[i][i])<1e-10)return Array(n).fill(0);const d=A[i][i];for(let j=i;j<=n;j++)A[i][j]/=d;for(let k=0;k<n;k++)if(k!==i){const f=A[k][i];for(let j=i;j<=n;j++)A[k][j]-=f*A[i][j]}}return A.map(x=>x[n])}
function fit(train:G[],cols:string[],alpha:number){const X=train.map(g=>fv(g,cols)),mu=cols.map((_,j)=>avg(X.map(x=>x[j]))),sd=cols.map((_,j)=>Math.sqrt(avg(X.map(x=>(x[j]-mu[j])**2)))||1),Z=X.map(x=>[1,...x.map((v,j)=>(v-mu[j])/sd[j])]),y=train.map(g=>g.am-g.pm),p=cols.length+1,M=Array.from({length:p},()=>Array(p).fill(0)),b=Array(p).fill(0);for(let i=0;i<Z.length;i++)for(let j=0;j<p;j++){b[j]+=Z[i][j]*y[i];for(let q=0;q<p;q++)M[j][q]+=Z[i][j]*Z[i][q]}for(let j=1;j<p;j++)M[j][j]+=alpha;return{mu,sd,b:solve(M,b)}}
function predict(g:G,cols:string[],m:any){const x=fv(g,cols);return g.pm+m.b[0]+x.reduce((s,v,j)=>s+m.b[j+1]*(v-m.mu[j])/m.sd[j],0)}
function mae(rows:G[],fn:(g:G)=>number){return avg(rows.map(g=>Math.abs(fn(g)-g.am)))}
function evalCols(games:G[],date:string,cols:string[],alpha:number){const tr=games.filter(g=>g.date<date),te=games.filter(g=>g.date===date),m=fit(tr,cols,alpha),raw=mae(te,g=>g.pm),bias=avg(tr.map(g=>g.am-g.pm)),bc=mae(te,g=>g.pm+bias),mod=mae(te,g=>predict(g,cols,m));return{date,n:te.length,trainN:tr.length,raw:r(raw),biasCorrected:r(bc),model:r(mod),improvementVsRaw:r(raw-mod),incrementVsBias:r(bc-mod),coefficients:cols.map((c,i)=>({feature:c,stdCoef:r(m.b[i+1])}))}}
function flatten(names:string[]){return [...new Set(names.flatMap(n=>GROUPS[n]))]}
function combos(xs:string[],max=3){const out:string[][]=[];function rec(start:number,cur:string[]){if(cur.length){out.push([...cur]);if(cur.length===max)return}for(let i=start;i<xs.length;i++){cur.push(xs[i]);rec(i+1,cur);cur.pop()}}rec(0,[]);return out}
export async function GET(){const [slate,schedule,ratings]=await Promise.all([readSportWorksheet("NCAAF","daily_slate") as Promise<R[]>,readSportWorksheet("NCAAF","schedule") as Promise<R[]>,readSportWorksheet("NCAAF","team_ratings") as Promise<R[]>]);const actual=new Map<string,{a:number,h:number}>();for(const x of schedule){const a=num(x["Away Score"]),h=num(x["Home Score"]);if(a==null||h==null||(a===0&&h===0))continue;for(const z of schedKeys(x))actual.set(z,{a,h})}const byTeam=new Map<string,R[]>();for(const x of ratings){const k0=key(teamName(x));if(!k0)continue;if(!byTeam.has(k0))byTeam.set(k0,[]);byTeam.get(k0)!.push(x)}for(const z of byTeam.values())z.sort((a,b)=>projWeek(a)-projWeek(b));const getR=(team:string,w:number)=>{const z=byTeam.get(key(team))||[],ex=z.filter(x=>projWeek(x)===w);if(ex.length)return ex.at(-1)!;const pr=z.filter(x=>projWeek(x)<=w);return pr.at(-1)||null};const ded=new Map<string,R>();for(const x of slate)ded.set(sKey(x),x);const games:G[]=[];for(const x of ded.values()){const ac=actual.get(sKey(x))||actual.get(`${dk(x.Date)}|${key(t(x["Away Team"]))}|${key(t(x["Home Team"]))}`),pm=num(x["Projected Margin"]),w=num(x.Week);if(!ac||pm==null||w==null)continue;const ar=getR(t(x["Away Team"]),w),hr=getR(t(x["Home Team"]),w);if(!ar||!hr||t(ar.Classification).toUpperCase()!=="FBS"||t(hr.Classification).toUpperCase()!=="FBS")continue;games.push({date:dk(x.Date),week:w,pm,am:ac.h-ac.a,ar,hr})}games.sort((a,b)=>a.date.localeCompare(b.date));const folds=["2026-09-12","2026-09-19","2026-09-26"].filter(d=>games.some(g=>g.date===d)),alphas=[5,20,80];const groups=Object.entries(GROUPS).map(([name,cols])=>({name,cols,alphaResults:alphas.map(alpha=>({alpha,folds:folds.map(d=>evalCols(games,d,cols,alpha))}))}));const baseFolds=folds.map(d=>evalCols(games,d,[],20));const devDates=folds.slice(0,2),holdDate=folds.at(-1)!;const devEligible=groups.filter(g=>{const a=g.alphaResults.find(x=>x.alpha===20)!;return devDates.every(d=>(a.folds.find(f=>f.date===d)?.incrementVsBias??-99)>0)}).map(g=>g.name);const searchPool=devEligible.length?devEligible:Object.keys(GROUPS);const candidates=[] as any[];for(const names of combos(searchPool,3))for(const alpha of alphas){const cols=flatten(names),fs=folds.map(d=>evalCols(games,d,cols,alpha)),dev=avg(fs.filter(f=>devDates.includes(f.date)).map(f=>f.incrementVsBias));candidates.push({names,alpha,devIncrementVsBias:r(dev),folds:fs})}candidates.sort((a,b)=>b.devIncrementVsBias-a.devIncrementVsBias);const best=candidates[0]||null;return NextResponse.json({source:{fbsGames:games.length,dates:[...new Set(games.map(g=>g.date))],folds},baseline:{folds:baseFolds},groupTests:groups,devEligible,strictDevSelected:best?{names:best.names,alpha:best.alpha,devIncrementVsBias:best.devIncrementVsBias,folds:best.folds}:null,topDevCandidates:candidates.slice(0,15).map(x=>({names:x.names,alpha:x.alpha,devIncrementVsBias:x.devIncrementVsBias,holdout:x.folds.find((f:any)=>f.date===holdDate)}))})}
