import { NextResponse } from "next/server";
import { readSportWorksheet } from "../../../../lib/sportSheets";
export const dynamic="force-dynamic";export const revalidate=0;
type Row=Record<string,string>;type R={date:string;player:string;line:number;projection:number;actual:number;targets:number;actualTargets:number|null;eff:number;actualEff:number|null;routes:number;tprr:number;routePart:number;role:number};
const PRIOR=6.15;const text=(v:unknown)=>String(v??"").trim();const num=(v:unknown)=>{const n=Number(text(v));return Number.isFinite(n)?n:null};const round=(v:number|null,d=2)=>v==null?null:Number(v.toFixed(d));const mean=(a:number[])=>a.length?a.reduce((s,x)=>s+x,0)/a.length:null;const key=(r:Row,l=false)=>`${text(r.Date)}|${text(r.Player)}|${text(r.Market)}${l?`|${text(r["Market Line"])}`:""}`;const role=(s:unknown)=>{const m=text(s).match(/live role(?:\/injury)? overlay\s+([0-9.]+)x/i);return m?Number(m[1]):1};
function arch(r:R){const native=r.routes*r.tprr;return native>r.targets&&native/r.targets>=1.15&&r.routePart>=0.45&&r.tprr>=0.20&&r.role<0.85}
function targetDown(r:R){const native=r.routes*r.tprr;if(native>=r.targets)return r.targets;return Math.max(0,r.targets+Math.max(-1,native-r.targets))}
function targetUp(r:R){if(!arch(r))return r.targets;const native=r.routes*r.tprr;return r.targets+Math.min(1.5,native-r.targets)}
function targetHybrid(r:R){const native=r.routes*r.tprr;if(native<r.targets)return targetDown(r);return targetUp(r)}
type Mode="current"|"down"|"up"|"hybrid"|"hybridPrior"|"hybridPrior50";
function vals(r:R,mode:Mode){let t=r.targets,e=r.eff;if(mode==="down")t=targetDown(r);if(mode==="up")t=targetUp(r);if(mode.startsWith("hybrid"))t=targetHybrid(r);if(arch(r)&&mode==="hybridPrior")e=Math.max(e,PRIOR);if(arch(r)&&mode==="hybridPrior50"&&e<PRIOR)e=0.5*e+0.5*PRIOR;return{t,e,p:r.projection*(t/r.targets)*(e/r.eff)}}
function result(r:R,p:number){if(r.line<=0)return"NA";if(r.actual===r.line)return"P";return p>=r.line?(r.actual>r.line?"W":"L"):(r.actual<r.line?"W":"L")}
function summary(rows:R[],mode:Mode){let w=0,l=0,p=0;const ae:number[]=[],te:number[]=[],ee:number[]=[];for(const r of rows){const v=vals(r,mode);ae.push(Math.abs(r.actual-v.p));if(r.actualTargets!=null)te.push(Math.abs(r.actualTargets-v.t));if(r.actualEff!=null)ee.push(Math.abs(r.actualEff-v.e));const z=result(r,v.p);if(z==="W")w++;else if(z==="L")l++;else if(z==="P")p++;}return{n:rows.length,mae:round(mean(ae)),targetMae:round(mean(te)),effMae:round(mean(ee)),marketN:w+l+p,record:`${w}-${l}-${p}`,winPct:w+l?round(100*w/(w+l),1):null}}
export async function GET(){const[cal,proj]=await Promise.all([readSportWorksheet("NFL","prop_calibration") as Promise<Row[]>,readSportWorksheet("NFL","prop_projections") as Promise<Row[]>]);const exact=new Map<string,Row>(),fallback=new Map<string,Row>();for(const p of proj){if(text(p.Market)!=="Receiving Yards"||text(p.Position)!=="RB")continue;exact.set(key(p,true),p);fallback.set(key(p,false),p)}const rows:R[]=[];const seen=new Set<string>();for(const c of cal){if(text(c.Market)!=="Receiving Yards"||text(c.Position)!=="RB")continue;const projection=num(c.Projection),actual=num(c["Actual Result"]),targets=num(c["Projected Opportunity"]),eff=num(c["Projected Efficiency"]),line=num(c["Market Line"])??0;if(projection==null||actual==null||targets==null||eff==null||targets<=0||eff<=0)continue;const p=exact.get(key(c,true))||fallback.get(key(c,false))||{};const routes=num(p["Projected Routes"]),tprr=num(p["Targets Per Route"]),routePart=num(p["Route Participation"]);if(routes==null||tprr==null||routePart==null)continue;const d=`${key(c,true)}|${projection}`;if(seen.has(d))continue;seen.add(d);rows.push({date:text(c.Date),player:text(c.Player),line,projection,actual,targets,actualTargets:num(c["Actual Opportunity"]),eff,actualEff:num(c["Actual Efficiency"]),routes,tprr,routePart,role:role(p.Confluence)})}rows.sort((a,b)=>a.date.localeCompare(b.date)||a.player.localeCompare(b.player));const pre=rows.filter(r=>r.date<"2026-09-27"),hold=rows.filter(r=>r.date==="2026-09-27");const modes:Mode[]=["current","down","up","hybrid","hybridPrior50","hybridPrior"];const pack=(z:R[])=>Object.fromEntries(modes.map(m=>[m,summary(z,m)]));return NextResponse.json({counts:{all:rows.length,pre:pre.length,holdout:hold.length,marketLined:rows.filter(r=>r.line>0).length,archAll:rows.filter(arch).length,archPre:pre.filter(arch).length,archHoldout:hold.filter(arch).length},pre:pack(pre),holdout:pack(hold),all:pack(rows),gibbs:rows.filter(r=>/jahmyr\s+gibbs/i.test(r.player)).map(r=>({date:r.date,line:r.line,actual:r.actual,currentTargets:r.targets,routeTargets:round(r.routes*r.tprr),actualTargets:r.actualTargets,currentEff:r.eff,actualEff:r.actualEff,role:r.role,routePart:r.routePart,tprr:r.tprr,archetype:arch(r),current:round(vals(r,"current").p),up:round(vals(r,"up").p),hybrid:round(vals(r,"hybrid").p),hybridPrior50:round(vals(r,"hybridPrior50").p),hybridPrior:round(vals(r,"hybridPrior").p)}))});}
