import { NextResponse } from "next/server";
import { readSportWorksheet } from "../../../../lib/sportSheets";
export const dynamic="force-dynamic"; export const revalidate=0;
type Row=Record<string,string>;type R={date:string;player:string;line:number;projection:number;actual:number;carries:number;actualCarries:number|null;eff:number;role:number;attempts:number|null;attemptRole:number};
const text=(v:unknown)=>String(v??"").trim();const num=(v:unknown)=>{const n=Number(text(v));return Number.isFinite(n)?n:null};const round=(v:number|null,d=2)=>v==null?null:Number(v.toFixed(d));const mean=(a:number[])=>a.length?a.reduce((s,x)=>s+x,0)/a.length:null;const key=(r:Row)=>`${text(r.Date)}|${text(r.Player)}`;const role=(s:unknown)=>{const m=text(s).match(/live role(?:\/injury)? overlay\s+([0-9.]+)x/i);return m?Number(m[1]):1};
function result(r:R,p:number){if(r.line<=0)return"NA";if(r.actual===r.line)return"P";return p>=r.line?(r.actual>r.line?"W":"L"):(r.actual<r.line?"W":"L")}
type C={source:"current"|"yardsNoRole"|"attempts"|"attemptsNoRole"|"blendNoRole";w:number;cap:number};
function target(r:R,c:C){const yrNo=r.carries/(r.role>0?r.role:1);const att=r.attempts??r.carries;const attNo=att/(r.attemptRole>0?r.attemptRole:1);let anchor=r.carries;if(c.source==="yardsNoRole")anchor=yrNo;if(c.source==="attempts")anchor=att;if(c.source==="attemptsNoRole")anchor=attNo;if(c.source==="blendNoRole")anchor=.5*yrNo+.5*attNo;let delta=anchor-r.carries;delta=Math.max(-c.cap,Math.min(c.cap,delta));return Math.max(0,r.carries+c.w*delta)}
function summary(rows:R[],c:C){let w=0,l=0,push=0;const ae:number[]=[],ce:number[]=[];for(const r of rows){const carries=target(r,c),p=r.projection*(carries/r.carries);ae.push(Math.abs(r.actual-p));if(r.actualCarries!=null)ce.push(Math.abs(r.actualCarries-carries));const z=result(r,p);if(z==="W")w++;else if(z==="L")l++;else if(z==="P")push++;}return{n:rows.length,mae:round(mean(ae)),carryMae:round(mean(ce)),marketN:w+l+push,record:`${w}-${l}-${push}`,winPct:w+l?round(100*w/(w+l),1):null}}
function grid(train:R[]){const out:{c:C;s:ReturnType<typeof summary>}[]=[];for(const source of ["yardsNoRole","attempts","attemptsNoRole","blendNoRole"] as const)for(const w of [.25,.5,.75,1])for(const cap of [1,2,3,5,99]){const c={source,w,cap};out.push({c,s:summary(train,c)})}out.sort((a,b)=>(a.s.mae??999)-(b.s.mae??999)||(a.s.carryMae??999)-(b.s.carryMae??999));return out}
export async function GET(){const[cal,proj]=await Promise.all([readSportWorksheet("NFL","prop_calibration") as Promise<Row[]>,readSportWorksheet("NFL","prop_projections") as Promise<Row[]>]);const yards=new Map<string,Row>(),attempts=new Map<string,Row>();for(const p of proj){if(text(p.Position)!=="RB")continue;if(text(p.Market)==="Rushing Yards")yards.set(key(p),p);if(text(p.Market)==="Rushing Attempts")attempts.set(key(p),p)}const rows:R[]=[];const seen=new Set<string>();const samples:any[]=[];for(const c of cal){if(text(c.Market)!=="Rushing Yards"||text(c.Position)!=="RB")continue;const projection=num(c.Projection),actual=num(c["Actual Result"]),carries=num(c["Projected Opportunity"]),eff=num(c["Projected Efficiency"]),line=num(c["Market Line"])??0;if(projection==null||actual==null||carries==null||eff==null||carries<=0)continue;const k=key(c),yp=yards.get(k)||{},ap=attempts.get(k)||{};const att=num(ap.Projection)??num(ap["Projected Player Attempts"]);const d=`${k}|${projection}`;if(seen.has(d))continue;seen.add(d);rows.push({date:text(c.Date),player:text(c.Player),line,projection,actual,carries,actualCarries:num(c["Actual Opportunity"]),eff,role:role(yp.Confluence),attempts:att,attemptRole:role(ap.Confluence)});if(samples.length<12)samples.push({date:text(c.Date),player:text(c.Player),yardCarries:carries,attemptProjection:att,yardRole:role(yp.Confluence),attemptRole:role(ap.Confluence),attemptProjectedPlayerAttempts:num(ap["Projected Player Attempts"])})}rows.sort((a,b)=>a.date.localeCompare(b.date)||a.player.localeCompare(b.player));const usable=rows.filter(r=>r.attempts!=null&&r.attempts>0),pre=usable.filter(r=>r.date<"2026-09-27"),hold=usable.filter(r=>r.date==="2026-09-27");const current:C={source:"current",w:0,cap:99},ranked=grid(pre),best=ranked[0];const pack=(c:C)=>({rule:c,pre:summary(pre,c),holdout:summary(hold,c),all:summary(usable,c)});return NextResponse.json({counts:{allRows:rows.length,usable:usable.length,pre:pre.length,holdout:hold.length},samples,current:pack(current),best:pack(best.c),top10:ranked.slice(0,10)});}
