import { NextResponse } from "next/server";
import { readSportWorksheet } from "../../../../lib/sportSheets";
export const dynamic="force-dynamic"; export const revalidate=0;
type R=Record<string,string>; const t=(v:unknown)=>String(v??"").trim(); const k=(v:unknown)=>t(v).toLowerCase().replace(/[^a-z0-9]+/g," ").replace(/\s+/g," ").trim(); const n=(v:unknown)=>{const x=Number(t(v).replace(/%/g,""));return Number.isFinite(x)?x:null};
function d(v:unknown){const s=t(v),m=s.match(/(20\d{2})[-/](\d{1,2})[-/](\d{1,2})/);return m?`${m[1]}-${m[2].padStart(2,"0")}-${m[3].padStart(2,"0")}`:""}
const yard=new Set(["Rushing Yards","Receiving Yards"]); const countMarket=(m:string)=>m==="Rushing Yards"?"Rushing Attempts":m==="Receiving Yards"?"Targets":"";
function key(r:R,m?:string){return[d(r.Date||r["Game Date"]),k(r.Player||r["Player Name"]),k(m??r.Market)].join("|")}
function sum(a:any[]){const mean=(f:(x:any)=>number|null)=>{const z=a.map(f).filter((x):x is number=>x!=null&&Number.isFinite(x));return z.length?+(z.reduce((s,x)=>s+x,0)/z.length).toFixed(3):null}; const dir=(field:string)=>a.filter(x=>Math.sign(x[field]-x.line)===Math.sign(x.actual-x.line)).length; return {n:a.length,finalMAE:mean(x=>Math.abs(x.actual-x.final)),preSlotMAE:mean(x=>Math.abs(x.actual-x.preSlot)),lineMAE:mean(x=>Math.abs(x.actual-x.line)),finalDirection:+(100*dir("final")/Math.max(1,a.length)).toFixed(1),preSlotDirection:+(100*dir("preSlot")/Math.max(1,a.length)).toFixed(1),avgFinalGap:mean(x=>Math.abs(x.final-x.line)),avgPreSlotGap:mean(x=>Math.abs(x.preSlot-x.line)),finalOppMAE:mean(x=>x.finalOpp==null||x.actualOpp==null?null:Math.abs(x.actualOpp-x.finalOpp)),preSlotOppMAE:mean(x=>x.preSlotOpp==null||x.actualOpp==null?null:Math.abs(x.actualOpp-x.preSlotOpp))}}
function grp(a:any[],f:(x:any)=>string){const o:Record<string,any>={}; for(const z of [...new Set(a.map(f))].sort())o[z]=sum(a.filter(x=>f(x)===z)); return o}
export async function GET(){const[p,tr]=await Promise.all([readSportWorksheet("NFL","prop_projections") as Promise<R[]>,readSportWorksheet("NFL","prop_tracker") as Promise<R[]>]); const v=p.filter(r=>t(r["Model Version"]).includes("v4.18")); const map=new Map(v.map(r=>[key(r),r])); const rows:any[]=[]; for(const r of tr){if(!t(r["Model Version"]).includes("v4.18")||!yard.has(t(r.Market)))continue; const actual=n(r["Actual Result"]),line=n(r["Market Line"]),final=n(r.Projection),mi=n(r["Matchup Index"]); if(actual==null||line==null||final==null||mi==null||mi<=0)continue; const pr=map.get(key(r)); const cm=countMarket(t(r.Market)); const cr=map.get(key(r,cm)); const cproj=cr?n(cr.Projection):null, cmi=cr?n(cr["Matchup Index"]):null; const finalOpp=t(r.Market)==="Rushing Yards"?n(r["Projected Player Attempts"]):n(r["Projected Targets"]); const actualOpp=t(r.Market)==="Rushing Yards"?n(r["Actual Attempts"]):n(r["Actual Targets"]); const preSlot=final/mi; const preSlotOpp=cproj!=null&&cmi!=null&&cmi>0?cproj/cmi:null; rows.push({date:d(r.Date),player:t(r.Player),market:t(r.Market),slot:t(r.Slot),line,actual,final,matchupIndex:mi,preSlot:+preSlot.toFixed(2),finalOpp,actualOpp,standaloneCount:cproj,countMatchupIndex:cmi,preSlotOpp:preSlotOpp==null?null:+preSlotOpp.toFixed(2),confluence:t(pr?.Confluence||r.Confluence)})} return NextResponse.json({overall:sum(rows),byMarket:grp(rows,x=>x.market),bySlot:grp(rows,x=>x.slot||"blank"),rows})}