import { NextResponse } from "next/server";
import { readSportWorksheet } from "../../../../lib/sportSheets";
export const dynamic="force-dynamic";export const revalidate=0;
type Row=Record<string,string>;type R={date:string;player:string;line:number;projection:number;actual:number;carries:number;actualCarries:number|null;eff:number;actualEff:number|null;role:number;matchup:number;slot:string};
const PRIOR=4.25;const text=(v:unknown)=>String(v??"").trim();const num=(v:unknown)=>{const n=Number(text(v));return Number.isFinite(n)?n:null};const round=(v:number|null,d=2)=>v==null?null:Number(v.toFixed(d));const mean=(a:number[])=>a.length?a.reduce((s,x)=>s+x,0)/a.length:null;const key=(r:Row,l=false)=>`${text(r.Date)}|${text(r.Player)}|${text(r.Market)}${l?`|${text(r["Market Line"])}`:""}`;const role=(s:unknown)=>{const m=text(s).match(/live role(?:\/injury)? overlay\s+([0-9.]+)x/i);return m?Number(m[1]):1};
function result(r:R,p:number){if(r.line<=0)return"NA";if(r.actual===r.line)return"P";return p>=r.line?(r.actual>r.line?"W":"L"):(r.actual<r.line?"W":"L")}
type C={carryScale:number;effPrior:number;matchupStrength:number};
function vals(r:R,c:C){const ro=r.role>0?r.role:1,mi=r.matchup>0?r.matchup:1;const carries=Math.max(0,(r.carries/ro)*c.carryScale);const eff=Math.max(0,(1-c.effPrior)*r.eff+c.effPrior*PRIOR);const matchFactor=(1+c.matchupStrength*(mi-1))/mi;const p=r.projection*(carries/r.carries)*(eff/r.eff)*matchFactor;return{carries,eff,p}}
function summary(rows:R[],c:C){let w=0,l=0,push=0;const ae:number[]=[],ce:number[]=[],ee:number[]=[];for(const r of rows){const v=vals(r,c);ae.push(Math.abs(r.actual-v.p));if(r.actualCarries!=null)ce.push(Math.abs(r.actualCarries-v.carries));if(r.actualEff!=null)ee.push(Math.abs(r.actualEff-v.eff));const z=result(r,v.p);if(z==="W")w++;else if(z==="L")l++;else if(z==="P")push++;}return{n:rows.length,mae:round(mean(ae)),carryMae:round(mean(ce)),effMae:round(mean(ee)),marketN:w+l+push,record:`${w}-${l}-${push}`,winPct:w+l?round(100*w/(w+l),1):null}}
function grid(train:R[]){const out:{c:C;s:ReturnType<typeof summary>}[]=[];for(const carryScale of [.65,.7,.75,.8,.85,.9,.95,1,1.05,1.1])for(const effPrior of [0,.25,.5])for(const matchupStrength of [.5,.75,1]){const c={carryScale,effPrior,matchupStrength};out.push({c,s:summary(train,c)})}out.sort((a,b)=>(a.s.mae??999)-(b.s.mae??999)||(a.s.carryMae??999)-(b.s.carryMae??999));return out}
function slotPack(rows:R[],c:C){return Object.fromEntries(["RB1","RB2"].map(slot=>[slot,summary(rows.filter(r=>r.slot===slot),c)]))}
export async function GET(){const[cal,proj]=await Promise.all([readSportWorksheet("NFL","prop_calibration") as Promise<Row[]>,readSportWorksheet("NFL","prop_projections") as Promise<Row[]>]);const exact=new Map<string,Row>(),fallback=new Map<string,Row>();for(const p of proj){if(text(p.Market)!=="Rushing Yards"||text(p.Position)!=="RB")continue;exact.set(key(p,true),p);fallback.set(key(p,false),p)}const rows:R[]=[];const seen=new Set<string>();for(const c of cal){if(text(c.Market)!=="Rushing Yards"||text(c.Position)!=="RB")continue;const projection=num(c.Projection),actual=num(c["Actual Result"]),carries=num(c["Projected Opportunity"]),eff=num(c["Projected Efficiency"]),line=num(c["Market Line"])??0;if(projection==null||actual==null||carries==null||eff==null||carries<=0||eff<=0)continue;const p=exact.get(key(c,true))||fallback.get(key(c,false))||{};const d=`${key(c,true)}|${projection}`;if(seen.has(d))continue;seen.add(d);rows.push({date:text(c.Date),player:text(c.Player),line,projection,actual,carries,actualCarries:num(c["Actual Opportunity"]),eff,actualEff:num(c["Actual Efficiency"]),role:role(p.Confluence),matchup:num(p["Matchup Index"])??1,slot:text(p.Slot)})}rows.sort((a,b)=>a.date.localeCompare(b.date)||a.player.localeCompare(b.player));const pre=rows.filter(r=>r.date<"2026-09-27"),hold=rows.filter(r=>r.date==="2026-09-27");const ranked=grid(pre),best=ranked[0],pure=ranked.filter(x=>x.c.effPrior===0&&x.c.matchupStrength===1).sort((a,b)=>(a.s.mae??999)-(b.s.mae??999))[0];const pack=(c:C)=>({rule:c,pre:summary(pre,c),holdout:summary(hold,c),all:summary(rows,c),holdoutBySlot:slotPack(hold,c),allBySlot:slotPack(rows,c)});return NextResponse.json({counts:{all:rows.length,pre:pre.length,holdout:hold.length},current:pack({carryScale:1,effPrior:0,matchupStrength:1}),bestPureCarry:pack(pure.c),bestJoint:pack(best.c),topPure:ranked.filter(x=>x.c.effPrior===0&&x.c.matchupStrength===1).slice(0,10),topJoint:ranked.slice(0,10)});}
