import { NextResponse } from "next/server";
import { readSportWorksheet } from "../../../../lib/sportSheets";
export const dynamic="force-dynamic";export const revalidate=0;
type R=Record<string,string>;
const t=(v:unknown)=>String(v??"").trim();const n=(v:unknown)=>{const x=Number(t(v));return Number.isFinite(x)?x:null};
const keyTeam=(s:string)=>s.toUpperCase().replace(/[^A-Z0-9]/g,"");const dk=(s:string)=>t(s).slice(0,10);
const slateKey=(r:R)=>t(r["Game ID"])?`id:${t(r["Game ID"])}`:`${dk(r.Date)}|${keyTeam(t(r["Away Team"]))}|${keyTeam(t(r["Home Team"]))}`;
const schedKeys=(r:R)=>{const a:string[]=[];if(t(r["Game ID"]))a.push(`id:${t(r["Game ID"])}`);a.push(`${dk(r["Game Date"])}|${keyTeam(t(r["Away Team"]))}|${keyTeam(t(r["Home Team"]))}`);return a};
function correctedGrade(r:R){const pick=t(r["Total Pick"]),p=n(r["Total Probability"])??0,e=n(r["Total Edge"])??0,rel=n(r.Reliability)??0,conf=n(r["Total Confluence"])??0;const side=pick.toLowerCase().startsWith("under")?"Under":"Over";if(p>=.585&&e>=3&&rel>=70&&conf>=4)return `Strong ${side}`;if(p>=.555&&e>=1.75&&rel>=62&&conf>=3)return side;return "Non-Edge Total"}
function result(r:R,actualTotal:number){const mt=n(r["Market Total"]);if(mt==null)return"?";const under=t(r["Total Pick"]).toLowerCase().startsWith("under");const d=actualTotal-mt;const s=under?-d:d;return Math.abs(s)<1e-9?"P":s>0?"W":"L"}
function summarize(rows:any[]){const map=new Map<string,{n:number,w:number,l:number,p:number,picks:Record<string,number>}>();for(const x of rows){const g=x.grade;if(!map.has(g))map.set(g,{n:0,w:0,l:0,p:0,picks:{}});const z=map.get(g)!;z.n++;if(x.result==="W")z.w++;else if(x.result==="L")z.l++;else z.p++;z.picks[x.side]=(z.picks[x.side]??0)+1}return[...map.entries()].map(([grade,z])=>({grade,...z,winRate:z.w+z.l?Number((z.w/(z.w+z.l)).toFixed(3)):null}))}
export async function GET(){const[slate,schedule]=await Promise.all([readSportWorksheet("NFL","daily_slate") as Promise<R[]>,readSportWorksheet("NFL","schedule") as Promise<R[]>]);const actual=new Map<string,number>();for(const r of schedule){const a=n(r["Away Score"]),h=n(r["Home Score"]);if(a==null||h==null||(a===0&&h===0))continue;for(const k of schedKeys(r))actual.set(k,a+h)}const dedup=new Map<string,R>();for(const r of slate)dedup.set(slateKey(r),r);const rows:any[]=[];for(const r of dedup.values()){const at=actual.get(slateKey(r));if(at==null||(n(r.Week)??0)<=0||!t(r["Model Version"])||(n(r["Projected Total"])??0)<20)continue;const side=t(r["Total Pick"]).toLowerCase().startsWith("under")?"Under":"Over";rows.push({date:dk(r.Date),game:t(r.Game),side,currentGrade:t(r["Total Grade"]),grade:correctedGrade(r),probability:n(r["Total Probability"]),edge:n(r["Total Edge"]),reliability:n(r.Reliability),confluence:n(r["Total Confluence"]),result:result(r,at)})}const dates=[...new Set(rows.map(x=>x.date))].sort(),holdout=dates.at(-1)??"";const pre=rows.filter(x=>x.date<holdout),ho=rows.filter(x=>x.date===holdout);const mismatches=rows.filter(x=>x.currentGrade!==x.grade);return NextResponse.json({n:rows.length,holdoutDate:holdout,current:summarize(rows.map(x=>({...x,grade:x.currentGrade}))),corrected:summarize(rows),developmentCorrected:summarize(pre),holdoutCorrected:summarize(ho),mismatchCount:mismatches.length,mismatches});}