import { NextResponse } from "next/server";
import { readSportWorksheet } from "../../../../lib/sportSheets";
export const dynamic="force-dynamic"; export const revalidate=0;
type R=Record<string,string>; type G={date:string;week:number;away:string;home:string,pm:number,pt:number,ms:number|null,mt:number|null,am:number,at:number,slate:R,ar:R|null,hr:R|null};
const t=(v:unknown)=>String(v??"").trim(); const n=(v:unknown):number|null=>{const x=Number(t(v));return Number.isFinite(x)?x:null}; const k=(s:string)=>s.toUpperCase().replace(/[^A-Z0-9]/g,""); const dk=(s:string)=>t(s).slice(0,10);
const mean=(a:number[])=>a.length?a.reduce((x,y)=>x+y,0)/a.length:null; const rnd=(x:number|null,d=4)=>x==null?null:Number(x.toFixed(d));
function corr(x:number[],y:number[]){if(x.length<5||x.length!==y.length)return null;const mx=mean(x)!,my=mean(y)!;let a=0,b=0,c=0;for(let i=0;i<x.length;i++){const dx=x[i]-mx,dy=y[i]-my;a+=dx*dy;b+=dx*dx;c+=dy*dy}return b>0&&c>0?a/Math.sqrt(b*c):null}
function sKey(r:R){const id=t(r["Game ID"]);return id?`id:${id}`:`${dk(r.Date)}|${k(t(r["Away Team"]))}|${k(t(r["Home Team"]))}`}; function schedKeys(r:R){const out:string[]=[];const id=t(r["Game ID"]);if(id)out.push(`id:${id}`);out.push(`${dk(r["Game Date"])}|${k(t(r["Away Team"]))}|${k(t(r["Home Team"]))}`);return out}
function teamName(r:R){for(const q of ["Team","School","team","school","Name"]){if(t(r[q]))return t(r[q])}return ""} function projWeek(r:R){for(const q of ["Projection Week","Week","week"]){const v=n(r[q]);if(v!=null)return v}return 0}
function pearsonRows(rows:G[],getX:(g:G)=>number|null,getY:(g:G)=>number|null){const x:number[]=[],y:number[]=[];for(const g of rows){const a=getX(g),b=getY(g);if(a!=null&&b!=null&&Number.isFinite(a)&&Number.isFinite(b)){x.push(a);y.push(b)}}return {n:x.length,corr:rnd(corr(x,y))}}
function ratingValue(g:G,col:string,mode:"diff"|"avg"){if(!g.ar||!g.hr)return null;const a=n(g.ar[col]),h=n(g.hr[col]);if(a==null||h==null)return null;return mode==="diff"?h-a:(h+a)/2}
function marketMargin(g:G){return g.ms==null?null:-g.ms}
function featureStats(rows:G[],col:string,mode:"diff"|"avg",kind:"spread"|"total"){
 const yActual=(g:G)=>kind==="spread"?g.am:g.at; const yMarketResidual=(g:G)=>kind==="spread"?(g.ms==null?null:g.am-marketMargin(g)!):(g.mt==null?null:g.at-g.mt); const yModelResidual=(g:G)=>kind==="spread"?g.am-g.pm:g.at-g.pt;
 return {feature:col,mode,...pearsonRows(rows,g=>ratingValue(g,col,mode),yActual),marketResidualCorr:pearsonRows(rows,g=>ratingValue(g,col,mode),yMarketResidual).corr,modelResidualCorr:pearsonRows(rows,g=>ratingValue(g,col,mode),yModelResidual).corr};
}
function slateStats(rows:G[],col:string,kind:"spread"|"total"){
 const gx=(g:G)=>n(g.slate[col]); const ya=(g:G)=>kind==="spread"?g.am:g.at; const ym=(g:G)=>kind==="spread"?(g.ms==null?null:g.am-marketMargin(g)!):(g.mt==null?null:g.at-g.mt); const yr=(g:G)=>kind==="spread"?g.am-g.pm:g.at-g.pt;
 return {feature:col,...pearsonRows(rows,gx,ya),marketResidualCorr:pearsonRows(rows,gx,ym).corr,modelResidualCorr:pearsonRows(rows,gx,yr).corr};
}
function numericCols(rows:R[],exclude:Set<string>){const keys=[...new Set(rows.flatMap(r=>Object.keys(r)))];return keys.filter(c=>{if(exclude.has(c))return false;let seen=0,ok=0;for(const r of rows){if(!t(r[c]))continue;seen++;if(n(r[c])!=null)ok++}return seen>=20&&ok/seen>=0.9});}
function stableRank(dev:any[],hold:any[],key:string){const hm=new Map(hold.map(x=>[x.feature,x]));return dev.map(d=>{const h=hm.get(d.feature);const a=d[key] as number|null,b=h?.[key] as number|null;return {...d,holdout:h?{n:h.n,corr:h.corr,marketResidualCorr:h.marketResidualCorr,modelResidualCorr:h.modelResidualCorr}:null,stable:a!=null&&b!=null&&Math.sign(a)===Math.sign(b),score:a==null||b==null?null:rnd(Math.min(Math.abs(a),Math.abs(b))*((Math.sign(a)===Math.sign(b))?1:-1))}}).sort((a,b)=>(b.score??-99)-(a.score??-99));}
export async function GET(){
 const [slate,schedule,ratings]=await Promise.all([readSportWorksheet("NCAAF","daily_slate") as Promise<R[]>,readSportWorksheet("NCAAF","schedule") as Promise<R[]>,readSportWorksheet("NCAAF","team_ratings") as Promise<R[]>]);
 const actual=new Map<string,{a:number,h:number}>();for(const r of schedule){const a=n(r["Away Score"]),h=n(r["Home Score"]);if(a==null||h==null||(a===0&&h===0))continue;for(const q of schedKeys(r))actual.set(q,{a,h});}
 const byTeam=new Map<string,R[]>();for(const r of ratings){const q=k(teamName(r));if(!q)continue;if(!byTeam.has(q))byTeam.set(q,[]);byTeam.get(q)!.push(r)};for(const x of byTeam.values())x.sort((a,b)=>projWeek(a)-projWeek(b));
 const getRating=(team:string,week:number)=>{const arr=byTeam.get(k(team))||[];const exact=arr.filter(r=>projWeek(r)===week);if(exact.length)return exact.at(-1)!;const prev=arr.filter(r=>projWeek(r)<=week);return prev.length?prev.at(-1)!:(arr.at(0)||null)};
 const dd=new Map<string,R>();for(const r of slate)dd.set(sKey(r),r);const games:G[]=[];for(const r of dd.values()){const a=actual.get(sKey(r))||actual.get(`${dk(r.Date)}|${k(t(r["Away Team"]))}|${k(t(r["Home Team"]))}`);if(!a)continue;const pm=n(r["Projected Margin"]),pt=n(r["Projected Total"]),w=n(r.Week);if(pm==null||pt==null||w==null)continue;const away=t(r["Away Team"]),home=t(r["Home Team"]);games.push({date:dk(r.Date),week:w,away,home,pm,pt,ms:n(r["Market Home Spread"]),mt:n(r["Market Total"]),am:a.h-a.a,at:a.h+a.a,slate:r,ar:getRating(away,w),hr:getRating(home,w)});}
 games.sort((a,b)=>a.date.localeCompare(b.date));const dates=[...new Set(games.map(g=>g.date))].sort();const hd=dates.at(-1)||"";const dev=games.filter(g=>g.date<hd),hold=games.filter(g=>g.date===hd);
 const ratingExclude=new Set(["Season","Projection Week","Games","FBS Games"]);const rcols=numericCols(ratings,ratingExclude);const slateExclude=new Set(["Season","Week","Projected Away","Projected Home","Projected Margin","Projected Total","Market Home Spread","Market Total","Spread Probability","Spread Push Probability","Spread Edge","Total Probability","Total Push Probability","Total Edge","ML Probability","ML Odds","ML Implied Probability","ML Edge","ML Expected Value"]);const scols=numericCols(slate,slateExclude);
 const devSpread=rcols.map(c=>featureStats(dev,c,"diff","spread"));const holdSpread=rcols.map(c=>featureStats(hold,c,"diff","spread"));const devTotal=rcols.map(c=>featureStats(dev,c,"avg","total"));const holdTotal=rcols.map(c=>featureStats(hold,c,"avg","total"));
 const dsSpread=scols.map(c=>slateStats(dev,c,"spread")),hsSpread=scols.map(c=>slateStats(hold,c,"spread"));const dsTotal=scols.map(c=>slateStats(dev,c,"total")),hsTotal=scols.map(c=>slateStats(hold,c,"total"));
 return NextResponse.json({source:{games:games.length,ratingsRows:ratings.length,matchedRatings:games.filter(g=>g.ar&&g.hr).length,dates,holdoutDate:hd,ratingColumns:rcols,slateColumns:scols},spread:{ratingActual:stableRank(devSpread,holdSpread,"corr").slice(0,20),ratingMarketResidual:stableRank(devSpread,holdSpread,"marketResidualCorr").slice(0,20),ratingModelResidual:stableRank(devSpread,holdSpread,"modelResidualCorr").slice(0,20),slateMarketResidual:stableRank(dsSpread,hsSpread,"marketResidualCorr").slice(0,20)},total:{ratingActual:stableRank(devTotal,holdTotal,"corr").slice(0,20),ratingMarketResidual:stableRank(devTotal,holdTotal,"marketResidualCorr").slice(0,20),ratingModelResidual:stableRank(devTotal,holdTotal,"modelResidualCorr").slice(0,20),slateMarketResidual:stableRank(dsTotal,hsTotal,"marketResidualCorr").slice(0,20)}});
}
