import { NextResponse } from "next/server";
import { readSportWorksheet } from "../../../../lib/sportSheets";
export const dynamic="force-dynamic";export const revalidate=0;
type Row=Record<string,string>;
type R={date:string;player:string;market:string;projection:number;actual:number;projOpp:number;actualOpp:number;projEff:number;actualEff:number;version:string;gameId:string};
const t=(v:unknown)=>String(v??"").trim();const n=(v:unknown)=>{const x=Number(t(v));return Number.isFinite(x)?x:null};const mean=(a:number[])=>a.length?a.reduce((s,x)=>s+x,0)/a.length:null;const rnd=(x:number|null,d=3)=>x==null?null:Number(x.toFixed(d));
function sm(a:R[],f:(r:R)=>number,g:(r:R)=>number){const e=a.map(r=>f(r)-g(r));return{n:a.length,mae:rnd(mean(e.map(x=>Math.abs(x)))),bias:rnd(mean(e)),projectedMean:rnd(mean(a.map(f)),3),actualMean:rnd(mean(a.map(g)),3)}}
function versionNum(v:string){const m=v.match(/v(\d+)\.(\d+)/i);return m?Number(m[1])*100+Number(m[2]):99999}
function dedupeEarliest(a:R[]){const m=new Map<string,R>();for(const r of a){const k=`${r.date}|${r.player}|${r.market}`;const old=m.get(k);if(!old||versionNum(r.version)<versionNum(old.version))m.set(k,r)}return [...m.values()]}
const ATT_I=18.848437,ATT_S=0.405922;
const calibratedAttempts=(x:number)=>Math.max(0,ATT_I+ATT_S*x);
const blendWeights=[0,0.25,0.5,0.75,1];
function bestBlend(a:R[]){return blendWeights.map(w=>({weight:w,...sm(a,r=>r.projection+w*(calibratedAttempts(r.projection)-r.projection),r=>r.actual)})).sort((x,y)=>(x.mae??999)-(y.mae??999))[0]}
export async function GET(){
 const raw=await readSportWorksheet("NFL","prop_calibration") as Row[];const all:R[]=[];
 for(const x of raw){if(t(x.Position)!=="QB")continue;const market=t(x.Market);if(market!=="Passing Attempts"&&market!=="Passing Completions")continue;const projection=n(x.Projection),actual=n(x["Actual Result"]),projOpp=n(x["Projected Opportunity"]),actualOpp=n(x["Actual Opportunity"]),projEff=n(x["Projected Efficiency"]),actualEff=n(x["Actual Efficiency"]);if(projection==null||actual==null||projOpp==null||actualOpp==null||projEff==null||actualEff==null)continue;all.push({date:t(x.Date),player:t(x.Player),market,projection,actual,projOpp,actualOpp,projEff,actualEff,version:t(x["Model Version"]),gameId:t(x["Game ID"])})}
 const rows=dedupeEarliest(all),attempts=rows.filter(r=>r.market==="Passing Attempts"),comps=rows.filter(r=>r.market==="Passing Completions");const pre=(a:R[])=>a.filter(r=>r.date<"2026-09-27"),hold=(a:R[])=>a.filter(r=>r.date==="2026-09-27"),full=(a:R[])=>a.filter(r=>r.actualOpp>=15);
 const versions:any={};for(const r of all){versions[r.version]=(versions[r.version]??0)+1}
 const compRate=(r:R)=>r.projOpp>0?r.projection/r.projOpp:r.projEff;const actualRate=(r:R)=>r.actualOpp>0?r.actual/r.actualOpp:r.actualEff;
 const compUsingActualOpp=(r:R)=>r.actualOpp*compRate(r),compUsingActualRate=(r:R)=>r.projOpp*actualRate(r);
 const calAttempt=(r:R)=>calibratedAttempts(r.projection);
 const calComp=(r:R)=>calibratedAttempts(r.projOpp)*compRate(r);
 const bw=bestBlend(pre(attempts));const blendAttempt=(r:R)=>r.projection+bw.weight*(calibratedAttempts(r.projection)-r.projection);const blendComp=(r:R)=>r.projection*(r.projOpp>0?(r.projOpp+bw.weight*(calibratedAttempts(r.projOpp)-r.projOpp))/r.projOpp:1);
 const byDate=[...new Set(rows.map(r=>r.date))].sort().map(date=>{const aa=attempts.filter(r=>r.date===date),cc=comps.filter(r=>r.date===date);return{date,attempts:{current:sm(aa,r=>r.projection,r=>r.actual),calibrated:sm(aa,calAttempt,r=>r.actual),blend:sm(aa,blendAttempt,r=>r.actual)},completions:{current:sm(cc,r=>r.projection,r=>r.actual),calibratedOpportunity:sm(cc,calComp,r=>r.actual),blendOpportunity:sm(cc,blendComp,r=>r.actual)},compRate:sm(cc,compRate,actualRate)}});
 return NextResponse.json({counts:{raw:all.length,deduped:rows.length,attempts:attempts.length,completions:comps.length,attemptPre:pre(attempts).length,attemptHoldout:hold(attempts).length,compPre:pre(comps).length,compHoldout:hold(comps).length,attemptFull:full(attempts).length,compFull:full(comps).length},versions,fixedCalibration:{intercept:ATT_I,slope:ATT_S},attempts:{current:{pre:sm(pre(attempts),r=>r.projection,r=>r.actual),holdout:sm(hold(attempts),r=>r.projection,r=>r.actual),all:sm(attempts,r=>r.projection,r=>r.actual),full:sm(full(attempts),r=>r.projection,r=>r.actual)},fixedPassingYardsCalibration:{pre:sm(pre(attempts),calAttempt,r=>r.actual),holdout:sm(hold(attempts),calAttempt,r=>r.actual),all:sm(attempts,calAttempt,r=>r.actual),full:sm(full(attempts),calAttempt,r=>r.actual)},trainSelectedBlend:{config:bw,pre:sm(pre(attempts),blendAttempt,r=>r.actual),holdout:sm(hold(attempts),blendAttempt,r=>r.actual),all:sm(attempts,blendAttempt,r=>r.actual),full:sm(full(attempts),blendAttempt,r=>r.actual)}},completions:{current:{pre:sm(pre(comps),r=>r.projection,r=>r.actual),holdout:sm(hold(comps),r=>r.projection,r=>r.actual),all:sm(comps,r=>r.projection,r=>r.actual),full:sm(full(comps),r=>r.projection,r=>r.actual)},rate:{pre:sm(pre(comps),compRate,actualRate),holdout:sm(hold(comps),compRate,actualRate),all:sm(comps,compRate,actualRate)},fixedPassingYardsOpportunity:{pre:sm(pre(comps),calComp,r=>r.actual),holdout:sm(hold(comps),calComp,r=>r.actual),all:sm(comps,calComp,r=>r.actual),full:sm(full(comps),calComp,r=>r.actual)},trainSelectedOpportunityBlend:{pre:sm(pre(comps),blendComp,r=>r.actual),holdout:sm(hold(comps),blendComp,r=>r.actual),all:sm(comps,blendComp,r=>r.actual),full:sm(full(comps),blendComp,r=>r.actual)},oracleActualOpportunity:{pre:sm(pre(comps),compUsingActualOpp,r=>r.actual),holdout:sm(hold(comps),compUsingActualOpp,r=>r.actual),all:sm(comps,compUsingActualOpp,r=>r.actual)},oracleActualRate:{pre:sm(pre(comps),compUsingActualRate,r=>r.actual),holdout:sm(hold(comps),compUsingActualRate,r=>r.actual),all:sm(comps,compUsingActualRate,r=>r.actual)}},byDate});
}
