import { NextResponse } from "next/server";
import { readSportWorksheet } from "../../../../lib/sportSheets";
export const dynamic="force-dynamic";export const revalidate=0;
type R=Record<string,string>;type G={date:string,m:number,t:number,am:number,at:number};
const tx=(v:unknown)=>String(v??"").trim();const nu=(v:unknown)=>{const x=Number(tx(v));return Number.isFinite(x)?x:null};const dk=(s:string)=>tx(s).slice(0,10);const kt=(s:string)=>s.toUpperCase().replace(/[^A-Z0-9]/g,"");
const sk=(r:R)=>tx(r["Game ID"])?`id:${tx(r["Game ID"])}`:`${dk(r.Date)}|${kt(tx(r["Away Team"]))}|${kt(tx(r["Home Team"]))}`;const kk=(r:R)=>{const a:string[]=[];if(tx(r["Game ID"]))a.push(`id:${tx(r["Game ID"])}`);a.push(`${dk(r["Game Date"])}|${kt(tx(r["Away Team"]))}|${kt(tx(r["Home Team"]))}`);return a};
const mean=(a:number[])=>a.length?a.reduce((s,x)=>s+x,0)/a.length:0;const rnd=(x:number,d=3)=>Number(x.toFixed(d));
function mae(g:G[],kind:"m"|"t",fn?:(x:number)=>number){return mean(g.map(z=>Math.abs((fn?fn(z[kind]):z[kind])-(kind==="m"?z.am:z.at))))}
function fitOLS(g:G[],kind:"m"|"t"){const xs=g.map(z=>z[kind]),ys=g.map(z=>kind==="m"?z.am:z.at),xm=mean(xs),ym=mean(ys);const den=xs.reduce((s,x)=>s+(x-xm)**2,0);const b=den?xs.reduce((s,x,i)=>s+(x-xm)*(ys[i]-ym),0)/den:1,a=ym-b*xm;return{a,b}}
function evalFit(g:G[],kind:"m"|"t",f:{a:number,b:number}){return{n:g.length,mae:rnd(mae(g,kind)),calMae:rnd(mae(g,kind,x=>f.a+f.b*x)),bias:rnd(mean(g.map(z=>z[kind]-(kind==="m"?z.am:z.at)))),calBias:rnd(mean(g.map(z=>f.a+f.b*z[kind]-(kind==="m"?z.am:z.at))))}}
function grid(g:G[],kind:"m"|"t",center:number){let best:any=null;for(let s=.6;s<=1.6001;s+=.05){for(let b=-5;b<=5.001;b+=.5){const f=(x:number)=>center+s*(x-center)+b, v=mae(g,kind,f);if(!best||v<best.mae)best={slope:rnd(s,2),bias:rnd(b,1),mae:rnd(v),center}}}return best}
function evalGrid(g:G[],kind:"m"|"t",q:any){return{n:g.length,currentMae:rnd(mae(g,kind)),adjustedMae:rnd(mae(g,kind,x=>q.center+q.slope*(x-q.center)+q.bias))}}
function lodCV(g:G[],kind:"m"|"t"){const dates=[...new Set(g.map(z=>z.date))],errs:number[]=[],base:number[]=[];const fits:any[]=[];for(const d of dates){const tr=g.filter(z=>z.date!==d),te=g.filter(z=>z.date===d);if(tr.length<5)continue;const f=fitOLS(tr,kind);fits.push({heldDate:d,n:te.length,a:rnd(f.a),b:rnd(f.b),baseMae:rnd(mae(te,kind)),calMae:rnd(mae(te,kind,x=>f.a+f.b*x))});for(const z of te){const y=kind==="m"?z.am:z.at;base.push(Math.abs(z[kind]-y));errs.push(Math.abs(f.a+f.b*z[kind]-y))}}return{n:errs.length,currentMae:rnd(mean(base)),calibratedMae:rnd(mean(errs)),folds:fits}}
export async function GET(){const[sl,sc]=await Promise.all([readSportWorksheet("NFL","daily_slate") as Promise<R[]>,readSportWorksheet("NFL","schedule") as Promise<R[]>]);const ac=new Map<string,{a:number,h:number}>();for(const r of sc){const a=nu(r["Away Score"]),h=nu(r["Home Score"]);if(a==null||h==null||(a===0&&h===0))continue;for(const k of kk(r))ac.set(k,{a,h})}const de=new Map<string,R>();for(const r of sl)de.set(sk(r),r);const gs:G[]=[];for(const r of de.values()){const z=ac.get(sk(r));if(!z||(nu(r.Week)??0)<=0||!tx(r["Model Version"]))continue;const m=nu(r["Projected Margin"]),t=nu(r["Projected Total"]),pa=nu(r["Projected Away"]),ph=nu(r["Projected Home"]);if(m==null||t==null||pa==null||ph==null||pa<=0||ph<=0||t<20)continue;gs.push({date:dk(r.Date),m,t,am:z.h-z.a,at:z.h+z.a})}gs.sort((a,b)=>a.date.localeCompare(b.date));const dates=[...new Set(gs.map(x=>x.date))],hd=dates.at(-1)??"",tr=gs.filter(x=>x.date<hd),ho=gs.filter(x=>x.date===hd);const mf=fitOLS(tr,"m"),tf=fitOLS(tr,"t"),mg=grid(tr,"m",0),tg=grid(tr,"t",45);return NextResponse.json({n:gs.length,developmentN:tr.length,holdoutDate:hd,holdoutN:ho.length,margin:{ols:{fit:{a:rnd(mf.a),b:rnd(mf.b)},development:evalFit(tr,"m",mf),holdout:evalFit(ho,"m",mf),leaveDateOut:lodCV(tr,"m")},grid:{selection:mg,development:evalGrid(tr,"m",mg),holdout:evalGrid(ho,"m",mg)}},total:{ols:{fit:{a:rnd(tf.a),b:rnd(tf.b)},development:evalFit(tr,"t",tf),holdout:evalFit(ho,"t",tf),leaveDateOut:lodCV(tr,"t")},grid:{selection:tg,development:evalGrid(tr,"t",tg),holdout:evalGrid(ho,"t",tg)}}});}