import { NextResponse } from "next/server";
import { parquetReadObjects } from "hyparquet";
import { compressors } from "hyparquet-compressors";
export const dynamic="force-dynamic";export const revalidate=0;export const maxDuration=60;
const YEARS=[2020,2021,2022,2023,2024,2025],A=x=>x.length?x.reduce((a,b)=>a+b,0)/x.length:0,R=x=>Number(x.toFixed(4)),C=(x,a,b)=>Math.max(a,Math.min(b,x)),N=(v,d=NaN)=>{const x=Number(v);return Number.isFinite(x)?x:d},K=s=>String(s??"").normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/&/g,"and").replace(/[^a-zA-Z0-9]/g,"").toUpperCase();
const BASE="https://raw.githubusercontent.com/sportsdataverse/cfbfastR-cfb-data/main/cfb";
async function pq(path){const r=await fetch(`${BASE}/${path}`,{cache:"force-cache"});if(!r.ok)throw new Error(`${r.status} ${path}`);return parquetReadObjects({file:await r.arrayBuffer(),compressors})}
async function load(y){const [s,t,d,si,dr,ds]=await Promise.all([pq(`cfb_schedules/parquet/cfb_schedules_${y}.parquet`),pq(`adv_team/parquet/adv_team_${y}.parquet`),pq(`adv_defensive/parquet/adv_defensive_${y}.parquet`),pq(`adv_situational/parquet/adv_situational_${y}.parquet`),pq(`adv_drives/parquet/adv_drives_${y}.parquet`),pq(`adv_drive_scripting/parquet/adv_drive_scripting_${y}.parquet`)]);return{y,s,t,d,si,dr,ds}}
function games(rows,y){const o=[];for(const r of rows){const week=N(r.week,0),hs=N(r.home_points,N(r.home_score)),as=N(r.away_points,N(r.away_score)),home=String(r.home_team??""),away=String(r.away_team??"");if(week>0&&Number.isFinite(hs)&&Number.isFinite(as)&&home&&away)o.push({season:y,week,id:String(r.game_id??r.id??""),home,away,hs,as,neutral:Boolean(r.neutral_site)})}return o}
function byId(rows){const m=new Map();for(const r of rows){const id=String(r.game_id??"");if(!m.has(id))m.set(id,[]);m.get(id).push(r)}return m}
function scoreName(team,row,field){const a=K(team),b=K(row?.[field]??"");if(!a||!b)return-1;if(a===b)return 1e6;if(a.startsWith(b)||b.startsWith(a))return Math.min(a.length,b.length);return-1}
function best(team,rows,field){let z=null,s=-1;for(const r of rows??[]){const q=scoreName(team,r,field);if(q>s){s=q;z=r}}return s>=Math.min(6,K(team).length)?z:null}
function allMatch(team,rows,field){return(rows??[]).filter(r=>scoreName(team,r,field)>=Math.min(6,K(team).length))}
function summaries(gs,through=null){const use=through==null?gs:gs.filter(g=>g.week<through),teams=[...new Set(use.flatMap(g=>[g.home,g.away]))],by=new Map(teams.map(t=>[t,[]]));for(const g of use){by.get(g.home)?.push(g);by.get(g.away)?.push(g)}let p=new Map(teams.map(t=>[t,0]));for(let it=0;it<30;it++){const nx=new Map();for(const t of teams){const v=[];for(const g of by.get(t)??[]){let m=g.hs-g.as;if(!g.neutral)m-=2;m=C(m,-45,45);const h=t===g.home,op=h?g.away:g.home;v.push((h?m:-m)+(p.get(op)??0))}nx.set(t,v.length?A(v):0)}const c=A([...nx.values()]);p=new Map([...nx].map(([t,v])=>[t,C(v-c,-45,45)]))}const o=new Map();for(const t of teams){let f=0,a=0,n=0;for(const g of by.get(t)??[]){const h=t===g.home;f+=h?g.hs:g.as;a+=h?g.as:g.hs;n++}o.set(t,{power:p.get(t)??0,ppg:n?f/n:28,papg:n?a/n:28,games:n})}return o}
const DEF={power:0,ppg:28,papg:28,games:0},get=(m,t)=>m.get(t)??DEF,blend=(p,c)=>{const w=c.games?c.games/(c.games+4):0;return{power:(1-w)*p.power+w*c.power,ppg:(1-w)*p.ppg+w*c.ppg,papg:(1-w)*p.papg+w*c.papg,games:c.games}};
const CO={prior_own_ppg:.26670808584236927,prior_opp_papg:.22597582571150315,prior_power_gap:.3024181814544948,current_own_scoring_delta:.38741952777838656,current_opp_allowed_delta:.2716376410485099,current_power_delta:.3569282298069327,home_indicator:4.804668259201711};
function pm(g,pr,cu){const hp=get(pr,g.home),ap=get(pr,g.away),hc=get(cu,g.home),ac=get(cu,g.away),hb=blend(hp,hc),ab=blend(ap,ac);const q=(op,pp,ob,pb,h)=>CO.prior_own_ppg*op.ppg+CO.prior_opp_papg*pp.papg+CO.prior_power_gap*(op.power-pp.power)+CO.current_own_scoring_delta*(ob.ppg-op.ppg)+CO.current_opp_allowed_delta*(pb.papg-pp.papg)+CO.current_power_delta*((ob.power-pb.power)-(op.power-pp.power))+CO.home_indicator*h;return q(hp,ap,hb,ab,g.neutral?0:1)-q(ap,hp,ab,hb,0)}
const OFF={pass_epa:r=>N(r.EPA_passing_per_play,0),rush_epa:r=>N(r.EPA_rushing_per_play,0),line:r=>N(r.line_yards_per_carry,0),stuff:r=>N(r.rushing_stuff_rate,0),power:r=>N(r.rushing_power_success_rate,0),special:r=>N(r.EPA_special_teams,0)};
const SIT={rz:r=>N(r.EPA_success_rate_rz,0),third:r=>N(r.EPA_success_rate_third,0),standard:r=>N(r.EPA_success_standard_down_rate,0),passing_down:r=>N(r.EPA_success_passing_down_rate,0),early:r=>N(r.EPA_success_early_down_rate,0)};
const DR={field:r=>N(r.avg_field_position,0),yards_drive:r=>N(r.yards_per_drive,0)};
const DD={havoc:r=>N(r.havoc_total_rate,0),sack:r=>N(r.sacks_rate,0),drive_stop:r=>N(r.drive_stopped_rate,0),tfl:r=>{const p=N(r.scrimmage_plays,0);return p?N(r.TFL,0)/p:0},ints:r=>{const p=N(r.scrimmage_plays,0);return p?N(r.def_int,0)/p:0}};
const FEATURE_NAMES=["finish_def","finish_off","finish_matchup","scoring_opp_rate_matchup","points_drive_matchup","drive_stop_def","havoc_def","sack_def","tfl_def","int_def","third_matchup","rz_matchup","standard_matchup","passing_down_matchup","early_down_matchup","field_position_matchup","yards_drive_matchup","line_matchup","stuff_matchup","power_matchup","pass_epa_matchup","rush_epa_matchup","special_teams"];
function profile(g,index){const tr=index.t.get(g.id)??[],def=index.d.get(g.id)??[],si=index.si.get(g.id)??[],dr=index.dr.get(g.id)??[],ds=index.ds.get(g.id)??[];const hT=best(g.home,tr,"pos_team"),aT=best(g.away,tr,"pos_team"),hD=best(g.home,def,"def_pos_team"),aD=best(g.away,def,"def_pos_team"),hS=best(g.home,si,"pos_team"),aS=best(g.away,si,"pos_team"),hR=best(g.home,dr,"pos_team"),aR=best(g.away,dr,"pos_team"),hDS=allMatch(g.home,ds,"pos_team"),aDS=allMatch(g.away,ds,"pos_team");if(!hT||!aT||!hD||!aD||!hS||!aS||!hR||!aR||!hDS.length||!aDS.length)return null;const scripted=xs=>{let points=0,opps=0,drives=0;for(const x of xs){points+=N(x.points,0);opps+=N(x.scoring_opps,0);drives+=N(x.drives,0)}return{finish:opps?points/opps:0,oppRate:drives?opps/drives:0,ppd:drives?points/drives:0}};const one=(team,trow,drow,srow,rrow,dsrows)=>({team,off:Object.fromEntries(Object.entries(OFF).map(([k,f])=>[k,f(trow)])),sit:Object.fromEntries(Object.entries(SIT).map(([k,f])=>[k,f(srow)])),dr:Object.fromEntries(Object.entries(DR).map(([k,f])=>[k,f(rrow)])),def:Object.fromEntries(Object.entries(DD).map(([k,f])=>[k,f(drow)])),script:scripted(dsrows)});const h=one(g.home,hT,hD,hS,hR,hDS),a=one(g.away,aT,aD,aS,aR,aDS);h.allowed={...a.off,...a.sit,...a.dr,...a.script};a.allowed={...h.off,...h.sit,...h.dr,...h.script};return{g,h,a}}
function aggregate(records,through=null){const use=through==null?records:records.filter(x=>x.g.week<through),m=new Map();const add=(tm,src)=>{if(!m.has(tm))m.set(tm,{n:0,off:{},sit:{},dr:{},def:{},script:{},allowed:{}});const z=m.get(tm);z.n++;for(const part of ["off","sit","dr","def","script","allowed"])for(const[k,v]of Object.entries(src[part]??{}))z[part][k]=(z[part][k]??0)+N(v,0)};for(const x of use){add(x.g.home,x.h);add(x.g.away,x.a)}for(const z of m.values())for(const part of ["off","sit","dr","def","script","allowed"])for(const k of Object.keys(z[part]))z[part][k]/=z.n;return m}
function bv(pr,cu,part,k){const p=pr?.[part]?.[k],c=cu?.[part]?.[k],n=cu?.n??0,w=n?n/(n+4):0;if(Number.isFinite(p)&&Number.isFinite(c))return(1-w)*p+w*c;if(Number.isFinite(p))return p;if(Number.isFinite(c))return c;return 0}
function features(g,pr,cu){const hp=pr.get(g.home),ap=pr.get(g.away),hc=cu.get(g.home),ac=cu.get(g.away),V=(side,part,k)=>side==="h"?bv(hp,hc,part,k):bv(ap,ac,part,k),match=(part,k)=>(V("h",part,k)-V("a","allowed",k))-(V("a",part,k)-V("h","allowed",k)),o={};o.finish_def=V("a","allowed","finish")-V("h","allowed","finish");o.finish_off=V("h","script","finish")-V("a","script","finish");o.finish_matchup=match("script","finish");o.scoring_opp_rate_matchup=match("script","oppRate");o.points_drive_matchup=match("script","ppd");o.drive_stop_def=V("h","def","drive_stop")-V("a","def","drive_stop");o.havoc_def=V("h","def","havoc")-V("a","def","havoc");o.sack_def=V("h","def","sack")-V("a","def","sack");o.tfl_def=V("h","def","tfl")-V("a","def","tfl");o.int_def=V("h","def","ints")-V("a","def","ints");for(const k of ["third","rz","standard","passing_down","early"])o[`${k==="third"?"third":k==="rz"?"rz":k==="standard"?"standard":k==="passing_down"?"passing_down":"early_down"}_matchup`]=match("sit",k);o.field_position_matchup=match("dr","field");o.yards_drive_matchup=match("dr","yards_drive");for(const k of ["line","stuff","power","pass_epa","rush_epa"])o[`${k}_matchup`]=match("off",k);o.special_teams=V("h","off","special")-V("a","off","special");return o}
function met(rows,p){const e=rows.map((x,i)=>p[i]-x.actual),mp=A(p),ma=A(rows.map(x=>x.actual)),den=Math.sqrt(p.reduce((s,v)=>s+(v-mp)**2,0)*rows.reduce((s,x)=>s+(x.actual-ma)**2,0)),corr=den?p.reduce((s,v,i)=>s+(v-mp)*(rows[i].actual-ma),0)/den:0;return{n:rows.length,mae:R(A(e.map(Math.abs))),rmse:R(Math.sqrt(A(e.map(x=>x*x)))),bias:R(A(e)),corr:R(corr)}}
function fit1(tr,f,a){const rms=Math.sqrt(A(tr.map(x=>x.x[f]**2)))||1,z=tr.map(x=>x.x[f]/rms),y=tr.map(x=>x.actual-x.base),b=z.reduce((s,v,i)=>s+v*y[i],0)/(z.reduce((s,v)=>s+v*v,0)+a);return{rms,b}}const pred1=(rs,f,m)=>rs.map(x=>x.base+m.b*x.x[f]/m.rms);
function solve(M,b){const n=b.length,A0=M.map((r,i)=>[...r,b[i]]);for(let i=0;i<n;i++){let p=i;for(let j=i+1;j<n;j++)if(Math.abs(A0[j][i])>Math.abs(A0[p][i]))p=j;[A0[i],A0[p]]=[A0[p],A0[i]];const d=A0[i][i];if(Math.abs(d)<1e-10)return Array(n).fill(0);for(let j=i;j<=n;j++)A0[i][j]/=d;for(let k=0;k<n;k++)if(k!==i){const f=A0[k][i];for(let j=i;j<=n;j++)A0[k][j]-=f*A0[i][j]}}return A0.map(r=>r[n])}
function fitM(tr,fs,a){const rms=fs.map(f=>Math.sqrt(A(tr.map(x=>x.x[f]**2)))||1),M=Array.from({length:fs.length},()=>Array(fs.length).fill(0)),b=Array(fs.length).fill(0);for(const x of tr){const z=fs.map((f,j)=>x.x[f]/rms[j]),y=x.actual-x.base;for(let j=0;j<fs.length;j++){b[j]+=z[j]*y;for(let k=0;k<fs.length;k++)M[j][k]+=z[j]*z[k]}}for(let j=0;j<fs.length;j++)M[j][j]+=a;return{rms,b:solve(M,b)}}const predM=(rs,fs,m)=>rs.map(x=>x.base+fs.reduce((s,f,j)=>s+m.b[j]*x.x[f]/m.rms[j],0));
function combos(xs,max=3){const o=[];function rec(s,c){if(c.length){o.push([...c]);if(c.length===max)return}for(let i=s;i<xs.length;i++){c.push(xs[i]);rec(i+1,c);c.pop()}}rec(0,[]);return o}
export async function GET(){try{const data=await Promise.all(YEARS.map(load)),sched=new Map(),prof=new Map(),fullP=new Map(),fullS=new Map();for(const d of data){const gs=games(d.s,d.y),ix={t:byId(d.t),d:byId(d.d),si:byId(d.si),dr:byId(d.dr),ds:byId(d.ds)},ps=[];for(const g of gs){const p=profile(g,ix);if(p)ps.push(p)}sched.set(d.y,gs);prof.set(d.y,ps);fullP.set(d.y,aggregate(ps));fullS.set(d.y,summaries(gs))}const wP=new Map(),wS=new Map(),rows=[];for(const y of [2021,2022,2023,2024,2025])for(const p of prof.get(y)??[]){const g=p.g,k=`${y}|${g.week}`;if(!wP.has(k))wP.set(k,aggregate(prof.get(y)??[],g.week));if(!wS.has(k))wS.set(k,summaries(sched.get(y)??[],g.week));const pr=fullP.get(y-1),ps=fullS.get(y-1);if(!pr||!ps)continue;rows.push({season:y,week:g.week,id:g.id,actual:g.hs-g.as,base:pm(g,ps,wS.get(k)),x:features(g,pr,wP.get(k))})}const tr=rows.filter(x=>x.season<=2023),va=rows.filter(x=>x.season===2024),ho=rows.filter(x=>x.season===2025),base={train:met(tr,tr.map(x=>x.base)),validation:met(va,va.map(x=>x.base)),holdout:met(ho,ho.map(x=>x.base))},alphas=[1,5,20,80],sing=[];for(const f of FEATURE_NAMES)for(const a of alphas){const m=fit1(tr,f,a);sing.push({feature:f,alpha:a,coefStd:R(m.b),train:met(tr,pred1(tr,f,m)),validation:met(va,pred1(va,f,m)),holdout:met(ho,pred1(ho,f,m))})}const best=[];for(const f of FEATURE_NAMES)best.push(sing.filter(x=>x.feature===f).sort((a,b)=>a.validation.mae-b.validation.mae)[0]);best.sort((a,b)=>a.validation.mae-b.validation.mae);const pool=best.filter(x=>x.validation.mae<base.validation.mae).slice(0,10).map(x=>x.feature),multi=[];for(const fs of combos(pool,3))for(const a of alphas){const m=fitM(tr,fs,a);multi.push({features:fs,alpha:a,coefStd:fs.map((f,j)=>({feature:f,coef:R(m.b[j])})),train:met(tr,predM(tr,fs,m)),validation:met(va,predM(va,fs,m)),holdout:met(ho,predM(ho,fs,m))})}multi.sort((a,b)=>a.validation.mae-b.validation.mae);return NextResponse.json({protocol:{train:"2021-2023",validation:2024,untouchedHoldout:2025,noMarketInputs:true,pregameOnly:true},coverage:{rows:rows.length,train:tr.length,validation:va.length,holdout:ho.length},baseline:base,bestSingles:best,topCombinations:multi.slice(0,25)});}catch(e){return NextResponse.json({error:String(e?.message??e),stack:String(e?.stack??"")})}}
