import { NextResponse } from "next/server";
import { readSportWorksheet } from "../../../../lib/sportSheets";
export const dynamic="force-dynamic";export const revalidate=0;
type R=Record<string,string>;type G={date:string;week:number;away:string;home:string;aa:number;ah:number;pm:number;pt:number;ms:number|null;mt:number|null;ar:R;hr:R;s:R};type Obs={g:G;home:boolean;y:number};type F={name:string,get:(o:Obs)=>number|null};
const T=(v:unknown)=>String(v??"").trim(),N=(v:unknown):number|null=>{const x=Number(T(v));return Number.isFinite(x)?x:null},K=(s:string)=>s.toUpperCase().replace(/[^A-Z0-9]/g,""),D=(s:string)=>T(s).slice(0,10),A=(x:number[])=>x.length?x.reduce((a,b)=>a+b,0)/x.length:0,RD=(x:number,d=3)=>Number(x.toFixed(d));
function SK(r:R){const id=T(r["Game ID"]);return id?`id:${id}`:`${D(r.Date)}|${K(T(r["Away Team"]))}|${K(T(r["Home Team"]))}`};function SH(r:R){const z:string[]=[];if(T(r["Game ID"]))z.push(`id:${T(r["Game ID"])}`);z.push(`${D(r["Game Date"])}|${K(T(r["Away Team"]))}|${K(T(r["Home Team"]))}`);return z}function PW(r:R){return N(r["Projection Week"])??N(r.Week)??0}
function solve(X:number[][],y:number[],lam:number){const p=X[0]?.length??0;if(!p)return[];const M=Array.from({length:p},()=>Array(p).fill(0)),b=Array(p).fill(0);for(let i=0;i<X.length;i++)for(let j=0;j<p;j++){b[j]+=X[i][j]*y[i];for(let q=0;q<p;q++)M[j][q]+=X[i][j]*X[i][q]}for(let j=1;j<p;j++)M[j][j]+=lam;for(let i=0;i<p;i++){let z=i;for(let r=i+1;r<p;r++)if(Math.abs(M[r][i])>Math.abs(M[z][i]))z=r;[M[i],M[z]]=[M[z],M[i]];[b[i],b[z]]=[b[z],b[i]];const u=M[i][i];if(Math.abs(u)<1e-9)return[];for(let q=i;q<p;q++)M[i][q]/=u;b[i]/=u;for(let r=0;r<p;r++)if(r!==i){const f=M[r][i];for(let q=i;q<p;q++)M[r][q]-=f*M[i][q];b[r]-=f*b[i]}}return b}
function fit(obs:Obs[],fs:F[],lam:number){const good=obs.filter(o=>fs.every(f=>f.get(o)!=null));if(good.length<Math.max(30,fs.length*5))return null;const mu=fs.map(f=>A(good.map(o=>f.get(o)!))),sd=fs.map((f,j)=>Math.sqrt(A(good.map(o=>(f.get(o)!-mu[j])**2)))||1);const X=good.map(o=>[1,...fs.map((f,j)=>(f.get(o)!-mu[j])/sd[j])]),b=solve(X,good.map(o=>o.y),lam);return b.length?{b,mu,sd}:null}
function pred(o:Obs,fs:F[],m:any){return m.b[0]+fs.reduce((z,f,j)=>z+m.b[j+1]*((f.get(o)!-m.mu[j])/m.sd[j]),0)}
function evalGames(train:G[],test:G[],fs:F[],lam:number){const obs=train.flatMap(g=>[{g,home:false,y:g.aa},{g,home:true,y:g.ah}]),m=fit(obs,fs,lam);if(!m)return null;let te=0,me=0,tcur=0,mcur=0,tmkt=0,mmkt=0,n=0,nm=0;const rows:any[]=[];for(const g of test){const ao:{g:G,home:boolean,y:number}={g,home:false,y:g.aa},ho:{g:G,home:boolean,y:number}={g,home:true,y:g.ah};if(!fs.every(f=>f.get(ao)!=null&&f.get(ho)!=null))continue;const pa=pred(ao,fs,m),ph=pred(ho,fs,m),pt=pa+ph,pm=ph-pa,at=g.aa+g.ah,am=g.ah-g.aa;te+=Math.abs(pt-at);me+=Math.abs(pm-am);tcur+=Math.abs(g.pt-at);mcur+=Math.abs(g.pm-am);if(g.mt!=null&&g.ms!=null){tmkt+=Math.abs(g.mt-at);mmkt+=Math.abs(-g.ms-am);nm++}n++;rows.push({date:g.date,game:`${g.away} @ ${g.home}`,predAway:RD(pa,2),predHome:RD(ph,2),predTotal:RD(pt,2),predMargin:RD(pm,2),actualTotal:at,actualMargin:am,marketTotal:g.mt,marketMargin:g.ms==null?null:-g.ms})}return{n,totalMae:RD(te/n),marginMae:RD(me/n),currentTotalMae:RD(tcur/n),currentMarginMae:RD(mcur/n),marketTotalMae:nm?RD(tmkt/nm):null,marketMarginMae:nm?RD(mmkt/nm):null,score:RD((te/n)+(me/n)),coefficients:fs.map((f,j)=>({feature:f.name,beta:RD(m.b[j+1]??0)})),rows}}
function cv(g:G[],fs:F[],lam:number){const ds=[...new Set(g.map(x=>x.date))].sort();let tn=0,t=0,m=0,ct=0,cm=0,mt=0,mm=0,mn=0;const folds:any[]=[];for(const d of ds){const tr=g.filter(x=>x.date<d),te=g.filter(x=>x.date===d);if(tr.length<20)continue;const e=evalGames(tr,te,fs,lam);if(!e)continue;folds.push({date:d,n:e.n,totalMae:e.totalMae,marginMae:e.marginMae,currentTotalMae:e.currentTotalMae,currentMarginMae:e.currentMarginMae,marketTotalMae:e.marketTotalMae,marketMarginMae:e.marketMarginMae});tn+=e.n;t+=e.totalMae*e.n;m+=e.marginMae*e.n;ct+=e.currentTotalMae*e.n;cm+=e.currentMarginMae*e.n;if(e.marketTotalMae!=null){mt+=e.marketTotalMae*e.n;mm+=e.marketMarginMae*e.n;mn+=e.n}}return tn?{n:tn,totalMae:RD(t/tn),marginMae:RD(m/tn),currentTotalMae:RD(ct/tn),currentMarginMae:RD(cm/tn),marketTotalMae:mn?RD(mt/mn):null,marketMarginMae:mn?RD(mm/mn):null,score:RD((t+m)/tn),folds}:null}
export async function GET(){const[sl,sc,rr]=await Promise.all([readSportWorksheet("NCAAF","daily_slate") as Promise<R[]>,readSportWorksheet("NCAAF","schedule") as Promise<R[]>,readSportWorksheet("NCAAF","team_ratings") as Promise<R[]>]);const am=new Map<string,{a:number,h:number}>();for(const r of sc){const a=N(r["Away Score"]),h=N(r["Home Score"]);if(a==null||h==null||(a===0&&h===0))continue;for(const x of SH(r))am.set(x,{a,h})}const by=new Map<string,R[]>();for(const r of rr){const q=K(T(r.Team));if(!by.has(q))by.set(q,[]);by.get(q)!.push(r)}for(const a of by.values())a.sort((x,y)=>PW(x)-PW(y));const GR=(team:string,w:number)=>{const a=by.get(K(team))||[];return a.filter(r=>PW(r)<=w).at(-1)||null};const dd=new Map<string,R>();for(const r of sl)dd.set(SK(r),r);const games:G[]=[];for(const s of dd.values()){const ac=am.get(SK(s))||am.get(`${D(s.Date)}|${K(T(s["Away Team"]))}|${K(T(s["Home Team"]))}`),w=N(s.Week),pm=N(s["Projected Margin"]),pt=N(s["Projected Total"]);if(!ac||w==null||pm==null||pt==null)continue;const away=T(s["Away Team"]),home=T(s["Home Team"]),ar=GR(away,w),hr=GR(home,w);if(!ar||!hr||T(ar.Classification).toLowerCase()!=="fbs"||T(hr.Classification).toLowerCase()!=="fbs")continue;games.push({date:D(s.Date),week:w,away,home,aa:ac.a,ah:ac.h,pm,pt,ms:N(s["Market Home Spread"]),mt:N(s["Market Total"]),ar,hr,s})}games.sort((a,b)=>a.date.localeCompare(b.date));const hd=[...new Set(games.map(g=>g.date))].sort().at(-1)!,dev=games.filter(g=>g.date<hd),hold=games.filter(g=>g.date===hd);
 const team=(c:string):F=>({name:`team ${c}`,get:o=>N((o.home?o.g.hr:o.g.ar)[c])}),opp=(c:string):F=>({name:`opp ${c}`,get:o=>N((o.home?o.g.ar:o.g.hr)[c])}),ctx=(name:string,c:string,sgn=false):F=>({name,get:o=>{const v=N(o.g.s[c]);return v==null?null:sgn?(o.home?v:-v):v}}),injTeam:F={name:"team injury",get:o=>N(o.g.s[o.home?"Home Injury Adjustment":"Away Injury Adjustment"])},injOpp:F={name:"opp injury",get:o=>N(o.g.s[o.home?"Away Injury Adjustment":"Home Injury Adjustment"])};
 const groups:{name:string;f:F[]}[]=[
 {name:"scoring",f:[team("Points Per Game"),opp("Points Allowed Per Game")]},
 {name:"drive",f:[team("Points Per Drive"),opp("Points Allowed Per Drive")]},
 {name:"ratings",f:[team("Offense Rating"),opp("Defense Rating")]},
 {name:"power_prior",f:[team("Elo Rating"),opp("Elo Rating"),team("Preseason Rating"),opp("Preseason Rating")]},
 {name:"epa",f:[team("EPA/PPA Offense"),opp("EPA/PPA Defense Edge")]},
 {name:"pass",f:[team("Pass EPA/PPA"),opp("Pass Defense Edge")]},
 {name:"rush",f:[team("Rush EPA/PPA"),opp("Rush Defense Edge")]},
 {name:"success",f:[team("Success Rate Offense"),opp("Success Rate Defense Edge")]},
 {name:"explosive",f:[team("Explosiveness Offense"),opp("Explosiveness Defense Edge")]},
 {name:"line",f:[team("Line Yards Offense"),opp("Line Yards Defense Edge")]},
 {name:"havoc",f:[team("Havoc Allowed"),opp("Havoc Created")]},
 {name:"passing_downs",f:[team("Passing Downs Offense"),opp("Passing Downs Defense Edge")]},
 {name:"finishing",f:[team("Finishing Drives Offense"),opp("Finishing Drives Defense Edge")]},
 {name:"field_position",f:[team("Field Position Offense"),opp("Field Position Defense Edge")]},
 {name:"third_down",f:[team("Third Down Rate"),opp("Third Down Defense Edge")]},
 {name:"red_zone",f:[team("Red Zone TD Rate"),opp("Red Zone Defense Edge")]},
 {name:"sacks",f:[team("Sack Rate Allowed"),opp("Sack Rate Created")]},
 {name:"turnovers",f:[team("Turnover Rate"),opp("Takeaway Rate")]},
 {name:"volume",f:[team("Plays Per Game"),team("Possessions Per Game"),team("Pace Seconds Per Play")]},
 {name:"talent",f:[team("Talent Rating"),opp("Talent Rating"),team("Returning Production"),team("QB Continuity")]},
 {name:"environment",f:[ctx("signed HFA","Home Field Advantage",true),ctx("weather","Weather Adjustment"),ctx("wind","Wind"),ctx("precip","Precipitation Probability")]},
 {name:"personnel",f:[injTeam,injOpp]}
 ];
 let bestLam=2,best=cv(dev,[],2)!;for(const l of [.5,1,2,5,10,20]){const z=cv(dev,[],l);if(z&&z.score<best.score){best=z;bestLam=l}}let chosen:F[]=[],chosenGroups:string[]=[],cur=best,steps:any[]=[];for(let s=0;s<7;s++){let nx:any=null;for(const g of groups.filter(x=>!chosenGroups.includes(x.name))){const z=cv(dev,[...chosen,...g.f],bestLam);if(z&&(!nx||z.score<nx.cv.score))nx={g,cv:z}}if(!nx||nx.cv.score>=cur.score-0.12)break;chosen=[...chosen,...nx.g.f];chosenGroups.push(nx.g.name);cur=nx.cv;steps.push({added:nx.g.name,cv:nx.cv})}
 const predefined=groups.map(g=>({group:g.name,cv:cv(dev,g.f,bestLam),holdout:evalGames(dev,hold,g.f,bestLam)})).sort((a,b)=>(a.cv?.score??999)-(b.cv?.score??999));return NextResponse.json({source:{games:games.length,development:dev.length,holdout:hold.length,holdoutDate:hd},lambda:bestLam,baseline:best,steps,selectedGroups:chosenGroups,development:cur,holdout:evalGames(dev,hold,chosen,bestLam),predefined:predefined.slice(0,12)});