import { NextResponse } from "next/server";
import { readSportWorksheet } from "../../../../lib/sportSheets";
export const dynamic="force-dynamic";export const revalidate=0;
type R=Record<string,string>;type G={date:string;at:number;mt:number;f:Record<string,number>};const T=(v:unknown)=>String(v??"").trim(),N=(v:unknown)=>{const x=Number(T(v));return Number.isFinite(x)?x:null},K=(s:string)=>s.toUpperCase().replace(/[^A-Z0-9]/g,""),D=(s:string)=>T(s).slice(0,10),A=(a:number[])=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0,RD=(x:number,p=4)=>Number(x.toFixed(p)),V=(r:R,c:string,z=0)=>N(r[c])??z;
function SK(r:R){const id=T(r["Game ID"]);return id?`id:${id}`:`${D(r.Date)}|${K(T(r["Away Team"]))}|${K(T(r["Home Team"]))}`};function SH(r:R){const a=[] as string[],id=T(r["Game ID"]);if(id)a.push(`id:${id}`);a.push(`${D(r["Game Date"])}|${K(T(r["Away Team"]))}|${K(T(r["Home Team"]))}`);return a}function RK(x:string,s:number,w:number){return`${s}|${w}|${K(x)}`}
function solve(X:number[][],y:number[],lam=2){const p=X[0]?.length??0;if(!p)return[];const M=Array.from({length:p},()=>Array(p).fill(0)),b=Array(p).fill(0);for(let i=0;i<X.length;i++)for(let j=0;j<p;j++){b[j]+=X[i][j]*y[i];for(let q=0;q<p;q++)M[j][q]+=X[i][j]*X[i][q]}for(let j=0;j<p;j++)M[j][j]+=lam;for(let i=0;i<p;i++){let z=i;for(let r=i+1;r<p;r++)if(Math.abs(M[r][i])>Math.abs(M[z][i]))z=r;[M[i],M[z]]=[M[z],M[i]];[b[i],b[z]]=[b[z],b[i]];const u=M[i][i]||1e-9;for(let q=i;q<p;q++)M[i][q]/=u;b[i]/=u;for(let r=0;r<p;r++)if(r!==i){const q=M[r][i];for(let c=i;c<p;c++)M[r][c]-=q*M[i][c];b[r]-=q*b[i]}}return b}
function score(tr:G[],te:G[],fs:string[]){if(!te.length)return{n:0,mae:0,marketMae:0,improvement:0,w:0,l:0,winRate:0,betas:[]};const m:Record<string,number>={},s:Record<string,number>={};for(const f of fs){const x=tr.map(g=>g.f[f]);m[f]=A(x);s[f]=Math.sqrt(A(x.map(y=>(y-m[f])**2)))||1}const y=tr.map(g=>g.at-g.mt),ym=A(y),X=tr.map(g=>fs.map(f=>(g.f[f]-m[f])/s[f])),b=solve(X,y.map(x=>x-ym));let e=0,bm=0,w=0,l=0;for(const g of te){const r=ym+fs.reduce((q,f,j)=>q+b[j]*(g.f[f]-m[f])/s[f],0),ae=g.at-g.mt,sg=r>=0?ae:-ae;e+=Math.abs(g.mt+r-g.at);bm+=Math.abs(ae);if(sg>0)w++;else if(sg<0)l++;}return{n:te.length,mae:RD(e/te.length),marketMae:RD(bm/te.length),improvement:RD((bm-e)/te.length),w,l,winRate:RD(w+l?w/(w+l):0),betas:fs.map((f,j)=>({feature:f,beta:RD(b[j]??0)})),bias:RD(ym)}}
function wf(g:G[],name:string,fs:string[]){const folds=["2026-09-12","2026-09-19","2026-09-26"].map(dt=>({date:dt,...score(g.filter(x=>x.date<dt),g.filter(x=>x.date===dt),fs)}));return{name,features:fs,folds,avgImprovement:RD(A(folds.map(x=>x.improvement))),positiveFolds:folds.filter(x=>x.improvement>0).length}}
export async function GET(){const[sl,sc,rr]=await Promise.all([readSportWorksheet("NCAAF","daily_slate") as Promise<R[]>,readSportWorksheet("NCAAF","schedule") as Promise<R[]>,readSportWorksheet("NCAAF","team_ratings") as Promise<R[]>]);const am=new Map<string,{a:number,h:number}>();for(const r of sc){const a=N(r["Away Score"]),h=N(r["Home Score"]);if(a==null||h==null||(a===0&&h===0))continue;for(const q of SH(r))am.set(q,{a,h})}const rm=new Map<string,R>();for(const r of rr)rm.set(RK(T(r.Team),N(r.Season)??2026,N(r["Projection Week"])??0),r);const dm=new Map<string,R>();for(const r of sl)dm.set(SK(r),r);const games:G[]=[];for(const r of dm.values()){const ac=am.get(SK(r))||am.get(`${D(r.Date)}|${K(T(r["Away Team"]))}|${K(T(r["Home Team"]))}`);if(!ac)continue;const s=N(r.Season)??2026,w=N(r.Week)??0,a=rm.get(RK(T(r["Away Team"]),s,w)),h=rm.get(RK(T(r["Home Team"]),s,w));if(!a||!h||T(a.Classification).toLowerCase()!=="fbs"||T(h.Classification).toLowerCase()!=="fbs")continue;const mt=N(r["Market Total"]);if(mt==null)continue;const plays=(V(a,"Plays Per Game")+V(h,"Plays Per Game"))/2,league=V(r,"League HFA"),venue=V(r,"Venue HFA"),travel=V(r,"Travel Adjustment"),tz=V(r,"Time Zone Adjustment"),alt=V(r,"Altitude Adjustment"),rest=V(r,"Rest Adjustment"),hfa=V(r,"Home Field Advantage");games.push({date:D(r.Date),at:ac.a+ac.h,mt,f:{"Plays":plays,"HFA":hfa,"League HFA":league,"Venue HFA":venue,"Travel":travel,"Time Zone":tz,"Altitude":alt,"Rest":rest,"HFA minus League":hfa-league,"HFA minus Venue":hfa-venue,"Composite nonleague":venue+alt+rest-travel-tz}})}
 const tests=[wf(games,"Plays + full HFA",["Plays","HFA"]),wf(games,"Plays + league HFA",["Plays","League HFA"]),wf(games,"Plays + venue HFA",["Plays","Venue HFA"]),wf(games,"Plays + HFA minus league",["Plays","HFA minus League"]),wf(games,"Plays + HFA minus venue",["Plays","HFA minus Venue"]),wf(games,"Plays + nonleague composite",["Plays","Composite nonleague"]),wf(games,"Plays + rest",["Plays","Rest"]),wf(games,"Plays + travel",["Plays","Travel"]),wf(games,"Plays + timezone",["Plays","Time Zone"]),wf(games,"Plays + altitude",["Plays","Altitude"]),wf(games,"Plays + venue + rest + travel + tz + altitude",["Plays","Venue HFA","Rest","Travel","Time Zone","Altitude"])];return NextResponse.json({source:{games:games.length},tests})}
