import { NextResponse } from "next/server";
import { readSportWorksheet } from "../../../../lib/sportSheets";
export const dynamic="force-dynamic"; export const revalidate=0;
type R=Record<string,string>; type G={date:string;week:number;away:string;home:string,pm:number,pt:number,ms:number|null,mt:number|null,am:number,at:number,slate:R,ar:R|null,hr:R|null}; type F={name:string,get:(g:G)=>number|null};
const t=(v:unknown)=>String(v??"").trim();const n=(v:unknown):number|null=>{const x=Number(t(v));return Number.isFinite(x)?x:null};const k=(s:string)=>s.toUpperCase().replace(/[^A-Z0-9]/g,"");const dk=(s:string)=>t(s).slice(0,10);const mean=(a:number[])=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0;const rnd=(x:number,d=3)=>Number(x.toFixed(d));
function sKey(r:R){const id=t(r["Game ID"]);return id?`id:${id}`:`${dk(r.Date)}|${k(t(r["Away Team"]))}|${k(t(r["Home Team"]))}`};function schedKeys(r:R){const o:string[]=[];const id=t(r["Game ID"]);if(id)o.push(`id:${id}`);o.push(`${dk(r["Game Date"])}|${k(t(r["Away Team"]))}|${k(t(r["Home Team"]))}`);return o}function teamName(r:R){return t(r.Team)||t(r.School)}function pw(r:R){return n(r["Projection Week"])??n(r.Week)??0}
function solve(A:number[][],b:number[]){const m=A.map((r,i)=>[...r,b[i]]),N=m.length;for(let i=0;i<N;i++){let p=i;for(let j=i+1;j<N;j++)if(Math.abs(m[j][i])>Math.abs(m[p][i]))p=j;[m[i],m[p]]=[m[p],m[i]];if(Math.abs(m[i][i])<1e-9)return null;const z=m[i][i];for(let j=i;j<=N;j++)m[i][j]/=z;for(let q=0;q<N;q++)if(q!==i){const f=m[q][i];for(let j=i;j<=N;j++)m[q][j]-=f*m[i][j]}}return m.map(r=>r[N])}
function fit(rows:G[],features:F[],kind:"spread"|"total",lambda:number){const good=rows.filter(g=>(kind==="spread"?g.ms:g.mt)!=null&&features.every(f=>f.get(g)!=null));if(good.length<Math.max(15,features.length*3))return null;const means=features.map(f=>mean(good.map(g=>f.get(g)!))),sds=features.map((f,j)=>Math.sqrt(mean(good.map(g=>(f.get(g)!-means[j])**2)))||1);const p=features.length+1,A=Array.from({length:p},()=>Array(p).fill(0)),b=Array(p).fill(0);for(const g of good){const base=kind==="spread"?-Number(g.ms):Number(g.mt),y=(kind==="spread"?g.am:g.at)-base;const x=[1,...features.map((f,j)=>(f.get(g)!-means[j])/sds[j])];for(let i=0;i<p;i++){b[i]+=x[i]*y;for(let j=0;j<p;j++)A[i][j]+=x[i]*x[j]}}for(let i=1;i<p;i++)A[i][i]+=lambda;const beta=solve(A,b);return beta?{beta,means,sds}:null}
function predict(g:G,features:F[],model:any,kind:"spread"|"total"){const base=kind==="spread"?-Number(g.ms):Number(g.mt);let r=model.beta[0];features.forEach((f,j)=>r+=model.beta[j+1]*((f.get(g)!-model.means[j])/model.sds[j]));return base+r}
function evalRows(train:G[],test:G[],features:F[],kind:"spread"|"total",lambda:number){const m=fit(train,features,kind,lambda);const valid=test.filter(g=>(kind==="spread"?g.ms:g.mt)!=null&&features.every(f=>f.get(g)!=null));if(!m||!valid.length)return null;let ae=0,baseAe=0;const records:any={};for(const th of [0,1,2,3,4])records[th]={n:0,w:0,l:0,p:0};for(const g of valid){const base=kind==="spread"?-Number(g.ms):Number(g.mt),actual=kind==="spread"?g.am:g.at,pred=predict(g,features,m,kind);ae+=Math.abs(pred-actual);baseAe+=Math.abs(base-actual);const adj=pred-base;for(const th of [0,1,2,3,4]){if(Math.abs(adj)<th)continue;const signed=(adj>0?1:-1)*(actual-base);records[th].n++;if(Math.abs(signed)<1e-9)records[th].p++;else if(signed>0)records[th].w++;else records[th].l++;}}const rec=Object.entries(records).map(([th,x]:any)=>({threshold:Number(th),n:x.n,w:x.w,l:x.l,p:x.p,winRate:x.w+x.l?rnd(x.w/(x.w+x.l)):null}));return{n:valid.length,mae:rnd(ae/valid.length),marketMae:rnd(baseAe/valid.length),improvement:rnd((baseAe-ae)/valid.length),record:rec,coefficients:features.map((f,j)=>({feature:f.name,beta:rnd(m.beta[j+1])}))};}
function cv(rows:G[],features:F[],kind:"spread"|"total",lambda:number){const dates=[...new Set(rows.map(g=>g.date))].sort();let ae=0,be=0,N=0;for(let i=0;i<dates.length;i++){const tr=rows.filter(g=>g.date<dates[i]),te=rows.filter(g=>g.date===dates[i]);if(tr.length<25)continue;const e=evalRows(tr,te,features,kind,lambda);if(!e)continue;ae+=e.mae*e.n;be+=e.marketMae*e.n;N+=e.n}return N?{n:N,mae:rnd(ae/N),marketMae:rnd(be/N),improvement:rnd((be-ae)/N)}:null}
export async function GET(){const [slate,schedule,ratings]=await Promise.all([readSportWorksheet("NCAAF","daily_slate") as Promise<R[]>,readSportWorksheet("NCAAF","schedule") as Promise<R[]>,readSportWorksheet("NCAAF","team_ratings") as Promise<R[]>]);const actual=new Map<string,{a:number,h:number}>();for(const r of schedule){const a=n(r["Away Score"]),h=n(r["Home Score"]);if(a==null||h==null||(a===0&&h===0))continue;for(const q of schedKeys(r))actual.set(q,{a,h})}const bt=new Map<string,R[]>();for(const r of ratings){const q=k(teamName(r));if(!q)continue;if(!bt.has(q))bt.set(q,[]);bt.get(q)!.push(r)}for(const x of bt.values())x.sort((a,b)=>pw(a)-pw(b));const gr=(team:string,w:number)=>{const a=bt.get(k(team))||[];return a.filter(r=>pw(r)<=w).at(-1)||a.at(0)||null};const dd=new Map<string,R>();for(const r of slate)dd.set(sKey(r),r);const games:G[]=[];for(const r of dd.values()){const a=actual.get(sKey(r))||actual.get(`${dk(r.Date)}|${k(t(r["Away Team"]))}|${k(t(r["Home Team"]))}`);const pm=n(r["Projected Margin"]),pt=n(r["Projected Total"]),w=n(r.Week);if(!a||pm==null||pt==null||w==null)continue;const away=t(r["Away Team"]),home=t(r["Home Team"]);games.push({date:dk(r.Date),week:w,away,home,pm,pt,ms:n(r["Market Home Spread"]),mt:n(r["Market Total"]),am:a.h-a.a,at:a.h+a.a,slate:r,ar:gr(away,w),hr:gr(home,w)})}games.sort((a,b)=>a.date.localeCompare(b.date));const dates=[...new Set(games.map(g=>g.date))].sort(),holdDate=dates.at(-1)!;const dev=games.filter(g=>g.date<holdDate),hold=games.filter(g=>g.date===holdDate);
 const rd=(c:string):F=>({name:c+" diff",get:g=>{const a=g.ar? n(g.ar[c]):null,h=g.hr?n(g.hr[c]):null;return a==null||h==null?null:h-a}});const ra=(c:string):F=>({name:c+" avg",get:g=>{const a=g.ar?n(g.ar[c]):null,h=g.hr?n(g.hr[c]):null;return a==null||h==null?null:(h+a)/2}});const ss=(c:string):F=>({name:c,get:g=>n(g.slate[c])});
 const spreadCandidates=[rd("Elo Rating"),rd("Power Rating"),rd("Offense Rating"),rd("Defense Rating"),rd("Third Down Defense Edge"),rd("Plays Per Game"),rd("Points Allowed Per Drive"),rd("Pass EPA/PPA"),rd("Line Yards Defense Edge"),rd("Stuff Rate Edge"),rd("Field Position Offense"),ss("Home Field Advantage"),ss("Venue HFA"),ss("Rest Adjustment"),ss("Home Injury Adjustment"),ss("Away Injury Adjustment")];
 const totalCandidates=[ra("Line Yards Offense"),ra("Havoc Allowed"),ra("Talent Rating"),ra("Pass EPA/PPA"),ra("Explosiveness Defense Edge"),ra("Passing Downs Offense"),ra("Success Rate Offense"),ra("EPA/PPA Offense"),ra("Line Yards Defense Edge"),ra("Rush Defense Edge"),ra("Turnover Rate"),ra("Field Position Offense"),ra("Points Per Drive"),ss("Home Field Advantage"),ss("Wind"),ss("Rest Adjustment")];
 function select(kind:"spread"|"total",cands:F[]){const lambdas=[0.5,2,5,10,25];let bestLambda=5,bestBase=Infinity;for(const l of lambdas){const z=cv(dev,[],kind,l);if(z&&z.mae<bestBase){bestBase=z.mae;bestLambda=l}}let selected:F[]=[];const steps:any[]=[];let current=cv(dev,selected,kind,bestLambda);for(let step=0;step<6;step++){let best:any=null;for(const f of cands.filter(x=>!selected.includes(x))){const z=cv(dev,[...selected,f],kind,bestLambda);if(z&&(!best||z.mae<best.cv.mae))best={f,cv:z}}if(!best||!current||best.cv.mae>=current.mae-0.03)break;selected=[...selected,best.f];current=best.cv;steps.push({added:best.f.name,cv:best.cv})}return{lambda:bestLambda,baselineCv:cv(dev,[],kind,bestLambda),steps,selected:selected.map(f=>f.name),developmentCv:current,holdout:evalRows(dev,hold,selected,kind,bestLambda),univariate:cands.map(f=>({feature:f.name,cv:cv(dev,[f],kind,bestLambda),holdout:evalRows(dev,hold,[f],kind,bestLambda)})).sort((a,b)=>(a.cv?.mae??999)-(b.cv?.mae??999)).slice(0,12)};}
 return NextResponse.json({source:{games:games.length,development:dev.length,holdout:hold.length,holdoutDate:holdDate},spread:select("spread",spreadCandidates),total:select("total",totalCandidates)});}
