import {NextResponse} from "next/server";
import {readSportWorksheet} from "../../../../lib/sportSheets";
export const dynamic="force-dynamic";export const revalidate=0;
const t=v=>String(v??"").trim(),n=v=>{const x=Number(t(v));return Number.isFinite(x)?x:null},mean=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:null,median=a=>{const z=[...a].sort((x,y)=>x-y);if(!z.length)return null;const m=Math.floor(z.length/2);return z.length%2?z[m]:(z[m-1]+z[m])/2},rx=(s,re)=>{const m=t(s).match(re);return m?Number(m[1]):null},role=s=>rx(s,/live role overlay\s+([0-9.]+)x/i),slotAdj=s=>{const x=rx(s,/slot matchup[\s\S]*?applied\s+([+-]?[0-9.]+)%/i);return x==null?0:x/100},key=r=>`${t(r.Date)}|${t(r.Player)}`,prior=x=>x.position==="WR"?8.15:6.15,pct=x=>x==null?null:+(100*x).toFixed(1),cal=x=>x.baseTargets*((.2*x.baseEff)+(.8*prior(x)))*(1+3*x.slotAdj);
function met(a,f){if(!a.length)return{n:0,mae:null,medianAE:null,bias:null};const e=a.map(x=>Math.abs(x.actual-f(x)));return{n:a.length,mae:+mean(e).toFixed(3),medianAE:+median(e).toFixed(3),bias:+mean(a.map(x=>f(x)-x.actual)).toFixed(3)}}
function rec(a,f,min=16,side="ALL"){let w=0,l=0,p=0;for(const x of a){const y=f(x),g=y-x.line;if(100*Math.abs(g)/x.line<min)continue;if(side==="OVER"&&g<=0)continue;if(side==="UNDER"&&g>=0)continue;const ar=Math.sign(x.actual-x.line),pr=Math.sign(g);if(ar===0)p++;else if(ar===pr)w++;else l++}return{n:w+l+p,w,l,p,winPct:w+l?pct(w/(w+l)):null}}
function stat(a){return{candidate:met(a,cal),market:met(a,x=>x.line),e16:rec(a,cal,16),e20:rec(a,cal,20),e25:rec(a,cal,25),e30:rec(a,cal,30),over16:rec(a,cal,16,"OVER"),under16:rec(a,cal,16,"UNDER"),over25:rec(a,cal,25,"OVER"),under25:rec(a,cal,25,"UNDER")}}
function grouped(a,k){const o={};for(const v of [...new Set(a.map(k))].sort()){const z=a.filter(x=>k(x)===v);o[v||"(blank)"]={all:stat(z),WR1:stat(z.filter(x=>x.slot==="WR1")),WR2:stat(z.filter(x=>x.slot==="WR2")),dates:[...new Set(z.map(x=>x.date))].sort()}}return o}
export async function GET(){const[rows,proj]=await Promise.all([readSportWorksheet("NFL","prop_tracker"),readSportWorksheet("NFL","prop_projections")]),tm=new Map(),a=[];for(const r of proj){if(t(r.Market)!=="Targets")continue;const p=n(r.Projection),mi=n(r["Matchup Index"]);if(p!=null&&mi!=null&&mi>0)tm.set(key(r),{p,mi})}for(const r of rows){if(t(r.Market)!=="Receiving Yards"||t(r.Position)!=="WR"||!["WR1","WR2"].includes(t(r.Slot)))continue;const projection=n(r.Projection),line=n(r["Market Line"]),actual=n(r["Actual Result"]),mi=n(r["Matchup Index"]),ro=role(r.Confluence),ft=n(r["Projected Targets"]),fe=n(r.Efficiency),at=n(r["Actual Targets"]),tr=tm.get(key(r)),c=t(r.Confluence);if(projection==null||line==null||line<=0||actual==null||mi==null||mi<=0||ro==null||ro<=0||ft==null||fe==null||at==null||!tr||!c.includes("slot matchup"))continue;const brt=tr.p/tr.mi,bt=brt/ro,opp=brt>0?ft/brt:1,ef=opp>0?mi/opp:1,be=ef>0?fe/ef:fe;a.push({date:t(r.Date),version:t(r["Model Version"]),player:t(r.Player),slot:t(r.Slot),line,actual,projection,baseTargets:bt,baseEff:be,slotAdj:slotAdj(c)})}const pre=a.filter(x=>x.date<"2026-09-27"),v=a.filter(x=>x.version.includes("v4.18"));return NextResponse.json({formula:"WR1/WR2: baseTargets * (20% baseEff + 80% 8.15 YPT prior) * (1 + 3*slotAdj)",counts:{all:a.length,pre:pre.length,v418:v.length},preOverall:stat(pre),v418:stat(v),preByVersion:grouped(pre,x=>x.version),preByDate:grouped(pre,x=>x.date),allByVersion:grouped(a,x=>x.version)});}
