import { NextResponse } from "next/server";
import { readSportWorksheet } from "../../../../lib/sportSheets";
export const dynamic="force-dynamic"; export const revalidate=0;
type Row=Record<string,string>;
const text=(v:unknown)=>String(v??"").trim();
const num=(v:unknown)=>{const x=Number(text(v).replace(/%/g,""));return Number.isFinite(x)?x:null};
const wanted=(m:string)=>["Rushing Yards","Receiving Yards","Passing Yards"].includes(m);
function summarize(rows:any[]){const mean=(f:(r:any)=>number|null)=>{const a=rows.map(f).filter((x):x is number=>x!=null&&Number.isFinite(x));return a.length?+(a.reduce((s,x)=>s+x,0)/a.length).toFixed(3):null};return{n:rows.length,projectionMAE:mean(r=>r.projectionAbsError),marketLineMAE:mean(r=>r.lineAbsError),avgAbsModelGap:mean(r=>Math.abs(r.modelGap)),directionCorrectPct:rows.length?+(100*rows.filter(r=>r.directionCorrect).length/rows.length).toFixed(1):null,avgOpportunityAbsError:mean(r=>r.opportunityError==null?null:Math.abs(r.opportunityError)),avgEfficiencyAbsError:mean(r=>r.efficiencyError==null?null:Math.abs(r.efficiencyError))}}
function fit(rows:any[]){if(rows.length<2)return null;const xs=rows.map(r=>r.modelGap),ys=rows.map(r=>r.actualMinusLine);const mx=xs.reduce((a,b)=>a+b,0)/xs.length,my=ys.reduce((a,b)=>a+b,0)/ys.length;let sxx=0,sxy=0;for(let i=0;i<xs.length;i++){sxx+=(xs[i]-mx)**2;sxy+=(xs[i]-mx)*(ys[i]-my)}const slope=sxx?sxy/sxx:0,intercept=my-slope*mx;const zeroSlope=xs.reduce((s,x,i)=>s+x*ys[i],0)/(xs.reduce((s,x)=>s+x*x,0)||1);let best={alpha:0,mae:Infinity};for(let a=0;a<=1.5;a+=0.01){const mae=rows.reduce((s,r)=>s+Math.abs(r.actual-(r.line+a*r.modelGap)),0)/rows.length;if(mae<best.mae)best={alpha:+a.toFixed(2),mae:+mae.toFixed(3)}}return{intercept:+intercept.toFixed(3),slope:+slope.toFixed(3),zeroInterceptSlope:+zeroSlope.toFixed(3),bestShrinkToMarket:best}}
function gapBucket(x:number){const a=Math.abs(x);return a<5?"0-5":a<10?"5-10":a<15?"10-15":a<20?"15-20":a<30?"20-30":"30+"}
function group(rows:any[],f:(r:any)=>string){const out:Record<string,any>={};for(const k of [...new Set(rows.map(f))].sort()){const a=rows.filter(r=>f(r)===k);const wins=a.filter(r=>r.betWon).length;out[k]={...summarize(a),fit:fit(a),wins,losses:a.length-wins,winPct:a.length?+(100*wins/a.length).toFixed(1):null}}return out}
export async function GET(){const tracker=await readSportWorksheet("NFL","prop_tracker") as Row[];const rows=tracker.map(r=>{const market=text(r.Market),line=num(r["Market Line"]),projection=num(r.Projection),actual=num(r["Actual Result"]);if(!wanted(market)||line==null||projection==null||actual==null)return null;const gap=projection-line,actualMinusLine=actual-line,side=gap>=0?"Over":"Under";return{date:text(r.Date),player:text(r.Player),market,slot:text(r.Slot)||text(r.Position),modelVersion:text(r["Model Version"]),line,projection,actual,modelGap:+gap.toFixed(2),actualMinusLine:+actualMinusLine.toFixed(2),projectionAbsError:+Math.abs(actual-projection).toFixed(2),lineAbsError:+Math.abs(actual-line).toFixed(2),directionCorrect:Math.sign(gap)===Math.sign(actualMinusLine),betWon:side==="Over"?actual>line:actual<line,side,opportunityError:num(r["Opportunity Error"]),efficiencyError:num(r["Efficiency Error"]),projectedAttempts:num(r["Projected Player Attempts"]),actualAttempts:num(r["Actual Attempts"]),projectedTargets:num(r["Projected Targets"]),actualTargets:num(r["Actual Targets"]),bucket:gapBucket(gap)}}).filter(Boolean) as any[];const yard=rows.filter(r=>r.market!=="Passing Yards"),v418=rows.filter(r=>r.modelVersion.includes("v4.18")),v418Y=v418.filter(r=>r.market!=="Passing Yards");const compact=(a:any[])=>({summary:summarize(a),fit:fit(a),byMarket:group(a,r=>r.market),byGap:group(a,r=>r.bucket),bySlot:group(a,r=>r.slot||"blank")});return NextResponse.json({trackerRows:tracker.length,all:compact(rows),yardage:compact(yard),v418:compact(v418),v418Yardage:compact(v418Y),v418YardageRows:v418Y})}