import { NextResponse } from "next/server";
import { readSportWorksheet } from "../../../../lib/sportSheets";
export const dynamic="force-dynamic";export const revalidate=0;
const T=v=>String(v??"").trim(),N=v=>{const x=Number(T(v));return Number.isFinite(x)?x:null},K=s=>s.toUpperCase().replace(/[^A-Z0-9]/g,""),D=s=>T(s).slice(0,10),A=x=>x.length?x.reduce((a,b)=>a+b,0)/x.length:0,RD=(x,d=3)=>Number(x.toFixed(d));
const SK=r=>T(r["Game ID"])?`id:${T(r["Game ID"])}`:`${D(r.Date)}|${K(T(r["Away Team"]))}|${K(T(r["Home Team"]))}`;const SH=r=>{const z=[];if(T(r["Game ID"]))z.push(`id:${T(r["Game ID"])}`);z.push(`${D(r["Game Date"])}|${K(T(r["Away Team"]))}|${K(T(r["Home Team"]))}`);return z};const RK=(t,s,w)=>`${s}|${w}|${K(t)}`;
function solve(X,y,lam=0){const p=X[0]?.length??0;if(!p)return[];const M=Array.from({length:p},()=>Array(p).fill(0)),b=Array(p).fill(0);for(let i=0;i<X.length;i++)for(let j=0;j<p;j++){b[j]+=X[i][j]*y[i];for(let q=0;q<p;q++)M[j][q]+=X[i][j]*X[i][q]}for(let j=1;j<p;j++)M[j][j]+=lam;for(let i=0;i<p;i++){let z=i;for(let r=i+1;r<p;r++)if(Math.abs(M[r][i])>Math.abs(M[z][i]))z=r;[M[i],M[z]]=[M[z],M[i]];[b[i],b[z]]=[b[z],b[i]];const u=M[i][i];if(Math.abs(u)<1e-10)return[];for(let q=i;q<p;q++)M[i][q]/=u;b[i]/=u;for(let r=0;r<p;r++)if(r!==i){const f=M[r][i];for(let q=i;q<p;q++)M[r][q]-=f*M[i][q];b[r]-=f*b[i]}}return b}
const modelDefs={
 current:{fit:()=>null,pred:g=>g.pm},
 intercept:{fit:tr=>({b:[A(tr.map(g=>g.am-g.pm))]}),pred:(g,m)=>g.pm+m.b[0]},
 linear:{fit:tr=>({b:solve(tr.map(g=>[1,g.pm]),tr.map(g=>g.am),2)}),pred:(g,m)=>m.b[0]+m.b[1]*g.pm},
 slopeOnly:{fit:tr=>{const den=tr.reduce((s,g)=>s+g.pm*g.pm,0)||1;return{b:[tr.reduce((s,g)=>s+g.pm*g.am,0)/den]}},pred:(g,m)=>m.b[0]*g.pm},
 nonlinear:{fit:tr=>({b:solve(tr.map(g=>[1,g.pm,Math.sign(g.pm)*g.pm*g.pm]),tr.map(g=>g.am),10)}),pred:(g,m)=>m.b[0]+m.b[1]*g.pm+m.b[2]*Math.sign(g.pm)*g.pm*g.pm},
 share:{fit:tr=>({b:solve(tr.map(g=>[1,g.pm/Math.max(35,g.pt)]),tr.map(g=>g.am/Math.max(35,g.pt)),2)}),pred:(g,m)=>(m.b[0]+m.b[1]*(g.pm/Math.max(35,g.pt)))*g.pt},
 currentElo:{fit:tr=>({b:solve(tr.map(g=>[1,g.pm,g.elo]),tr.map(g=>g.am),10)}),pred:(g,m)=>m.b[0]+m.b[1]*g.pm+m.b[2]*g.elo},
 currentEloPre:{fit:tr=>({b:solve(tr.map(g=>[1,g.pm,g.elo,g.pre]),tr.map(g=>g.am),20)}),pred:(g,m)=>m.b[0]+m.b[1]*g.pm+m.b[2]*g.elo+m.b[3]*g.pre}
};
function evalM(tr,te,name){const d=modelDefs[name],m=d.fit(tr);let ae=0,cur=0,mkt=0,nm=0,bias=0;for(const g of te){const p=d.pred(g,m);ae+=Math.abs(p-g.am);bias+=p-g.am;cur+=Math.abs(g.pm-g.am);if(g.mm!=null){mkt+=Math.abs(g.mm-g.am);nm++}}return{n:te.length,mae:RD(ae/te.length),bias:RD(bias/te.length),currentMae:RD(cur/te.length),marketMae:nm?RD(mkt/nm):null,vsCurrent:RD((cur-ae)/te.length),params:m?.b?.map(x=>RD(x))??[]}}
function cv(rows,name){const ds=[...new Set(rows.map(g=>g.date))].sort();let n=0,ae=0,cur=0,mkt=0,nm=0;const folds=[];for(const d of ds){const tr=rows.filter(g=>g.date<d),te=rows.filter(g=>g.date===d);if(tr.length<25)continue;const e=evalM(tr,te,name);folds.push({date:d,...e});n+=e.n;ae+=e.mae*e.n;cur+=e.currentMae*e.n;if(e.marketMae!=null){mkt+=e.marketMae*e.n;nm+=e.n}}return{n,mae:RD(ae/n),currentMae:RD(cur/n),marketMae:nm?RD(mkt/nm):null,vsCurrent:RD((cur-ae)/n),positiveFolds:folds.filter(x=>x.vsCurrent>0).length,folds}}
export async function GET(){const[sl,sc,rr]=await Promise.all([readSportWorksheet("NCAAF","daily_slate"),readSportWorksheet("NCAAF","schedule"),readSportWorksheet("NCAAF","team_ratings")]);const am=new Map();for(const r of sc){const a=N(r["Away Score"]),h=N(r["Home Score"]);if(a==null||h==null||(a===0&&h===0))continue;for(const q of SH(r))am.set(q,{a,h})}const rm=new Map();for(const r of rr)rm.set(RK(T(r.Team),N(r.Season)??2026,N(r["Projection Week"])??0),r);const dd=new Map();for(const r of sl)dd.set(SK(r),r);const games=[];for(const s of dd.values()){const ac=am.get(SK(s))||am.get(`${D(s.Date)}|${K(T(s["Away Team"]))}|${K(T(s["Home Team"]))}`),season=N(s.Season)??2026,w=N(s.Week)??0,pm=N(s["Projected Margin"]),pt=N(s["Projected Total"]);if(!ac||!w||pm==null||pt==null)continue;const ar=rm.get(RK(T(s["Away Team"]),season,w)),hr=rm.get(RK(T(s["Home Team"]),season,w));if(!ar||!hr||T(ar.Classification).toLowerCase()!=="fbs"||T(hr.Classification).toLowerCase()!=="fbs")continue;games.push({date:D(s.Date),pm,pt,am:ac.h-ac.a,mm:N(s["Market Home Spread"])==null?null:-N(s["Market Home Spread"]),elo:(N(hr["Elo Rating"])??0)-(N(ar["Elo Rating"])??0),pre:(N(hr["Preseason Rating"])??0)-(N(ar["Preseason Rating"])??0)})}games.sort((a,b)=>a.date.localeCompare(b.date));const ds=[...new Set(games.map(g=>g.date))].sort(),holdDate=ds.at(-1),dev=games.filter(g=>g.date<holdDate),hold=games.filter(g=>g.date===holdDate);const results={};for(const name of Object.keys(modelDefs))results[name]={development:cv(dev,name),holdout:evalM(dev,hold,name)};const buckets=[[-99,-14],[-14,-7],[-7,0],[0,7],[7,14],[14,99]].map(([lo,hi])=>{const x=hold.filter(g=>g.pm>=lo&&g.pm<hi);return{range:`${lo} to ${hi}`,n:x.length,currentMae:x.length?RD(A(x.map(g=>Math.abs(g.pm-g.am)))):null,currentBias:x.length?RD(A(x.map(g=>g.pm-g.am))):null,marketMae:x.length?RD(A(x.filter(g=>g.mm!=null).map(g=>Math.abs(g.mm-g.am)))):null}});return NextResponse.json({source:{games:games.length,development:dev.length,holdout:hold.length,holdoutDate:holdDate},results,buckets})}
