import { NextResponse } from "next/server";
import { readSportWorksheet } from "../../../../lib/sportSheets";
export const dynamic="force-dynamic";export const revalidate=0;
type Row=Record<string,string>;type R={date:string;line:number;projection:number;actual:number;role:number;match:number};
const t=(v:unknown)=>String(v??"").trim(),n=(v:unknown)=>{const x=Number(t(v));return Number.isFinite(x)?x:null},mean=(a:number[])=>a.length?a.reduce((s,x)=>s+x,0)/a.length:null,rd=(x:number|null,d=2)=>x==null?null:+x.toFixed(d),key=(r:Row)=>`${t(r.Date)}|${t(r.Player)}|${t(r.Market)}`;
function role(c:unknown){const m=t(c).match(/live role(?:\/injury)? overlay\s+([0-9.]+)x/i);return m?Number(m[1]):1}
const current=(r:R)=>r.projection,noBoth=(r:R)=>r.projection/Math.max(.01,r.role*r.match),halfBoth=(r:R)=>r.projection/Math.max(.01,r.role*r.match)*(1+.5*(r.role-1))*(1+.5*(r.match-1));
const fns={current,lowOnly:(r:R)=>r.role<.9?noBoth(r):current(r),extremesNoBoth:(r:R)=>(r.role<.9||r.role>1.1)?noBoth(r):current(r),roleBands:(r:R)=>r.role<.9?noBoth(r):r.role>1.1?halfBoth(r):current(r),roleBandsTight:(r:R)=>r.role<.85?noBoth(r):r.role>1.2?halfBoth(r):current(r),noBoth,halfBoth,market:(r:R)=>r.line};
function result(r:R,p:number){if(r.actual===r.line)return"P";return p>=r.line?(r.actual>r.line?"W":"L"):(r.actual<r.line?"W":"L")}
function stat(a:R[],fn:(r:R)=>number){let w=0,l=0,p=0;const ae:number[]=[],res:number[]=[];for(const r of a){const y=Math.max(0,fn(r));ae.push(Math.abs(r.actual-y));res.push(r.actual-y);const z=result(r,y);if(z==="W")w++;else if(z==="L")l++;else p++}return{n:a.length,mae:rd(mean(ae)),bias:rd(mean(res)),record:`${w}-${l}-${p}`,winPct:w+l?rd(100*w/(w+l),1):null}}
function suite(a:R[]){return Object.fromEntries(Object.entries(fns).map(([k,f])=>[k,stat(a,f)]))}
export async function GET(){const[cal,proj]=await Promise.all([readSportWorksheet("NFL","prop_calibration") as Promise<Row[]>,readSportWorksheet("NFL","prop_projections") as Promise<Row[]>]);const pm=new Map<string,Row>();for(const p of proj)if(t(p.Market)==="Receiving Yards"&&t(p.Position)==="RB")pm.set(key(p),p);const seen=new Set<string>(),rows:R[]=[];for(const c of cal){if(t(c.Market)!=="Receiving Yards"||t(c.Position)!=="RB")continue;const line=n(c["Market Line"]),projection=n(c.Projection),actual=n(c["Actual Result"]);if(line==null||line<=0||projection==null||actual==null)continue;const d=`${key(c)}|${line}|${projection}`;if(seen.has(d))continue;seen.add(d);const p=pm.get(key(c))||{};rows.push({date:t(c.Date),line,projection,actual,role:role(p.Confluence),match:n(p["Matchup Index"])||1})}const pre=rows.filter(r=>r.date<"2026-09-27"),hold=rows.filter(r=>r.date==="2026-09-27"),dates=[...new Set(rows.map(r=>r.date))].sort();const byDate=Object.fromEntries(dates.map(d=>[d,suite(rows.filter(r=>r.date===d))]));return NextResponse.json({counts:{all:rows.length,pre:pre.length,holdout:hold.length},all:suite(rows),pre:suite(pre),holdout:suite(hold),byDate});}
