import { NextResponse } from "next/server";
import { readSportWorksheet } from "../../../../lib/sportSheets";
export const dynamic="force-dynamic";export const revalidate=0;
type Row=Record<string,string>;type R={date:string;player:string;projection:number;line:number;actual:number;attempts:number;actualAttempts:number;ypa:number;actualYpa:number;yardMi:number;attMi:number;effMi:number};
const t=(v:unknown)=>String(v??"").trim();const n=(v:unknown)=>{const x=Number(t(v));return Number.isFinite(x)?x:null};const mean=(a:number[])=>a.length?a.reduce((s,x)=>s+x,0)/a.length:null;const rnd=(x:number|null,d=3)=>x==null?null:Number(x.toFixed(d));const pk=(r:Row)=>`${t(r.Date)}|${t(r.Player)}`;const normLine=(x:number)=>{let v=x;while(v>600)v/=10;return v};
function bet(r:R,p:number){if(!(r.line>0))return"NA";if(r.actual===r.line)return"P";return p>=r.line?(r.actual>r.line?"W":"L"):(r.actual<r.line?"W":"L")}
function sum(a:R[],f:(r:R)=>number){let w=0,l=0,p=0;const ae=a.map(r=>{const q=f(r),z=bet(r,q);if(z==="W")w++;else if(z==="L")l++;else if(z==="P")p++;return Math.abs(r.actual-q)});return{n:a.length,mae:rnd(mean(ae)),bias:rnd(mean(a.map(r=>f(r)-r.actual))),record:`${w}-${l}-${p}`,winPct:w+l?rnd(100*w/(w+l),1):null}}
const cand=(r:R,ow:number,ew:number)=>r.projection/Math.pow(Math.max(.05,r.attMi),ow)/Math.pow(Math.max(.05,r.effMi),ew);
const weights=[0,.25,.5,.75,1];
function grid(a:R[]){const z:any[]=[];for(const ow of weights)for(const ew of weights)z.push({oppNeutral:ow,effNeutral:ew,...sum(a,r=>cand(r,ow,ew))});return z.sort((x,y)=>(x.mae??999)-(y.mae??999)||Math.abs(x.bias??999)-Math.abs(y.bias??999))}
function edge(a:R[],f:(r:R)=>number,min:number){let w=0,l=0,p=0;for(const r of a){const q=f(r);if(!(r.line>0)||100*Math.abs(q-r.line)/r.line<min)continue;const z=bet(r,q);if(z==="W")w++;else if(z==="L")l++;else if(z==="P")p++;}return{n:w+l+p,w,l,p,winPct:w+l?rnd(100*w/(w+l),1):null}}
export async function GET(){
 const rows0=await readSportWorksheet("NFL","prop_tracker") as Row[];const att=new Map<string,Row[]>();
 for(const x of rows0){if(t(x.Position)==="QB"&&t(x.Market)==="Passing Attempts"){const k=pk(x);if(!att.has(k))att.set(k,[]);att.get(k)!.push(x)}}
 const rows:R[]=[];const seen=new Set<string>();
 for(const x of rows0){if(t(x.Position)!=="QB"||t(x.Market)!=="Passing Yards")continue;const projection=n(x.Projection),actual=n(x["Actual Result"]),attempts=n(x["Projected Pass Attempts"]),actualAttempts=n(x["Actual Attempts"]),ypa=n(x.Efficiency),yardMi=n(x["Matchup Index"])??1;if(projection==null||actual==null||attempts==null||attempts<=0||actualAttempts==null||actualAttempts<=0||ypa==null||ypa<=0||yardMi<=0)continue;const candidates=att.get(pk(x))??[];let ar:Row|undefined;let best=1e9;for(const q of candidates){const pa=n(q["Projected Pass Attempts"])??n(q.Projection);if(pa==null)continue;const d=Math.abs(pa-attempts);if(d<best){best=d;ar=q}}const attMi=ar?(n(ar["Matchup Index"])??1):1;const effMi=yardMi/Math.max(.05,attMi);const line0=n(x["Market Line"])??0,line=line0>0?normLine(line0):0;const k=`${pk(x)}|${projection}|${actual}`;if(seen.has(k))continue;seen.add(k);rows.push({date:t(x.Date),player:t(x.Player),projection,line,actual,attempts,actualAttempts,ypa,actualYpa:actual/actualAttempts,yardMi,attMi,effMi})}
 rows.sort((a,b)=>a.date.localeCompare(b.date)||a.player.localeCompare(b.player));const pre=rows.filter(r=>r.date<"2026-09-27"),hold=rows.filter(r=>r.date==="2026-09-27");const g=grid(pre),best=g[0]??{oppNeutral:0,effNeutral:0};
 const full=(a:R[])=>a.filter(r=>r.actualAttempts>=.60*r.attempts);const byDate=[...new Set(rows.map(r=>r.date))].sort().map(date=>{const a=rows.filter(r=>r.date===date);return{date,current:sum(a,r=>r.projection),noOpp:sum(a,r=>cand(r,1,0)),noEff:sum(a,r=>cand(r,0,1)),noBoth:sum(a,r=>cand(r,1,1))}});
 return NextResponse.json({counts:{all:rows.length,pre:pre.length,holdout:hold.length,fullGameLike:full(rows).length},components:{attemptMatchupMean:rnd(mean(rows.map(r=>r.attMi)),4),effMatchupMean:rnd(mean(rows.map(r=>r.effMi)),4),yardMatchupMean:rnd(mean(rows.map(r=>r.yardMi)),4)},fixed:{current:{pre:sum(pre,r=>r.projection),holdout:sum(hold,r=>r.projection),all:sum(rows,r=>r.projection)},noOpp:{pre:sum(pre,r=>cand(r,1,0)),holdout:sum(hold,r=>cand(r,1,0)),all:sum(rows,r=>cand(r,1,0))},noEff:{pre:sum(pre,r=>cand(r,0,1)),holdout:sum(hold,r=>cand(r,0,1)),all:sum(rows,r=>cand(r,0,1))},noBoth:{pre:sum(pre,r=>cand(r,1,1)),holdout:sum(hold,r=>cand(r,1,1)),all:sum(rows,r=>cand(r,1,1))}},selectedOnTrain:{config:{oppNeutral:best.oppNeutral,effNeutral:best.effNeutral},pre:sum(pre,r=>cand(r,best.oppNeutral,best.effNeutral)),holdout:sum(hold,r=>cand(r,best.oppNeutral,best.effNeutral)),all:sum(rows,r=>cand(r,best.oppNeutral,best.effNeutral)),edges:{e16:edge(rows,r=>cand(r,best.oppNeutral,best.effNeutral),16),e25:edge(rows,r=>cand(r,best.oppNeutral,best.effNeutral),25)}},topGrid:g.slice(0,8),fullGameLike:{current:sum(full(rows),r=>r.projection),noOpp:sum(full(rows),r=>cand(r,1,0)),noEff:sum(full(rows),r=>cand(r,0,1)),noBoth:sum(full(rows),r=>cand(r,1,1))},byDate,holdoutRows:hold.map(r=>({player:r.player,line:r.line,current:rnd(r.projection,2),actual:r.actual,attempts:rnd(r.attempts,1),actualAttempts:r.actualAttempts,ypa:rnd(r.ypa,2),actualYpa:rnd(r.actualYpa,2),attMi:rnd(r.attMi,3),effMi:rnd(r.effMi,3),noOpp:rnd(cand(r,1,0),2),noEff:rnd(cand(r,0,1),2),noBoth:rnd(cand(r,1,1),2)}))});
}
