import { NextResponse } from "next/server";
import { readSportWorksheet } from "../../../../lib/sportSheets";
export const dynamic="force-dynamic";export const revalidate=0;
type R=Record<string,string>;type G={date:string;at:number;mt:number;f:Record<string,number>;minFbs:number;avgFbs:number};
const T=(v:unknown)=>String(v??"").trim(),N=(v:unknown)=>{const x=Number(T(v));return Number.isFinite(x)?x:null},K=(s:string)=>s.toUpperCase().replace(/[^A-Z0-9]/g,""),D=(s:string)=>T(s).slice(0,10),A=(a:number[])=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0,RD=(x:number,p=4)=>Number(x.toFixed(p)),V=(r:R,c:string,z=0)=>N(r[c])??z;
function SK(r:R){const id=T(r["Game ID"]);return id?`id:${id}`:`${D(r.Date)}|${K(T(r["Away Team"]))}|${K(T(r["Home Team"]))}`};function SH(r:R){const a=[] as string[],id=T(r["Game ID"]);if(id)a.push(`id:${id}`);a.push(`${D(r["Game Date"])}|${K(T(r["Away Team"]))}|${K(T(r["Home Team"]))}`);return a}function RK(x:string,s:number,w:number){return`${s}|${w}|${K(x)}`}
function solve(X:number[][],y:number[],lam=2){const p=X[0]?.length??0;if(!p)return[];const M=Array.from({length:p},()=>Array(p).fill(0)),b=Array(p).fill(0);for(let i=0;i<X.length;i++)for(let j=0;j<p;j++){b[j]+=X[i][j]*y[i];for(let q=0;q<p;q++)M[j][q]+=X[i][j]*X[i][q]}for(let j=0;j<p;j++)M[j][j]+=lam;for(let i=0;i<p;i++){let z=i;for(let r=i+1;r<p;r++)if(Math.abs(M[r][i])>Math.abs(M[z][i]))z=r;[M[i],M[z]]=[M[z],M[i]];[b[i],b[z]]=[b[z],b[i]];const u=M[i][i]||1e-9;for(let q=i;q<p;q++)M[i][q]/=u;b[i]/=u;for(let r=0;r<p;r++)if(r!==i){const q=M[r][i];for(let c=i;c<p;c++)M[r][c]-=q*M[i][c];b[r]-=q*b[i]}}return b}
function score(tr:G[],te:G[],fs:string[]){if(!te.length)return{n:0,mae:0,marketMae:0,improvement:0,w:0,l:0,p:0,winRate:0,betas:[]};const m:Record<string,number>={},s:Record<string,number>={};for(const f of fs){const x=tr.map(g=>g.f[f]);m[f]=A(x);s[f]=Math.sqrt(A(x.map(y=>(y-m[f])**2)))||1}const y=tr.map(g=>g.at-g.mt),ym=A(y),X=tr.map(g=>fs.map(f=>(g.f[f]-m[f])/s[f])),b=solve(X,y.map(x=>x-ym));let e=0,bm=0,w=0,l=0,p=0;for(const g of te){const r=ym+fs.reduce((q,f,j)=>q+b[j]*(g.f[f]-m[f])/s[f],0),ae=g.at-g.mt,sg=r>=0?ae:-ae;e+=Math.abs(g.mt+r-g.at);bm+=Math.abs(ae);if(Math.abs(sg)<1e-9)p++;else if(sg>0)w++;else l++;}return{n:te.length,mae:RD(e/te.length),marketMae:RD(bm/te.length),improvement:RD((bm-e)/te.length),w,l,p,winRate:RD(w+l?w/(w+l):0),betas:fs.map((f,j)=>({feature:f,beta:RD(b[j]??0)})),bias:RD(ym)}}
function wf(g:G[],fs:string[],minFbs=0){const rows=g.filter(x=>x.minFbs>=minFbs),folds=["2026-09-12","2026-09-19","2026-09-26"].map(dt=>({date:dt,...score(rows.filter(x=>x.date<dt),rows.filter(x=>x.date===dt),fs)}));const imp=folds.filter(x=>x.n).map(x=>x.improvement);return{features:fs,minFbs,folds,avgImprovement:RD(A(imp)),positiveFolds:imp.filter(x=>x>0).length,totalFolds:imp.length}}
export async function GET(){const[sl,sc,rr]=await Promise.all([readSportWorksheet("NCAAF","daily_slate") as Promise<R[]>,readSportWorksheet("NCAAF","schedule") as Promise<R[]>,readSportWorksheet("NCAAF","team_ratings") as Promise<R[]>]);const am=new Map<string,{a:number,h:number}>();for(const r of sc){const a=N(r["Away Score"]),h=N(r["Home Score"]);if(a==null||h==null||(a===0&&h===0))continue;for(const q of SH(r))am.set(q,{a,h})}const rm=new Map<string,R>();for(const r of rr)rm.set(RK(T(r.Team),N(r.Season)??2026,N(r["Projection Week"])??0),r);const dm=new Map<string,R>();for(const r of sl)dm.set(SK(r),r);const games:G[]=[];for(const r of dm.values()){const ac=am.get(SK(r))||am.get(`${D(r.Date)}|${K(T(r["Away Team"]))}|${K(T(r["Home Team"]))}`);if(!ac)continue;const s=N(r.Season)??2026,w=N(r.Week)??0,a=rm.get(RK(T(r["Away Team"]),s,w)),h=rm.get(RK(T(r["Home Team"]),s,w));if(!a||!h||T(a.Classification).toLowerCase()!=="fbs"||T(h.Classification).toLowerCase()!=="fbs")continue;const mt=N(r["Market Total"]);if(mt==null)continue;const ap=V(a,"Plays Per Game"),hp=V(h,"Plays Per Game"),apos=V(a,"Possessions Per Game",12),hpos=V(h,"Possessions Per Game",12),appg=V(a,"Points Per Game"),hppg=V(h,"Points Per Game"),aypp=V(a,"Yards Per Play",5.7),hypp=V(h,"Yards Per Play",5.7),afbs=V(a,"FBS Games"),hfbs=V(h,"FBS Games"),f:Record<string,number>={"HFA":V(r,"Home Field Advantage"),"Plays avg":(ap+hp)/2,"Possessions avg":(apos+hpos)/2,"Plays/Possession avg":((ap/Math.max(1,apos))+(hp/Math.max(1,hpos)))/2,"Points/Play avg":((appg/Math.max(1,ap))+(hppg/Math.max(1,hp)))/2,"Yards/Play avg":(aypp+hypp)/2,"Pace avg":(V(a,"Pace Seconds Per Play",27.5)+V(h,"Pace Seconds Per Play",27.5))/2,"PPD avg":(V(a,"Points Per Drive",2.3)+V(h,"Points Per Drive",2.3))/2,"Plays x Pace":((ap*V(a,"Pace Seconds Per Play",27.5))+(hp*V(h,"Pace Seconds Per Play",27.5)))/2,"Plays minus Poss*5.75":((ap-apos*5.75)+(hp-hpos*5.75))/2};games.push({date:D(r.Date),at:ac.a+ac.h,mt,f,minFbs:Math.min(afbs,hfbs),avgFbs:(afbs+hfbs)/2})}
 const forms=[{name:"HFA + raw plays",f:["Plays avg","HFA"]},{name:"HFA + plays/possession",f:["Plays/Possession avg","HFA"]},{name:"HFA + points/play",f:["Points/Play avg","HFA"]},{name:"HFA + yards/play",f:["Yards/Play avg","HFA"]},{name:"HFA + pace",f:["Pace avg","HFA"]},{name:"HFA + PPD",f:["PPD avg","HFA"]},{name:"HFA + possessions",f:["Possessions avg","HFA"]},{name:"HFA + plays x pace",f:["Plays x Pace","HFA"]},{name:"HFA + excess plays/drive",f:["Plays minus Poss*5.75","HFA"]}].map(x=>({name:x.name,...wf(games,x.f)}));const maturity=[0,1,2,3].map(m=>wf(games,["Plays avg","HFA"],m));return NextResponse.json({source:{games:games.length},forms,maturity})}
