import { NextResponse } from "next/server";
import { readSportWorksheet } from "../../../../lib/sportSheets";
export const dynamic="force-dynamic";export const revalidate=0;
type Row=Record<string,string>;type R={date:string;player:string;line:number;projection:number;actual:number;carries:number;actualCarries:number|null;role:number;slot:string};
const text=(v:unknown)=>String(v??"").trim();const num=(v:unknown)=>{const n=Number(text(v));return Number.isFinite(n)?n:null};const round=(v:number|null,d=2)=>v==null?null:Number(v.toFixed(d));const mean=(a:number[])=>a.length?a.reduce((s,x)=>s+x,0)/a.length:null;const key=(r:Row,l=false)=>`${text(r.Date)}|${text(r.Player)}|${text(r.Market)}${l?`|${text(r["Market Line"])}`:""}`;const role=(s:unknown)=>{const m=text(s).match(/live role(?:\/injury)? overlay\s+([0-9.]+)x/i);return m?Number(m[1]):1};
function result(r:R,p:number){if(r.line<=0)return"NA";if(r.actual===r.line)return"P";return p>=r.line?(r.actual>r.line?"W":"L"):(r.actual<r.line?"W":"L")}
type Mode="current"|"rb2Only"|"neutralRB1_rb2Half"|"neutralAll";
function vals(r:R,m:Mode){let factor=1;if(m==="rb2Only"&&r.slot==="RB2")factor=.5/(r.role>0?r.role:1);if(m==="neutralRB1_rb2Half")factor=(r.slot==="RB2"?.5:1)/(r.role>0?r.role:1);if(m==="neutralAll")factor=1/(r.role>0?r.role:1);return{carries:r.carries*factor,p:r.projection*factor}}
function summary(rows:R[],m:Mode){let w=0,l=0,push=0;const ae:number[]=[],ce:number[]=[];for(const r of rows){const v=vals(r,m);ae.push(Math.abs(r.actual-v.p));if(r.actualCarries!=null)ce.push(Math.abs(r.actualCarries-v.carries));const z=result(r,v.p);if(z==="W")w++;else if(z==="L")l++;else if(z==="P")push++;}return{n:rows.length,mae:round(mean(ae)),carryMae:round(mean(ce)),marketN:w+l+push,record:`${w}-${l}-${push}`,winPct:w+l?round(100*w/(w+l),1):null}}
function market(rows:R[]){const z=rows.filter(r=>r.line>0);return{n:z.length,mae:round(mean(z.map(r=>Math.abs(r.actual-r.line))))}}
function pack(rows:R[]){const modes:Mode[]=["current","rb2Only","neutralRB1_rb2Half","neutralAll"];return Object.fromEntries(modes.map(m=>[m,summary(rows,m)]))}
function byDate(rows:R[]){const dates=[...new Set(rows.map(r=>r.date))].sort();return Object.fromEntries(dates.map(d=>{const z=rows.filter(r=>r.date===d);return[d,{all:pack(z),RB1:pack(z.filter(r=>r.slot==="RB1")),RB2:pack(z.filter(r=>r.slot==="RB2")),market:{all:market(z),RB1:market(z.filter(r=>r.slot==="RB1")),RB2:market(z.filter(r=>r.slot==="RB2"))}}]}))}
export async function GET(){const[cal,proj]=await Promise.all([readSportWorksheet("NFL","prop_calibration") as Promise<Row[]>,readSportWorksheet("NFL","prop_projections") as Promise<Row[]>]);const exact=new Map<string,Row>(),fallback=new Map<string,Row>();for(const p of proj){if(text(p.Market)!=="Rushing Yards"||text(p.Position)!=="RB")continue;exact.set(key(p,true),p);fallback.set(key(p,false),p)}const rows:R[]=[];const seen=new Set<string>();for(const c of cal){if(text(c.Market)!=="Rushing Yards"||text(c.Position)!=="RB")continue;const projection=num(c.Projection),actual=num(c["Actual Result"]),carries=num(c["Projected Opportunity"]),line=num(c["Market Line"])??0;if(projection==null||actual==null||carries==null||carries<=0)continue;const p=exact.get(key(c,true))||fallback.get(key(c,false))||{};const d=`${key(c,true)}|${projection}`;if(seen.has(d))continue;seen.add(d);rows.push({date:text(c.Date),player:text(c.Player),line,projection,actual,carries,actualCarries:num(c["Actual Opportunity"]),role:role(p.Confluence),slot:text(p.Slot)})}rows.sort((a,b)=>a.date.localeCompare(b.date)||a.player.localeCompare(b.player));const pre=rows.filter(r=>r.date<"2026-09-27"),hold=rows.filter(r=>r.date==="2026-09-27");const slots=(z:R[])=>({all:pack(z),RB1:pack(z.filter(r=>r.slot==="RB1")),RB2:pack(z.filter(r=>r.slot==="RB2")),market:{all:market(z),RB1:market(z.filter(r=>r.slot==="RB1")),RB2:market(z.filter(r=>r.slot==="RB2"))}});return NextResponse.json({counts:{all:rows.length,pre:pre.length,holdout:hold.length},pre:slots(pre),holdout:slots(hold),all:slots(rows),byDate:byDate(rows)});}
