import { NextResponse } from "next/server";
export const dynamic="force-dynamic";export const revalidate=0;
const CSV="https://raw.githubusercontent.com/ezpzpicks/mlb-mobile-admin/main/research/results/cfb_2025_current_production_game_edges.csv";
const A=x=>x.length?x.reduce((a,b)=>a+b,0)/x.length:0,R=x=>Number(x.toFixed(3));
function parseCsv(text){const lines=text.trim().split(/\r?\n/),h=lines[0].split(',');return lines.slice(1).map(line=>{const c=line.split(',');const o={};h.forEach((k,i)=>o[k]=c[i]??'');return o})}
function mae(rows,pred){return A(rows.map(r=>Math.abs(pred(r)-r.actual)))}
function bias(rows,pred){return A(rows.map(r=>pred(r)-r.actual))}
function slopeFit(rows){const den=rows.reduce((s,r)=>s+r.pm*r.pm,0)||1;return rows.reduce((s,r)=>s+r.pm*r.actual,0)/den}
function metric(rows,pred){return{n:rows.length,mae:R(mae(rows,pred)),bias:R(bias(rows,pred))}}
export async function GET(){const res=await fetch(CSV,{cache:'no-store'});if(!res.ok)return NextResponse.json({error:`github ${res.status}`},{status:500});const raw=parseCsv(await res.text()).filter(r=>r.market==='Spread'&&String(r.fbs_fbs).toLowerCase()==='true');const map=new Map();for(const r of raw){const k=`${r.week}|${r.game_id}`;if(!map.has(k))map.set(k,{week:Number(r.week),game:r.game_id,pm:Number(r.projected_margin),actual:Number(r.actual_home)-Number(r.actual_away),market:Number(r.line)*-1})}const rows=[...map.values()].filter(r=>[r.pm,r.actual,r.market].every(Number.isFinite)).sort((a,b)=>a.week-b.week);const scales=[];for(let s=.8;s<=1.301;s+=.025)scales.push({scale:R(s),...metric(rows,r=>s*r.pm)});scales.sort((a,b)=>a.mae-b.mae);const buckets=[[-99,-14],[-14,-7],[-7,0],[0,7],[7,14],[14,99]].map(([lo,hi])=>{const x=rows.filter(r=>r.pm>=lo&&r.pm<hi);return{range:`${lo} to ${hi}`,...metric(x,r=>r.pm),marketMae:x.length?R(mae(x,r=>r.market)):null}});const weeks=[...new Set(rows.map(r=>r.week))].sort((a,b)=>a-b);const wf=[];for(const w of weeks){const tr=rows.filter(r=>r.week<w),te=rows.filter(r=>r.week===w);if(tr.length<60||!te.length)continue;const s=slopeFit(tr);wf.push({week:w,scale:R(s),baseline:metric(te,r=>r.pm),scaled:metric(te,r=>s*r.pm),improvement:R(mae(te,r=>r.pm)-mae(te,r=>s*r.pm)),marketMae:R(mae(te,r=>r.market))})}return NextResponse.json({source:{n:rows.length,weeks},baseline:{...metric(rows,r=>r.pm),marketMae:R(mae(rows,r=>r.market))},fixed111:metric(rows,r=>1.114*r.pm),bestScales:scales.slice(0,8),buckets,walkForward:wf,walkForwardSummary:{n:wf.reduce((s,x)=>s+x.baseline.n,0),baselineMae:R(A(wf.flatMap(x=>Array(x.baseline.n).fill(x.baseline.mae)))),scaledMae:R(A(wf.flatMap(x=>Array(x.scaled.n).fill(x.scaled.mae)))),positiveWeeks:wf.filter(x=>x.improvement>0).length,totalWeeks:wf.length}})}