import { NextResponse } from "next/server";
import { readSportWorksheet } from "../../../../lib/sportSheets";
export const dynamic="force-dynamic"; export const revalidate=0;
type Row=Record<string,string>; type R={date:string;player:string;line:number;projection:number;actual:number;targets:number;actualTargets:number|null;routes:number;tprr:number;routePart:number;role:number};
const text=(v:unknown)=>String(v??"").trim(); const num=(v:unknown)=>{const n=Number(text(v));return Number.isFinite(n)?n:null}; const round=(v:number|null,d=2)=>v==null?null:Number(v.toFixed(d)); const mean=(a:number[])=>a.length?a.reduce((s,x)=>s+x,0)/a.length:null; const key=(r:Row,l=false)=>`${text(r.Date)}|${text(r.Player)}|${text(r.Market)}${l?`|${text(r["Market Line"])}`:""}`; const role=(s:unknown)=>{const m=text(s).match(/live role(?:\/injury)? overlay\s+([0-9.]+)x/i);return m?Number(m[1]):1};
function res(r:R,p:number){if(r.actual===r.line)return"P";return p>=r.line?(r.actual>r.line?"W":"L"):(r.actual<r.line?"W":"L")}
function summarize(rows:R[],fn:(r:R)=>number){let w=0,l=0,p=0;const ae:number[]=[],te:number[]=[];for(const r of rows){const nt=Math.max(0,fn(r)),pr=r.targets>0?r.projection*(nt/r.targets):r.projection;ae.push(Math.abs(r.actual-pr));if(r.actualTargets!=null)te.push(Math.abs(r.actualTargets-nt));const z=res(r,pr);if(z==="W")w++;else if(z==="L")l++;else p++;}return{n:rows.length,mae:round(mean(ae)),targetMae:round(mean(te)),record:`${w}-${l}-${p}`,winPct:w+l?round(100*w/(w+l),1):null}}
type C={w:number;cap:number;mode:"all"|"up"|"down"|"upLowRole"|"upHighRoute";ratioCut:number;routePartCut:number};
function target(r:R,c:C){const native=r.routes*r.tprr;let delta=native-r.targets;if(c.mode==="up"&&delta<=0)return r.targets;if(c.mode==="down"&&delta>=0)return r.targets;if(c.mode==="upLowRole"&&!(delta>0&&r.role<1))return r.targets;if(c.mode==="upHighRoute"&&!(delta>0&&r.routePart>=c.routePartCut&&native/r.targets>=c.ratioCut))return r.targets;delta=Math.max(-c.cap,Math.min(c.cap,delta));return Math.max(0,r.targets+c.w*delta)}
function grid(train:R[]){const out:{c:C;s:ReturnType<typeof summarize>}[]=[];for(const w of [0.25,0.5,0.75,1])for(const cap of [0.5,1,1.5,2,3])for(const mode of ["all","up","down","upLowRole","upHighRoute"] as const)for(const ratioCut of [1.05,1.1,1.2,1.3])for(const routePartCut of [0.4,0.5,0.6]){const c={w,cap,mode,ratioCut,routePartCut};out.push({c,s:summarize(train,r=>target(r,c))});}out.sort((a,b)=>(a.s.mae??999)-(b.s.mae??999)||(a.s.targetMae??999)-(b.s.targetMae??999));return out}
export async function GET(){const [cal,proj]=await Promise.all([readSportWorksheet("NFL","prop_calibration") as Promise<Row[]>,readSportWorksheet("NFL","prop_projections") as Promise<Row[]>]);const exact=new Map<string,Row>(),fallback=new Map<string,Row>();for(const p of proj){if(text(p.Market)!=="Receiving Yards"||text(p.Position)!=="RB")continue;exact.set(key(p,true),p);fallback.set(key(p,false),p)}const rows:R[]=[];const seen=new Set<string>();for(const c of cal){if(text(c.Market)!=="Receiving Yards"||text(c.Position)!=="RB")continue;const line=num(c["Market Line"]),projection=num(c.Projection),actual=num(c["Actual Result"]),targets=num(c["Projected Opportunity"]);if(line==null||projection==null||actual==null||targets==null||targets<=0)continue;const p=exact.get(key(c,true))||fallback.get(key(c,false))||{};const routes=num(p["Projected Routes"]),tprr=num(p["Targets Per Route"]),routePart=num(p["Route Participation"]);if(routes==null||tprr==null||routePart==null)continue;const d=`${key(c,true)}|${projection}`;if(seen.has(d))continue;seen.add(d);rows.push({date:text(c.Date),player:text(c.Player),line,projection,actual,targets,actualTargets:num(c["Actual Opportunity"]),routes,tprr,routePart,role:role(p.Confluence)})}rows.sort((a,b)=>a.date.localeCompare(b.date)||a.player.localeCompare(b.player));const pre=rows.filter(r=>r.date<"2026-09-27"),hold=rows.filter(r=>r.date==="2026-09-27");const ranked=grid(pre),best=ranked[0];const fixed:C={w:0.5,cap:1.5,mode:"upHighRoute",ratioCut:1.1,routePartCut:0.5};const gibbs=rows.filter(r=>/jahmyr\s+gibbs/i.test(r.player));return NextResponse.json({counts:{all:rows.length,pre:pre.length,holdout:hold.length},current:{all:summarize(rows,r=>r.targets),pre:summarize(pre,r=>r.targets),holdout:summarize(hold,r=>r.targets)},selected:{rule:best.c,train:best.s,holdout:summarize(hold,r=>target(r,best.c)),all:summarize(rows,r=>target(r,best.c))},fixed:{rule:fixed,train:summarize(pre,r=>target(r,fixed)),holdout:summarize(hold,r=>target(r,fixed)),all:summarize(rows,r=>target(r,fixed))},top10:ranked.slice(0,10),gibbs:gibbs.map(r=>{const native=r.routes*r.tprr;const bt=target(r,best.c),ft=target(r,fixed);return{date:r.date,line:r.line,currentProjection:r.projection,actual:r.actual,currentTargets:r.targets,actualTargets:r.actualTargets,routeTargets:round(native),routePart:r.routePart,tprr:r.tprr,role:r.role,selectedTargets:round(bt),selectedProjection:round(r.projection*(bt/r.targets)),fixedTargets:round(ft),fixedProjection:round(r.projection*(ft/r.targets))}})});}
