import { NextResponse } from "next/server";
export const dynamic="force-dynamic";export const revalidate=0;export const maxDuration=60;
const ESPN="https://site.api.espn.com/apis/site/v2/sports/football/college-football/scoreboard";
const A=x=>x.length?x.reduce((a,b)=>a+b,0)/x.length:0,R=x=>Number(x.toFixed(4)),C=(x,a,b)=>Math.max(a,Math.min(b,x));
const norm=s=>String(s??"").normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/&/g,"and").replace(/\s+/g," ").trim();
function key(s){let k=norm(s).toUpperCase().replace(/[^A-Z0-9]/g,"");const a={TEXASAM:"TEXASANDM",TEXASAANDM:"TEXASANDM",TEXASANDM:"TEXASANDM",NCSTATE:"NORTHCAROLINASTATE",CONNECTICUT:"UCONN",FLORIDAINTERNATIONAL:"FIU",FLORIDAATLANTIC:"FAU",MASSACHUSETTS:"UMASS",SOUTHERNMISSISSIPPI:"SOUTHERNMISS",LOUISIANAMONROE:"ULMONROE",MIDDLETENNESSEESTATE:"MIDDLETENNESSEE"};return a[k]??k}
async function fetchSeason(y){const out=new Map();await Promise.all([2,3].map(async st=>{const u=new URL(ESPN);u.searchParams.set("dates",String(y));u.searchParams.set("limit","1000");u.searchParams.set("groups","80");u.searchParams.set("seasontype",String(st));const r=await fetch(u,{cache:"force-cache"});if(!r.ok)throw new Error(`ESPN ${y}/${st} ${r.status}`);const j=await r.json();for(const e of j.events??[])out.set(String(e.id),e)}));if(out.size<100){const jobs=[];for(const st of [2,3])for(let w=0;w<=(st===2?18:8);w++)jobs.push((async()=>{const u=new URL(ESPN);u.searchParams.set("dates",String(y));u.searchParams.set("limit","500");u.searchParams.set("groups","80");u.searchParams.set("seasontype",String(st));u.searchParams.set("week",String(w));try{const r=await fetch(u,{cache:"force-cache"});if(r.ok){const j=await r.json();for(const e of j.events??[])out.set(String(e.id),e)}}catch{}})());await Promise.all(jobs)}const rows=[];for(const e of out.values()){const c=e.competitions?.[0];if(!c)continue;const h=c.competitors?.find(x=>x.homeAway==="home"),a=c.competitors?.find(x=>x.homeAway==="away"),done=c.status?.type?.completed??e.status?.type?.completed;if(!h||!a||!done)continue;const hs=Number(h.score),as=Number(a.score),w=Number(e.week?.number??0),home=norm(h.team?.shortDisplayName||h.team?.location||h.team?.name||h.team?.displayName),away=norm(a.team?.shortDisplayName||a.team?.location||a.team?.name||a.team?.displayName);if(home&&away&&Number.isFinite(hs)&&Number.isFinite(as)&&w>0)rows.push({season:y,week:w,id:String(e.id),home,away,hs,as,neutral:Boolean(c.neutralSite)})}return rows}
function summaries(games,tw=null){const done=tw==null?games:games.filter(g=>g.week<tw),teams=[...new Set(done.flatMap(g=>[g.home,g.away]))],by=new Map(teams.map(t=>[t,[]]));for(const g of done){by.get(g.home)?.push(g);by.get(g.away)?.push(g)}let power=new Map(teams.map(t=>[t,0]));for(let it=0;it<30;it++){const nx=new Map();for(const t of teams){const vals=[];for(const g of by.get(t)??[]){let m=g.hs-g.as;if(!g.neutral)m-=2;m=C(m,-45,45);const home=t===g.home,opp=home?g.away:g.home;vals.push((home?m:-m)+(power.get(opp)??0))}nx.set(t,vals.length?A(vals):0)}const cen=A([...nx.values()]);power=new Map([...nx].map(([t,v])=>[t,C(v-cen,-45,45)]))}const out=new Map();for(const t of teams){let sc=0,al=0,n=0;for(const g of by.get(t)??[]){const h=t===g.home;sc+=h?g.hs:g.as;al+=h?g.as:g.hs;n++}out.set(t,{power:power.get(t)??0,ppg:n?sc/n:28,papg:n?al/n:28,games:n})}return out}
const def={power:0,ppg:28,papg:28,games:0},get=(m,t)=>m.get(t)??def,blend=(p,c)=>{const w=c.games?c.games/(c.games+4):0;return{power:(1-w)*p.power+w*c.power,ppg:(1-w)*p.ppg+w*c.ppg,papg:(1-w)*p.papg+w*c.papg,games:c.games}};
const CO={po:.26670808584236927,pa:.22597582571150315,pg:.3024181814544948,cs:.38741952777838656,ca:.2716376410485099,cp:.3569282298069327,h:4.804668259201711};
function baseRow(g,prior,current){const hp=get(prior,g.home),ap=get(prior,g.away),hc=get(current,g.home),ac=get(current,g.away),hb=blend(hp,hc),ab=blend(ap,ac),team=(op,pp,ob,pb,h)=>CO.po*op.ppg+CO.pa*pp.papg+CO.pg*(op.power-pp.power)+CO.cs*(ob.ppg-op.ppg)+CO.ca*(pb.papg-pp.papg)+CO.cp*((ob.power-pb.power)-(op.power-pp.power))+CO.h*h;return{base:team(hp,ap,hb,ab,g.neutral?0:1)-team(ap,hp,ab,hb,0),priorPowerDiff:hp.power-ap.power}}
const clean=s=>s.replace(/<script[\s\S]*?<\/script>/gi,"").replace(/<style[\s\S]*?<\/style>/gi,"").replace(/<[^>]+>/g," ").replace(/&nbsp;/g," ").replace(/&amp;/g,"&").replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/\s+/g," ").trim();
async function fetchWN(y,type){const prefix=y===2020?`https://www.warrennolan.com/football/${y}`:`https://www.warrennolan.com/fbs/${y}`,u=`${prefix}/${type}`,r=await fetch(u,{headers:{"user-agent":"Mozilla/5.0"},cache:"force-cache"});if(!r.ok)throw new Error(`WN ${y}/${type} ${r.status}`);const t=await r.text(),out=new Map();for(const m of t.matchAll(/<tr\b[\s\S]*?<\/tr>/gi)){const row=m[0],href=[...row.matchAll(/href=["']([^"']+)["']/gi)].map(x=>x[1]).find(h=>h.includes(`/${y}/schedule/`));if(!href)continue;const mm=href.match(/\/schedule\/([^"'?/#]+)/i);if(!mm)continue;const slug=decodeURIComponent(mm[1]).replace(/-/g," "),txt=clean(row),nums=[...txt.matchAll(/\b(1\d{3}(?:\.\d+)?)\b/g)].map(x=>Number(x[1]));if(nums.length)out.set(key(slug),nums[0])}return out}
function metrics(rows,p=0,e=0,s=0){const pred=r=>r.base+p*r.priorPowerDiff+e*(r.eloDiff/100)+s*(r.sosDiff/100),errs=rows.map(r=>pred(r)-r.actual),ps=rows.map(pred),ys=rows.map(r=>r.actual),mx=A(ps),my=A(ys),den=Math.sqrt(ps.reduce((z,v)=>z+(v-mx)**2,0)*ys.reduce((z,v)=>z+(v-my)**2,0)),corr=den?ps.reduce((z,v,i)=>z+(v-mx)*(ys[i]-my),0)/den:0;return{n:rows.length,mae:R(A(errs.map(Math.abs))),rmse:R(Math.sqrt(A(errs.map(x=>x*x)))),bias:R(A(errs)),corr:R(corr)}}
export async function GET(){const years=[2020,2021,2022,2023,2024,2025],[seasons,elos,soss]=await Promise.all([Promise.all(years.map(fetchSeason)),Promise.all(years.map(y=>fetchWN(y,"elo"))),Promise.all(years.map(y=>fetchWN(y,"sos-elo")))]),by=new Map(seasons.map((g,i)=>[years[i],g])),full=new Map([...by].map(([y,g])=>[y,summaries(g)])),wn=new Map(years.map((y,i)=>[y,{elo:elos[i],sos:soss[i]}])),wc=new Map(),rows=[];for(const y of [2021,2022,2023,2024,2025])for(const g of by.get(y)??[]){const wk=`${y}|${g.week}`;if(!wc.has(wk))wc.set(wk,summaries(by.get(y)??[],g.week));const w=wn.get(y-1),he=w?.elo.get(key(g.home)),ae=w?.elo.get(key(g.away)),hs=w?.sos.get(key(g.home)),as=w?.sos.get(key(g.away));if(![he,ae,hs,as].every(Number.isFinite))continue;const b=baseRow(g,full.get(y-1),wc.get(wk));rows.push({season:y,actual:g.hs-g.as,base:b.base,priorPowerDiff:b.priorPowerDiff,eloDiff:he-ae,sosDiff:hs-as})}const tr=rows.filter(r=>r.season<=2023),va=rows.filter(r=>r.season===2024),ho=rows.filter(r=>r.season===2025),base={train:metrics(tr),validation:metrics(va),holdout:metrics(ho)},c=[];for(let pi=-6;pi<=6;pi++)for(let ei=-12;ei<=12;ei++)for(let si=-16;si<=20;si++){const p=pi*.05,e=ei*.25,s=si*.25,tm=metrics(tr,p,e,s),vm=metrics(va,p,e,s);if(tm.mae<base.train.mae&&vm.mae<base.validation.mae)c.push({powerAdjustment:p,eloWeight:e,sosWeight:s,train:tm,validation:vm})}c.sort((a,b)=>a.validation.mae-b.validation.mae);const top=c.slice(0,25).map(x=>({...x,holdout:metrics(ho,x.powerAdjustment,x.eloWeight,x.sosWeight)}));return NextResponse.json({protocol:{formula:"production margin + powerAdjustment*internal prior power gap + eloWeight*(prior WN ELO gap/100) + sosWeight*(prior WN ELO-SOS gap/100)",selection:"weights must improve 2021-23 training and 2024 validation; 2025 revealed only afterward",sportsbookPredictors:false},coverage:{all:rows.length,train:tr.length,validation:va.length,holdout:ho.length},baseline:base,topValidation:top,bestSelected:top[0]??null})}
