import { NextResponse } from "next/server";
import { parquetReadObjects } from "hyparquet";
import { compressors } from "hyparquet-compressors";
export const dynamic="force-dynamic";export const revalidate=0;export const maxDuration=60;
const YEARS=[2020,2021,2022,2023,2024,2025];
const FIELDS=["EPA_per_play","EPA_passing_per_play","EPA_rushing_per_play","EPA_explosive_rate","EPA_explosive_passing_rate","EPA_explosive_rushing_rate","yards_per_play","yards_per_pass","yards_per_rush","line_yards_per_carry","rushing_power_success_rate","rushing_stuff_rate","first_downs_created_rate","passing_first_downs_created_rate","rushing_first_downs_created_rate","EPA_special_teams"];
const A=x=>x.length?x.reduce((a,b)=>a+b,0)/x.length:0,R=x=>Number(x.toFixed(4)),C=(x,a,b)=>Math.max(a,Math.min(b,x));
const norm=s=>String(s??"").normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/&/g,"and").replace(/[^a-zA-Z0-9]/g,"").toUpperCase();
const num=(v,d=NaN)=>{const x=Number(v);return Number.isFinite(x)?x:d};
async function pq(url){const r=await fetch(url,{cache:"force-cache"});if(!r.ok)throw new Error(`${r.status} ${url}`);return parquetReadObjects({file:await r.arrayBuffer(),compressors})}
async function loadYear(y){const base="https://raw.githubusercontent.com/sportsdataverse/cfbfastR-cfb-data/main/cfb";const [s,a]=await Promise.all([pq(`${base}/cfb_schedules/parquet/cfb_schedules_${y}.parquet`),pq(`${base}/adv_team/parquet/adv_team_${y}.parquet`)]);return{year:y,sched:s,adv:a}}
function scheduleGames(rows,y){const out=[];for(const r of rows){const week=num(r.week,0),hs=num(r.home_points,num(r.home_score)),as=num(r.away_points,num(r.away_score));if(week<=0||!Number.isFinite(hs)||!Number.isFinite(as))continue;const home=String(r.home_team??""),away=String(r.away_team??"");if(!home||!away)continue;out.push({season:y,week,id:String(r.game_id??r.id??""),home,away,hs,as,neutral:Boolean(r.neutral_site),homeDiv:String(r.home_division??""),awayDiv:String(r.away_division??"")})}return out}
function summaries(games,through=null){const use=through==null?games:games.filter(g=>g.week<through),teams=[...new Set(use.flatMap(g=>[g.home,g.away]))],by=new Map(teams.map(t=>[t,[]]));for(const g of use){by.get(g.home)?.push(g);by.get(g.away)?.push(g)}let power=new Map(teams.map(t=>[t,0]));for(let it=0;it<30;it++){const nx=new Map();for(const t of teams){const vals=[];for(const g of by.get(t)??[]){let m=g.hs-g.as;if(!g.neutral)m-=2;m=C(m,-45,45);const h=t===g.home,o=h?g.away:g.home;vals.push((h?m:-m)+(power.get(o)??0))}nx.set(t,vals.length?A(vals):0)}const cen=A([...nx.values()]);power=new Map([...nx].map(([t,v])=>[t,C(v-cen,-45,45)]))}const out=new Map();for(const t of teams){let sc=0,al=0,n=0;for(const g of by.get(t)??[]){const h=t===g.home;sc+=h?g.hs:g.as;al+=h?g.as:g.hs;n++}out.set(t,{power:power.get(t)??0,ppg:n?sc/n:28,papg:n?al/n:28,games:n})}return out}
const DEF={power:0,ppg:28,papg:28,games:0},get=(m,t)=>m.get(t)??DEF,blend=(p,c)=>{const w=c.games?c.games/(c.games+4):0;return{power:(1-w)*p.power+w*c.power,ppg:(1-w)*p.ppg+w*c.ppg,papg:(1-w)*p.papg+w*c.papg,games:c.games}};
const CO={prior_own_ppg:.26670808584236927,prior_opp_papg:.22597582571150315,prior_power_gap:.3024181814544948,current_own_scoring_delta:.38741952777838656,current_opp_allowed_delta:.2716376410485099,current_power_delta:.3569282298069327,home_indicator:4.804668259201711};
function prodMargin(g,prior,current){const hp=get(prior,g.home),ap=get(prior,g.away),hc=get(current,g.home),ac=get(current,g.away),hb=blend(hp,hc),ab=blend(ap,ac);const team=(op,pp,ob,pb,h)=>CO.prior_own_ppg*op.ppg+CO.prior_opp_papg*pp.papg+CO.prior_power_gap*(op.power-pp.power)+CO.current_own_scoring_delta*(ob.ppg-op.ppg)+CO.current_opp_allowed_delta*(pb.papg-pp.papg)+CO.current_power_delta*((ob.power-pb.power)-(op.power-pp.power))+CO.home_indicator*h;return team(hp,ap,hb,ab,g.neutral?0:1)-team(ap,hp,ab,hb,0)}
function matchRow(team,rows){const k=norm(team);let best=null,score=-1;for(const r of rows){const q=norm(r.pos_team);let s=0;if(q===k)s=10000;else if(q.startsWith(k)||k.startsWith(q))s=Math.min(q.length,k.length);if(s>score){score=s;best=r}}return score>=Math.min(6,k.length)?best:null}
function gameFeatureRecords(games,advRows){const byId=new Map();for(const r of advRows){const id=String(r.game_id??"");if(!byId.has(id))byId.set(id,[]);byId.get(id).push(r)}const out=[];for(const g of games){const rs=byId.get(g.id)??[];if(rs.length<2)continue;const h=matchRow(g.home,rs),a=matchRow(g.away,rs);if(!h||!a||h===a)continue;out.push({g,h,a})}return out}
function agg(records,through=null){const use=through==null?records:records.filter(x=>x.g.week<through),acc=new Map();function row(t){if(!acc.has(t))acc.set(t,{n:0,off:Object.fromEntries(FIELDS.map(f=>[f,0])),def:Object.fromEntries(FIELDS.map(f=>[f,0]))});return acc.get(t)}for(const x of use){for(const [tm,own,opp] of [[x.g.home,x.h,x.a],[x.g.away,x.a,x.h]]){const z=row(tm);z.n++;for(const f of FIELDS){z.off[f]+=num(own[f],0);z.def[f]+=num(opp[f],0)}}}const out=new Map();for(const [tm,z] of acc){const o={},d={};for(const f of FIELDS){o[f]=z.n?z.off[f]/z.n:0;d[f]=z.n?z.def[f]/z.n:0}out.set(tm,{n:z.n,off:o,def:d})}return out}
function advBlend(pr,cu,f,side){const p=pr?.[side]?.[f],c=cu?.[side]?.[f],n=cu?.n??0,w=n?n/(n+4):0;if(Number.isFinite(p)&&Number.isFinite(c))return(1-w)*p+w*c;if(Number.isFinite(p))return p;if(Number.isFinite(c))return c;return 0}
function feature(g,prior,current,f){const hp=prior.get(g.home),ap=prior.get(g.away),hc=current.get(g.home),ac=current.get(g.away);const ho=advBlend(hp,hc,f,"off"),ao=advBlend(ap,ac,f,"off"),hd=advBlend(hp,hc,f,"def"),ad=advBlend(ap,ac,f,"def");if(f==="EPA_special_teams")return ho-ao;return(ho-ad)-(ao-hd)}
function metrics(rows,pred){const e=rows.map((x,i)=>pred[i]-x.actual),p=pred,a=rows.map(x=>x.actual),mp=A(p),ma=A(a),den=Math.sqrt(p.reduce((s,v)=>s+(v-mp)**2,0)*a.reduce((s,v)=>s+(v-ma)**2,0)),corr=den?p.reduce((s,v,i)=>s+(v-mp)*(a[i]-ma),0)/den:0;return{n:rows.length,mae:R(A(e.map(Math.abs))),rmse:R(Math.sqrt(A(e.map(x=>x*x)))),bias:R(A(e)),corr:R(corr)}}
function singleFit(train,f,alpha){const rms=Math.sqrt(A(train.map(x=>x.x[f]**2)))||1,z=train.map(x=>x.x[f]/rms),y=train.map(x=>x.actual-x.base),b=z.reduce((s,v,i)=>s+v*y[i],0)/(z.reduce((s,v)=>s+v*v,0)+alpha);return{rms,b}}
function singlePred(rows,f,m){return rows.map(x=>x.base+m.b*x.x[f]/m.rms)}
function solve(M,b){const n=b.length,A0=M.map((r,i)=>[...r,b[i]]);for(let i=0;i<n;i++){let p=i;for(let j=i+1;j<n;j++)if(Math.abs(A0[j][i])>Math.abs(A0[p][i]))p=j;[A0[i],A0[p]]=[A0[p],A0[i]];const d=A0[i][i];if(Math.abs(d)<1e-10)return Array(n).fill(0);for(let j=i;j<=n;j++)A0[i][j]/=d;for(let k=0;k<n;k++)if(k!==i){const f=A0[k][i];for(let j=i;j<=n;j++)A0[k][j]-=f*A0[i][j]}}return A0.map(r=>r[n])}
function multiFit(train,fs,alpha){const rms=fs.map(f=>Math.sqrt(A(train.map(x=>x.x[f]**2)))||1),M=Array.from({length:fs.length},()=>Array(fs.length).fill(0)),b=Array(fs.length).fill(0);for(const x of train){const z=fs.map((f,j)=>x.x[f]/rms[j]),y=x.actual-x.base;for(let j=0;j<fs.length;j++){b[j]+=z[j]*y;for(let k=0;k<fs.length;k++)M[j][k]+=z[j]*z[k]}}for(let j=0;j<fs.length;j++)M[j][j]+=alpha;return{rms,b:solve(M,b)}}
function multiPred(rows,fs,m){return rows.map(x=>x.base+fs.reduce((s,f,j)=>s+m.b[j]*(x.x[f]/m.rms[j]),0))}
function combos(xs,max=3){const out=[];function rec(st,cur){if(cur.length){out.push([...cur]);if(cur.length===max)return}for(let i=st;i<xs.length;i++){cur.push(xs[i]);rec(i+1,cur);cur.pop()}}rec(0,[]);return out}
export async function GET(){try{const data=await Promise.all(YEARS.map(loadYear)),sched=new Map(),advGames=new Map(),advFull=new Map();for(const d of data){const gs=scheduleGames(d.sched,d.year),gr=gameFeatureRecords(gs,d.adv);sched.set(d.year,gs);advGames.set(d.year,gr);advFull.set(d.year,agg(gr))}const fullScore=new Map([...sched].map(([y,g])=>[y,summaries(g)])),weekScore=new Map(),weekAdv=new Map(),rows=[];for(const y of [2021,2022,2023,2024,2025]){for(const rec of advGames.get(y)??[]){const g=rec.g,ks=`${y}|${g.week}`;if(!weekScore.has(ks))weekScore.set(ks,summaries(sched.get(y)??[],g.week));if(!weekAdv.has(ks))weekAdv.set(ks,agg(advGames.get(y)??[],g.week));const priorS=fullScore.get(y-1),curS=weekScore.get(ks),priorA=advFull.get(y-1),curA=weekAdv.get(ks);if(!priorS||!priorA)continue;const x={};for(const f of FIELDS)x[f]=feature(g,priorA,curA,f);rows.push({season:y,week:g.week,id:g.id,actual:g.hs-g.as,base:prodMargin(g,priorS,curS),x})}}const train=rows.filter(x=>x.season<=2023),val=rows.filter(x=>x.season===2024),hold=rows.filter(x=>x.season===2025),base={train:metrics(train,train.map(x=>x.base)),validation:metrics(val,val.map(x=>x.base)),holdout:metrics(hold,hold.map(x=>x.base))},alphas=[1,5,20,80],singles=[];for(const f of FIELDS){for(const a of alphas){const m=singleFit(train,f,a);singles.push({feature:f,alpha:a,coefficientStd:R(m.b),train:metrics(train,singlePred(train,f,m)),validation:metrics(val,singlePred(val,f,m)),holdout:metrics(hold,singlePred(hold,f,m))})}}singles.sort((a,b)=>a.validation.mae-b.validation.mae);const byFeature=[];for(const f of FIELDS){const best=singles.filter(x=>x.feature===f).sort((a,b)=>a.validation.mae-b.validation.mae)[0];byFeature.push(best)}byFeature.sort((a,b)=>a.validation.mae-b.validation.mae);const pool=byFeature.filter(x=>x.validation.mae<base.validation.mae).slice(0,8).map(x=>x.feature),multi=[];for(const fs of combos(pool,3))for(const a of alphas){const m=multiFit(train,fs,a);multi.push({features:fs,alpha:a,coefficientsStd:fs.map((f,j)=>({feature:f,coef:R(m.b[j])})),train:metrics(train,multiPred(train,fs,m)),validation:metrics(val,multiPred(val,fs,m)),holdout:metrics(hold,multiPred(hold,fs,m))})}multi.sort((a,b)=>a.validation.mae-b.validation.mae);return NextResponse.json({protocol:{train:"2021-2023",validation:2024,untouchedHoldout:2025,marketPredictors:false,advancedFeatures:"pregame only; previous season + current games before matchup",residualFit:"through-origin ridge on current production margin"},coverage:{rows:rows.length,train:train.length,validation:val.length,holdout:hold.length},baseline:base,bestSingleByFeature:byFeature,topCombinations:multi.slice(0,20)});}catch(e){return NextResponse.json({error:String(e?.message??e),stack:String(e?.stack??"")})}}
