import { NextResponse } from "next/server";
import { readSportWorksheet } from "../../../../lib/sportSheets";
export const dynamic="force-dynamic";export const revalidate=0;
type R=Record<string,string>;type G={date:string,week:number,away:string,home:string,pm:number,pt:number,ms:number|null,mt:number|null,am:number,at:number,slate:R,ar:R,hr:R};type F={name:string,get:(g:G)=>number|null};
const t=(v:unknown)=>String(v??"").trim();const n=(v:unknown):number|null=>{const x=Number(t(v));return Number.isFinite(x)?x:null};const k=(s:string)=>s.toUpperCase().replace(/[^A-Z0-9]/g,"");const dk=(s:string)=>t(s).slice(0,10);const mean=(a:number[])=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0;const rnd=(x:number,d=3)=>Number(x.toFixed(d));
function sKey(r:R){const id=t(r["Game ID"]);return id?`id:${id}`:`${dk(r.Date)}|${k(t(r["Away Team"]))}|${k(t(r["Home Team"]))}`};function schedKeys(r:R){const o:string[]=[];const id=t(r["Game ID"]);if(id)o.push(`id:${id}`);o.push(`${dk(r["Game Date"])}|${k(t(r["Away Team"]))}|${k(t(r["Home Team"]))}`);return o}function pw(r:R){return n(r["Projection Week"])??n(r.Week)??0}
function solve(A:number[][],b:number[]){const m=A.map((r,i)=>[...r,b[i]]),N=m.length;for(let i=0;i<N;i++){let p=i;for(let j=i+1;j<N;j++)if(Math.abs(m[j][i])>Math.abs(m[p][i]))p=j;[m[i],m[p]]=[m[p],m[i]];if(Math.abs(m[i][i])<1e-9)return null;const z=m[i][i];for(let j=i;j<=N;j++)m[i][j]/=z;for(let q=0;q<N;q++)if(q!==i){const f=m[q][i];for(let j=i;j<=N;j++)m[q][j]-=f*m[i][j]}}return m.map(r=>r[N])}
function fit(rows:G[],fs:F[],kind:"spread"|"total",lambda:number){const good=rows.filter(g=>fs.every(f=>f.get(g)!=null));if(good.length<Math.max(20,fs.length*4))return null;const mu=fs.map(f=>mean(good.map(g=>f.get(g)!))),sd=fs.map((f,j)=>Math.sqrt(mean(good.map(g=>(f.get(g)!-mu[j])**2)))||1);const p=fs.length+1,A=Array.from({length:p},()=>Array(p).fill(0)),b=Array(p).fill(0);for(const g of good){const y=kind==="spread"?g.am:g.at,x=[1,...fs.map((f,j)=>(f.get(g)!-mu[j])/sd[j])];for(let i=0;i<p;i++){b[i]+=x[i]*y;for(let j=0;j<p;j++)A[i][j]+=x[i]*x[j]}}for(let i=1;i<p;i++)A[i][i]+=lambda;const beta=solve(A,b);return beta?{beta,mu,sd}:null}
function pred(g:G,fs:F[],m:any){let y=m.beta[0];fs.forEach((f,j)=>y+=m.beta[j+1]*((f.get(g)!-m.mu[j])/m.sd[j]));return y}
function evaluate(train:G[],test:G[],fs:F[],kind:"spread"|"total",lambda:number){const m=fit(train,fs,kind,lambda),valid=test.filter(g=>fs.every(f=>f.get(g)!=null));if(!m||!valid.length)return null;let ae=0,cm=0,mm=0;for(const g of valid){const y=kind==="spread"?g.am:g.at,p=pred(g,fs,m),cur=kind==="spread"?g.pm:g.pt,mkt=kind==="spread"?(g.ms==null?null:-g.ms):g.mt;ae+=Math.abs(p-y);cm+=Math.abs(cur-y);if(mkt!=null)mm+=Math.abs(mkt-y)}return{n:valid.length,mae:rnd(ae/valid.length),currentModelMae:rnd(cm/valid.length),marketMae:rnd(mm/valid.filter(g=>(kind==="spread"?g.ms:g.mt)!=null).length),coefficients:fs.map((f,j)=>({feature:f.name,beta:rnd(m.beta[j+1])}))}}
function cv(rows:G[],fs:F[],kind:"spread"|"total",lambda:number){const dates=[...new Set(rows.map(g=>g.date))].sort();let ae=0,cm=0,mm=0,N=0,M=0;for(const d of dates){const tr=rows.filter(g=>g.date<d),te=rows.filter(g=>g.date===d);if(tr.length<25)continue;const m=fit(tr,fs,kind,lambda);if(!m)continue;for(const g of te.filter(g=>fs.every(f=>f.get(g)!=null))){const y=kind==="spread"?g.am:g.at,p=pred(g,fs,m),cur=kind==="spread"?g.pm:g.pt,mkt=kind==="spread"?(g.ms==null?null:-g.ms):g.mt;ae+=Math.abs(p-y);cm+=Math.abs(cur-y);N++;if(mkt!=null){mm+=Math.abs(mkt-y);M++}}}return N?{n:N,mae:rnd(ae/N),currentModelMae:rnd(cm/N),marketMae:rnd(mm/M)}:null}
export async function GET(){const [slate,schedule,ratings]=await Promise.all([readSportWorksheet("NCAAF","daily_slate") as Promise<R[]>,readSportWorksheet("NCAAF","schedule") as Promise<R[]>,readSportWorksheet("NCAAF","team_ratings") as Promise<R[]>]);const actual=new Map<string,{a:number,h:number}>();for(const r of schedule){const a=n(r["Away Score"]),h=n(r["Home Score"]);if(a==null||h==null||(a===0&&h===0))continue;for(const q of schedKeys(r))actual.set(q,{a,h})}const bt=new Map<string,R[]>();for(const r of ratings){const q=k(t(r.Team));if(!q)continue;if(!bt.has(q))bt.set(q,[]);bt.get(q)!.push(r)}for(const x of bt.values())x.sort((a,b)=>pw(a)-pw(b));const gr=(team:string,w:number)=>{const a=bt.get(k(team))||[];return a.filter(r=>pw(r)<=w).at(-1)||a.at(0)||null};const dd=new Map<string,R>();for(const r of slate)dd.set(sKey(r),r);const games:G[]=[];for(const r of dd.values()){const a=actual.get(sKey(r))||actual.get(`${dk(r.Date)}|${k(t(r["Away Team"]))}|${k(t(r["Home Team"]))}`),w=n(r.Week),pm=n(r["Projected Margin"]),pt=n(r["Projected Total"]);if(!a||w==null||pm==null||pt==null)continue;const away=t(r["Away Team"]),home=t(r["Home Team"]),ar=gr(away,w),hr=gr(home,w);if(!ar||!hr)continue;games.push({date:dk(r.Date),week:w,away,home,pm,pt,ms:n(r["Market Home Spread"]),mt:n(r["Market Total"]),am:a.h-a.a,at:a.h+a.a,slate:r,ar,hr})}games.sort((a,b)=>a.date.localeCompare(b.date));const dates=[...new Set(games.map(g=>g.date))].sort(),hd=dates.at(-1)!,dev=games.filter(g=>g.date<hd),hold=games.filter(g=>g.date===hd);const rd=(c:string):F=>({name:c+" diff",get:g=>{const a=n(g.ar[c]),h=n(g.hr[c]);return a==null||h==null?null:h-a}}),ra=(c:string):F=>({name:c+" avg",get:g=>{const a=n(g.ar[c]),h=n(g.hr[c]);return a==null||h==null?null:(h+a)/2}}),ss=(c:string):F=>({name:c,get:g=>n(g.slate[c])});
 const spread=[rd("Elo Rating"),rd("Power Rating"),rd("Preseason Rating"),rd("Offense Rating"),rd("Defense Rating"),rd("Points Per Game"),rd("Points Allowed Per Game"),rd("Points Per Drive"),rd("Points Allowed Per Drive"),rd("Pass EPA/PPA"),rd("Rush EPA/PPA"),rd("Success Rate Offense"),rd("Third Down Rate"),rd("Third Down Defense Edge"),rd("Line Yards Offense"),rd("Line Yards Defense Edge"),rd("Field Position Offense"),rd("Special Teams Rating"),ss("Home Field Advantage"),ss("Venue HFA"),ss("Rest Adjustment"),ss("Away Injury Adjustment"),ss("Home Injury Adjustment")];
 const total=[ra("Line Yards Offense"),ra("Havoc Allowed"),ra("Talent Rating"),ra("Pass EPA/PPA"),ra("Explosiveness Defense Edge"),ra("Passing Downs Offense"),ra("Success Rate Offense"),ra("EPA/PPA Offense"),ra("Line Yards Defense Edge"),ra("Rush Defense Edge"),ra("Turnover Rate"),ra("Field Position Offense"),ra("Points Per Drive"),ra("Points Allowed Per Drive"),ra("Points Per Game"),ra("Points Allowed Per Game"),ra("Yards Per Play"),ra("Yards Per Play Allowed"),ra("Plays Per Game"),ra("Possessions Per Game"),ss("Expected Possessions"),ss("Home Field Advantage"),ss("Wind"),ss("Precipitation Probability"),ss("Weather Adjustment")];
 function select(kind:"spread"|"total",cands:F[]){let best:any=null;for(const l of [.5,2,5,10,25]){const b=cv(dev,[],kind,l);if(b&&(!best||b.mae<best.cv.mae))best={l,cv:b}}let chosen:F[]=[],cur=best.cv,steps:any[]=[];for(let s=0;s<8;s++){let next:any=null;for(const f of cands.filter(x=>!chosen.includes(x))){const z=cv(dev,[...chosen,f],kind,best.l);if(z&&(!next||z.mae<next.cv.mae))next={f,cv:z}}if(!next||next.cv.mae>=cur.mae-0.08)break;chosen=[...chosen,next.f];cur=next.cv;steps.push({added:next.f.name,cv:next.cv})}return{lambda:best.l,baselineCv:best.cv,steps,selected:chosen.map(x=>x.name),developmentCv:cur,holdout:evaluate(dev,hold,chosen,kind,best.l),univariate:cands.map(f=>({feature:f.name,cv:cv(dev,[f],kind,best.l),holdout:evaluate(dev,hold,[f],kind,best.l)})).sort((a,b)=>(a.cv?.mae??999)-(b.cv?.mae??999)).slice(0,15)}}
 return NextResponse.json({source:{games:games.length,development:dev.length,holdout:hold.length,holdoutDate:hd},spread:select("spread",spread),total:select("total",total)});}
