import { NextResponse } from "next/server";
import { readSportWorksheet } from "../../../../lib/sportSheets";
export const dynamic="force-dynamic";export const revalidate=0;
type R=Record<string,string>;type G={date:string;at:number;mt:number;mm:number;conference:boolean;f:Record<string,number>};type P=G&{res:number;pred:number;err:number;baseErr:number};
const T=(v:unknown)=>String(v??"").trim(),N=(v:unknown)=>{const x=Number(T(v));return Number.isFinite(x)?x:null},K=(s:string)=>s.toUpperCase().replace(/[^A-Z0-9]/g,""),D=(s:string)=>T(s).slice(0,10),A=(a:number[])=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0,RD=(x:number,p=4)=>Number(x.toFixed(p)),V=(r:R,c:string,z=0)=>N(r[c])??z,B=(v:unknown)=>["true","1","yes","y"].includes(T(v).toLowerCase());
function SK(r:R){const id=T(r["Game ID"]);return id?`id:${id}`:`${D(r.Date)}|${K(T(r["Away Team"]))}|${K(T(r["Home Team"]))}`};function SH(r:R){const a=[] as string[],id=T(r["Game ID"]);if(id)a.push(`id:${id}`);a.push(`${D(r["Game Date"])}|${K(T(r["Away Team"]))}|${K(T(r["Home Team"]))}`);return a}function RK(x:string,s:number,w:number){return`${s}|${w}|${K(x)}`}
function solve(X:number[][],y:number[],lam=2){const p=X[0]?.length??0;if(!p)return[];const M=Array.from({length:p},()=>Array(p).fill(0)),b=Array(p).fill(0);for(let i=0;i<X.length;i++)for(let j=0;j<p;j++){b[j]+=X[i][j]*y[i];for(let q=0;q<p;q++)M[j][q]+=X[i][j]*X[i][q]}for(let j=0;j<p;j++)M[j][j]+=lam;for(let i=0;i<p;i++){let z=i;for(let r=i+1;r<p;r++)if(Math.abs(M[r][i])>Math.abs(M[z][i]))z=r;[M[i],M[z]]=[M[z],M[i]];[b[i],b[z]]=[b[z],b[i]];const u=M[i][i]||1e-9;for(let q=i;q<p;q++)M[i][q]/=u;b[i]/=u;for(let r=0;r<p;r++)if(r!==i){const q=M[r][i];for(let c=i;c<p;c++)M[r][c]-=q*M[i][c];b[r]-=q*b[i]}}return b}
function predict(tr:G[],te:G[]){const fs=["Plays Per Game avg","Home Field Advantage"],m:Record<string,number>={},s:Record<string,number>={};for(const f of fs){const x=tr.map(g=>g.f[f]);m[f]=A(x);s[f]=Math.sqrt(A(x.map(y=>(y-m[f])**2)))||1}const y=tr.map(g=>g.at-g.mt),ym=A(y),X=tr.map(g=>fs.map(f=>(g.f[f]-m[f])/s[f])),b=solve(X,y.map(x=>x-ym));return te.map(g=>{const res=ym+fs.reduce((q,f,j)=>q+b[j]*(g.f[f]-m[f])/s[f],0),pred=g.mt+res;return{...g,res,pred,err:Math.abs(pred-g.at),baseErr:Math.abs(g.mt-g.at)}})}
function stats(rows:P[]){let w=0,l=0,p=0;for(const g of rows){const ae=g.at-g.mt,sg=g.res>=0?ae:-ae;if(Math.abs(sg)<1e-9)p++;else if(sg>0)w++;else l++;}return{n:rows.length,mae:RD(A(rows.map(x=>x.err))),marketMae:RD(A(rows.map(x=>x.baseErr))),improvement:RD(A(rows.map(x=>x.baseErr))-A(rows.map(x=>x.err))),w,l,p,winRate:RD(w+l?w/(w+l):0),avgResidual:RD(A(rows.map(x=>x.res))),avgAbsResidual:RD(A(rows.map(x=>Math.abs(x.res))))}}
function group(rows:P[],defs:{name:string;fn:(g:P)=>boolean}[]){return defs.map(d=>({segment:d.name,...stats(rows.filter(d.fn))}))}
export async function GET(){const[sl,sc,rr]=await Promise.all([readSportWorksheet("NCAAF","daily_slate") as Promise<R[]>,readSportWorksheet("NCAAF","schedule") as Promise<R[]>,readSportWorksheet("NCAAF","team_ratings") as Promise<R[]>]);const am=new Map<string,{a:number,h:number}>();for(const r of sc){const a=N(r["Away Score"]),h=N(r["Home Score"]);if(a==null||h==null||(a===0&&h===0))continue;for(const q of SH(r))am.set(q,{a,h})}const rm=new Map<string,R>();for(const r of rr)rm.set(RK(T(r.Team),N(r.Season)??2026,N(r["Projection Week"])??0),r);const dm=new Map<string,R>();for(const r of sl)dm.set(SK(r),r);const games:G[]=[];for(const r of dm.values()){const ac=am.get(SK(r))||am.get(`${D(r.Date)}|${K(T(r["Away Team"]))}|${K(T(r["Home Team"]))}`);if(!ac)continue;const s=N(r.Season)??2026,w=N(r.Week)??0,a=rm.get(RK(T(r["Away Team"]),s,w)),h=rm.get(RK(T(r["Home Team"]),s,w));if(!a||!h||T(a.Classification).toLowerCase()!=="fbs"||T(h.Classification).toLowerCase()!=="fbs")continue;const mt=N(r["Market Total"]),hs=N(r["Market Home Spread"]);if(mt==null||hs==null)continue;games.push({date:D(r.Date),at:ac.a+ac.h,mt,mm:-hs,conference:B(r["Conference Game"]),f:{"Plays Per Game avg":(V(a,"Plays Per Game")+V(h,"Plays Per Game"))/2,"Home Field Advantage":V(r,"Home Field Advantage"),"Possessions Per Game avg":(V(a,"Possessions Per Game")+V(h,"Possessions Per Game"))/2,"Wind":V(r,"Wind"),"Weather Adjustment":V(r,"Weather Adjustment")}})}
 const dates=["2026-09-12","2026-09-19","2026-09-26"],oos:P[]=[];const byDate:any[]=[];for(const dt of dates){const rows=predict(games.filter(g=>g.date<dt),games.filter(g=>g.date===dt));oos.push(...rows);byDate.push({date:dt,...stats(rows)})}
 const mt=group(oos,[{name:"<=48",fn:g=>g.mt<=48},{name:"48.5-55",fn:g=>g.mt>48&&g.mt<=55},{name:">55",fn:g=>g.mt>55}]);const spread=group(oos,[{name:"close <=3.5",fn:g=>Math.abs(g.mm)<=3.5},{name:"medium 4-10",fn:g=>Math.abs(g.mm)>3.5&&Math.abs(g.mm)<=10},{name:"large >10",fn:g=>Math.abs(g.mm)>10}]);const hfa=group(oos,[{name:"HFA <2.75",fn:g=>g.f["Home Field Advantage"]<2.75},{name:"HFA 2.75-3.25",fn:g=>g.f["Home Field Advantage"]>=2.75&&g.f["Home Field Advantage"]<=3.25},{name:"HFA >3.25",fn:g=>g.f["Home Field Advantage"]>3.25}]);const edge=group(oos,[{name:"<1",fn:g=>Math.abs(g.res)<1},{name:"1-2",fn:g=>Math.abs(g.res)>=1&&Math.abs(g.res)<2},{name:"2-3",fn:g=>Math.abs(g.res)>=2&&Math.abs(g.res)<3},{name:"3-4",fn:g=>Math.abs(g.res)>=3&&Math.abs(g.res)<4},{name:"4+",fn:g=>Math.abs(g.res)>=4}]);const dir=group(oos,[{name:"Over",fn:g=>g.res>0},{name:"Under",fn:g=>g.res<0}]);const conf=group(oos,[{name:"Conference",fn:g=>g.conference},{name:"Nonconference",fn:g=>!g.conference}]);const fav=group(oos,[{name:"Home favorite",fn:g=>g.mm>0},{name:"Home dog",fn:g=>g.mm<0},{name:"Pickem",fn:g=>g.mm===0}]);
 const overs=oos.filter(g=>g.res>0),unders=oos.filter(g=>g.res<0);return NextResponse.json({source:{games:games.length,oos:oos.length,dates},overall:stats(oos),byDate,segments:{direction:dir,edge,marketTotal:mt,spreadMagnitude:spread,homeField:hfa,conference:conf,homeFavorite: fav},overSubsegments:{edge:group(overs,[{name:"<2",fn:g=>Math.abs(g.res)<2},{name:"2-4",fn:g=>Math.abs(g.res)>=2&&Math.abs(g.res)<4},{name:"4+",fn:g=>Math.abs(g.res)>=4}]),marketTotal:group(overs,[{name:"<=48",fn:g=>g.mt<=48},{name:"48.5-55",fn:g=>g.mt>48&&g.mt<=55},{name:">55",fn:g=>g.mt>55}]),spreadMagnitude:group(overs,[{name:"<=3.5",fn:g=>Math.abs(g.mm)<=3.5},{name:"4-10",fn:g=>Math.abs(g.mm)>3.5&&Math.abs(g.mm)<=10},{name:">10",fn:g=>Math.abs(g.mm)>10}])},underSubsegments:{edge:group(unders,[{name:"<2",fn:g=>Math.abs(g.res)<2},{name:"2-4",fn:g=>Math.abs(g.res)>=2&&Math.abs(g.res)<4},{name:"4+",fn:g=>Math.abs(g.res)>=4}]),marketTotal:group(unders,[{name:"<=48",fn:g=>g.mt<=48},{name:"48.5-55",fn:g=>g.mt>48&&g.mt<=55},{name:">55",fn:g=>g.mt>55}])}})}
