import { NextResponse } from "next/server";
import { readSportWorksheet } from "../../../../lib/sportSheets";
export const dynamic="force-dynamic"; export const revalidate=0;
type Row=Record<string,string>; type R={date:string;player:string;line:number;projection:number;actual:number;carries:number;actualCarries:number|null;eff:number;actualEff:number|null;role:number;matchup:number;slot:string};
const PRIOR=4.25; const text=(v:unknown)=>String(v??"").trim(); const num=(v:unknown)=>{const n=Number(text(v));return Number.isFinite(n)?n:null}; const round=(v:number|null,d=2)=>v==null?null:Number(v.toFixed(d)); const mean=(a:number[])=>a.length?a.reduce((s,x)=>s+x,0)/a.length:null; const key=(r:Row,l=false)=>`${text(r.Date)}|${text(r.Player)}|${text(r.Market)}${l?`|${text(r["Market Line"])}`:""}`;
const role=(s:unknown)=>{const m=text(s).match(/live role(?:\/injury)? overlay\s+([0-9.]+)x/i);return m?Number(m[1]):1};
function result(r:R,p:number){if(r.line<=0)return"NA";if(r.actual===r.line)return"P";return p>=r.line?(r.actual>r.line?"W":"L"):(r.actual<r.line?"W":"L")}
type G={lo:number;hi:number;effPrior:number;matchupStrength:number};
function vals(r:R,g:G){const ro=r.role>0?r.role:1,mi=r.matchup>0?r.matchup:1;const baseCarries=r.carries/ro;const guardedRole=Math.max(g.lo,Math.min(g.hi,ro));const carries=Math.max(0,baseCarries*guardedRole);const eff=Math.max(0,(1-g.effPrior)*r.eff+g.effPrior*PRIOR);const matchFactor=(1+g.matchupStrength*(mi-1))/mi;const p=r.projection*(carries/r.carries)*(eff/r.eff)*matchFactor;return{carries,eff,p,guardedRole}}
function summary(rows:R[],g:G){let w=0,l=0,push=0;const ae:number[]=[],ce:number[]=[],ee:number[]=[];for(const r of rows){const v=vals(r,g);ae.push(Math.abs(r.actual-v.p));if(r.actualCarries!=null)ce.push(Math.abs(r.actualCarries-v.carries));if(r.actualEff!=null)ee.push(Math.abs(r.actualEff-v.eff));const z=result(r,v.p);if(z==="W")w++;else if(z==="L")l++;else if(z==="P")push++;}return{n:rows.length,mae:round(mean(ae)),carryMae:round(mean(ce)),effMae:round(mean(ee)),marketN:w+l+push,record:`${w}-${l}-${push}`,winPct:w+l?round(100*w/(w+l),1):null}}
function market(rows:R[]){const z=rows.filter(r=>r.line>0);return{n:z.length,mae:round(mean(z.map(r=>Math.abs(r.actual-r.line))))}}
function grid(train:R[]){const out:{g:G;s:ReturnType<typeof summary>}[]=[];for(const lo of [0.8,0.9,1])for(const hi of [1,1.1,1.2,1.3,1.4,1.5,1.6,1.8]){if(hi<lo)continue;for(const ep of [0,0.25,0.5])for(const ms of [0.5,0.75,1]){const g={lo,hi,effPrior:ep,matchupStrength:ms};out.push({g,s:summary(train,g)})}}out.sort((a,b)=>(a.s.mae??999)-(b.s.mae??999));return out}
function bands(rows:R[]){const specs=[{name:"<0.90",a:-99,b:.9},{name:"0.90-1.10",a:.9,b:1.1},{name:"1.10-1.40",a:1.1,b:1.4},{name:"1.40-1.79",a:1.4,b:1.8},{name:"1.80",a:1.8,b:99}];return specs.map(x=>{const z=rows.filter(r=>r.role>=x.a&&r.role<x.b);const carryBias=z.filter(r=>r.actualCarries!=null).map(r=>(r.actualCarries as number)-r.carries);return{name:x.name,n:z.length,mae:round(mean(z.map(r=>Math.abs(r.actual-r.projection)))),carryMae:round(mean(z.filter(r=>r.actualCarries!=null).map(r=>Math.abs((r.actualCarries as number)-r.carries)))),carryBiasActualMinusProj:round(mean(carryBias)),market:market(z)}})}
export async function GET(){const[cal,proj]=await Promise.all([readSportWorksheet("NFL","prop_calibration") as Promise<Row[]>,readSportWorksheet("NFL","prop_projections") as Promise<Row[]>]);const exact=new Map<string,Row>(),fallback=new Map<string,Row>();for(const p of proj){if(text(p.Market)!=="Rushing Yards"||text(p.Position)!=="RB")continue;exact.set(key(p,true),p);fallback.set(key(p,false),p)}const rows:R[]=[];const seen=new Set<string>();for(const c of cal){if(text(c.Market)!=="Rushing Yards"||text(c.Position)!=="RB")continue;const projection=num(c.Projection),actual=num(c["Actual Result"]),carries=num(c["Projected Opportunity"]),eff=num(c["Projected Efficiency"]),line=num(c["Market Line"])??0;if(projection==null||actual==null||carries==null||eff==null||carries<=0||eff<=0)continue;const p=exact.get(key(c,true))||fallback.get(key(c,false))||{};const d=`${key(c,true)}|${projection}`;if(seen.has(d))continue;seen.add(d);rows.push({date:text(c.Date),player:text(c.Player),line,projection,actual,carries,actualCarries:num(c["Actual Opportunity"]),eff,actualEff:num(c["Actual Efficiency"]),role:role(p.Confluence),matchup:num(p["Matchup Index"])??1,slot:text(p.Slot)})}rows.sort((a,b)=>a.date.localeCompare(b.date)||a.player.localeCompare(b.player));const pre=rows.filter(r=>r.date<"2026-09-27"),hold=rows.filter(r=>r.date==="2026-09-27");const current:G={lo:0,hi:9,effPrior:0,matchupStrength:1};const ranked=grid(pre),best=ranked[0];const roleRank=ranked.filter(x=>x.g.effPrior===0&&x.g.matchupStrength===1).sort((a,b)=>(a.s.mae??999)-(b.s.mae??999));const pack=(g:G)=>({rule:g,pre:summary(pre,g),holdout:summary(hold,g),all:summary(rows,g)});return NextResponse.json({counts:{all:rows.length,pre:pre.length,holdout:hold.length,marketLined:rows.filter(r=>r.line>0).length},market:{pre:market(pre),holdout:market(hold),all:market(rows)},current:pack(current),best:pack(best.g),bestRoleOnly:pack(roleRank[0].g),topRole:roleRank.slice(0,10),topJoint:ranked.slice(0,10),roleBands:{pre:bands(pre),holdout:bands(hold),all:bands(rows)}});}
