import { NextResponse } from "next/server";
import { readSportWorksheet } from "../../../../lib/sportSheets";

export const dynamic = "force-dynamic";
export const revalidate = 0;

const T=v=>String(v??"").trim();
const N=v=>{const x=Number(T(v));return Number.isFinite(x)?x:null};
const K=s=>s.toUpperCase().replace(/[^A-Z0-9]/g,"");
const D=s=>T(s).slice(0,10);
const A=x=>x.length?x.reduce((a,b)=>a+b,0)/x.length:0;
const RD=(x,d=3)=>Number(x.toFixed(d));
const slateKey=r=>T(r["Game ID"])?`id:${T(r["Game ID"])}`:`${D(r.Date)}|${K(T(r["Away Team"]))}|${K(T(r["Home Team"]))}`;
const schedKeys=r=>{const z=[];if(T(r["Game ID"]))z.push(`id:${T(r["Game ID"])}`);z.push(`${D(r["Game Date"])}|${K(T(r["Away Team"]))}|${K(T(r["Home Team"]))}`);return z};
const ratingKey=(team,season,week)=>`${season}|${week}|${K(team)}`;

function solve(X,y,lam){const p=X[0]?.length??0;if(!p)return[];const M=Array.from({length:p},()=>Array(p).fill(0)),b=Array(p).fill(0);for(let i=0;i<X.length;i++)for(let j=0;j<p;j++){b[j]+=X[i][j]*y[i];for(let q=0;q<p;q++)M[j][q]+=X[i][j]*X[i][q]}for(let j=1;j<p;j++)M[j][j]+=lam;for(let i=0;i<p;i++){let z=i;for(let r=i+1;r<p;r++)if(Math.abs(M[r][i])>Math.abs(M[z][i]))z=r;[M[i],M[z]]=[M[z],M[i]];[b[i],b[z]]=[b[z],b[i]];const u=M[i][i];if(Math.abs(u)<1e-10)return[];for(let q=i;q<p;q++)M[i][q]/=u;b[i]/=u;for(let r=0;r<p;r++)if(r!==i){const f=M[r][i];for(let q=i;q<p;q++)M[r][q]-=f*M[i][q];b[r]-=f*b[i]}}return b}
function fit(rows,features,lambda,target){const good=rows.filter(g=>features.every(f=>Number.isFinite(g.f[f])));if(good.length<Math.max(25,features.length*5))return null;const mu=features.map(f=>A(good.map(g=>g.f[f]))),sd=features.map((f,j)=>Math.sqrt(A(good.map(g=>(g.f[f]-mu[j])**2)))||1);const X=good.map(g=>[1,...features.map((f,j)=>(g.f[f]-mu[j])/sd[j])]);const y=good.map(g=>target(g));const b=solve(X,y,lambda);return b.length?{b,mu,sd}:null}
function predict(g,features,m){return m.b[0]+features.reduce((z,f,j)=>z+m.b[j+1]*((g.f[f]-m.mu[j])/m.sd[j]),0)}
function evaluate(train,test,features,lambda,mode){const target=mode==="raw"?(g=>g.actualMargin):(g=>g.actualMargin-g.currentMargin);const m=fit(train,features,lambda,target);if(!m)return null;const valid=test.filter(g=>features.every(f=>Number.isFinite(g.f[f])));if(!valid.length)return null;let ae=0,cur=0,mkt=0,nm=0,w=0,l=0,p=0;for(const g of valid){const v=predict(g,features,m);const pm=mode==="raw"?v:g.currentMargin+v;ae+=Math.abs(pm-g.actualMargin);cur+=Math.abs(g.currentMargin-g.actualMargin);if(g.marketMargin!=null){mkt+=Math.abs(g.marketMargin-g.actualMargin);nm++}const edge=pm-(g.marketMargin??pm),actualEdge=g.actualMargin-(g.marketMargin??g.actualMargin),sg=edge>=0?actualEdge:-actualEdge;if(g.marketMargin!=null){if(Math.abs(sg)<1e-9)p++;else if(sg>0)w++;else l++}}
return{n:valid.length,mae:RD(ae/valid.length),currentMae:RD(cur/valid.length),marketMae:nm?RD(mkt/nm):null,vsCurrent:RD((cur-ae)/valid.length),record:{w,l,p,winRate:RD(w+l?w/(w+l):0)},coefficients:features.map((f,j)=>({feature:f,beta:RD(m.b[j+1]??0)}))}}
function cv(rows,features,lambda,mode){const dates=[...new Set(rows.map(g=>g.date))].sort();const folds=[];let n=0,ae=0,cur=0,mkt=0,nm=0;for(const d of dates){const tr=rows.filter(g=>g.date<d),te=rows.filter(g=>g.date===d);if(tr.length<25)continue;const e=evaluate(tr,te,features,lambda,mode);if(!e)continue;folds.push({date:d,n:e.n,mae:e.mae,currentMae:e.currentMae,marketMae:e.marketMae,vsCurrent:e.vsCurrent});n+=e.n;ae+=e.mae*e.n;cur+=e.currentMae*e.n;if(e.marketMae!=null){mkt+=e.marketMae*e.n;nm+=e.n}}return n?{n,mae:RD(ae/n),currentMae:RD(cur/n),marketMae:nm?RD(mkt/nm):null,vsCurrent:RD((cur-ae)/n),positiveFolds:folds.filter(x=>x.vsCurrent>0).length,folds}:null}

export async function GET(){
 const [sl,sc,rr]=await Promise.all([readSportWorksheet("NCAAF","daily_slate"),readSportWorksheet("NCAAF","schedule"),readSportWorksheet("NCAAF","team_ratings")]);
 const actual=new Map();for(const r of sc){const a=N(r["Away Score"]),h=N(r["Home Score"]);if(a==null||h==null||(a===0&&h===0))continue;for(const q of schedKeys(r))actual.set(q,{a,h})}
 const ratings=new Map();for(const r of rr){ratings.set(ratingKey(T(r.Team),N(r.Season)??2026,N(r["Projection Week"])??0),r)}
 const dedup=new Map();for(const r of sl)dedup.set(slateKey(r),r);
 const games=[];
 const diffCols=["Elo Rating","Preseason Rating","Power Rating","Offense Rating","Defense Rating","Special Teams Rating","Points Per Game","Points Allowed Per Game","Points Per Drive","Points Allowed Per Drive","EPA/PPA Offense","EPA/PPA Defense Edge","Pass EPA/PPA","Pass Defense Edge","Rush EPA/PPA","Rush Defense Edge","Success Rate Offense","Success Rate Defense Edge","Explosiveness Offense","Explosiveness Defense Edge","Havoc Allowed","Havoc Created","Line Yards Offense","Line Yards Defense Edge","Power Success","Stuff Rate Edge","Finishing Drives Offense","Finishing Drives Defense Edge","Field Position Offense","Field Position Defense Edge","Third Down Rate","Third Down Defense Edge","Red Zone TD Rate","Red Zone Defense Edge","Turnover Rate","Takeaway Rate","Sack Rate Allowed","Sack Rate Created","Standard Downs Offense","Standard Downs Defense Edge","Passing Downs Offense","Passing Downs Defense Edge","Plays Per Game","Possessions Per Game","Pace Seconds Per Play","Talent Rating","Recruiting Rating","Portal Rating","Returning Production","QB Continuity"];
 for(const s of dedup.values()){
  const ac=actual.get(slateKey(s))||actual.get(`${D(s.Date)}|${K(T(s["Away Team"]))}|${K(T(s["Home Team"]))}`);const season=N(s.Season)??2026,week=N(s.Week)??0,pm=N(s["Projected Margin"]);if(!ac||!week||pm==null)continue;
  const ar=ratings.get(ratingKey(T(s["Away Team"]),season,week)),hr=ratings.get(ratingKey(T(s["Home Team"]),season,week));if(!ar||!hr||T(ar.Classification).toLowerCase()!=="fbs"||T(hr.Classification).toLowerCase()!=="fbs")continue;
  const f={};for(const c of diffCols){const a=N(ar[c]),h=N(hr[c]);if(a!=null&&h!=null)f[c]=h-a}
  f["Home Field Advantage"]=N(s["Home Field Advantage"])??0;f["Venue HFA"]=N(s["Venue HFA"])??0;f["Rest Adjustment"]=N(s["Rest Adjustment"])??0;f["Travel Adjustment"]=N(s["Travel Adjustment"])??0;f["Altitude Adjustment"]=N(s["Altitude Adjustment"])??0;f["Injury Differential"]=(N(s["Home Injury Adjustment"])??0)-(N(s["Away Injury Adjustment"])??0);f["QB Differential"]=(N(s["Home QB Adjustment"])??0)-(N(s["Away QB Adjustment"])??0);
  games.push({date:D(s.Date),week,game:T(s.Game),actualMargin:ac.h-ac.a,currentMargin:pm,marketMargin:N(s["Market Home Spread"])==null?null:-N(s["Market Home Spread"]),f});
 }
 games.sort((a,b)=>a.date.localeCompare(b.date));const dates=[...new Set(games.map(g=>g.date))].sort(),holdDate=dates.at(-1),dev=games.filter(g=>g.date<holdDate),hold=games.filter(g=>g.date===holdDate);
 const candidates=["Elo Rating","Preseason Rating","Power Rating","Offense Rating","Defense Rating","Special Teams Rating","Points Per Game","Points Allowed Per Game","Points Per Drive","Points Allowed Per Drive","Pass EPA/PPA","Pass Defense Edge","Rush EPA/PPA","Rush Defense Edge","Success Rate Offense","Success Rate Defense Edge","Explosiveness Offense","Explosiveness Defense Edge","Havoc Allowed","Havoc Created","Line Yards Offense","Line Yards Defense Edge","Finishing Drives Offense","Finishing Drives Defense Edge","Field Position Offense","Field Position Defense Edge","Third Down Rate","Third Down Defense Edge","Red Zone TD Rate","Red Zone Defense Edge","Turnover Rate","Takeaway Rate","Sack Rate Allowed","Sack Rate Created","Standard Downs Offense","Standard Downs Defense Edge","Passing Downs Offense","Passing Downs Defense Edge","Plays Per Game","Possessions Per Game","Talent Rating","Recruiting Rating","Portal Rating","Returning Production","QB Continuity","Home Field Advantage","Venue HFA","Rest Adjustment","Injury Differential","QB Differential"];
 const lambdas=[.5,1,2,5,10,20];let bestLambda=2,b0=cv(dev,[],2,"correction");for(const l of lambdas){const z=cv(dev,[],l,"correction");if(z&&(!b0||z.mae<b0.mae)){b0=z;bestLambda=l}}
 const singles=candidates.map(f=>({feature:f,cv:cv(dev,[f],bestLambda,"correction"),holdout:evaluate(dev,hold,[f],bestLambda,"correction")})).filter(x=>x.cv).sort((a,b)=>a.cv.mae-b.cv.mae);
 const top=singles.slice(0,14).map(x=>x.feature);const pairs=[];for(let i=0;i<top.length;i++)for(let j=i+1;j<top.length;j++){const fs=[top[i],top[j]],z=cv(dev,fs,bestLambda,"correction");if(z)pairs.push({features:fs,cv:z,holdout:evaluate(dev,hold,fs,bestLambda,"correction")})}pairs.sort((a,b)=>a.cv.mae-b.cv.mae);
 let chosen=[],cur=b0,steps=[];for(let step=0;step<8;step++){let nx=null;for(const f of candidates.filter(x=>!chosen.includes(x))){const z=cv(dev,[...chosen,f],bestLambda,"correction");if(z&&(!nx||z.mae<nx.cv.mae))nx={f,cv:z}}if(!nx||nx.cv.mae>=cur.mae-0.12)break;chosen=[...chosen,nx.f];cur=nx.cv;steps.push({added:nx.f,cv:nx.cv,holdout:evaluate(dev,hold,chosen,bestLambda,"correction")})}
 const rawBest=[];for(const l of lambdas){const z=cv(dev,chosen,l,"raw");if(z)rawBest.push({lambda:l,cv:z,holdout:evaluate(dev,hold,chosen,l,"raw")})}rawBest.sort((a,b)=>a.cv.mae-b.cv.mae);
 return NextResponse.json({source:{games:games.length,development:dev.length,holdout:hold.length,holdoutDate},current:{development:cv(dev,[],bestLambda,"correction"),holdout:{n:hold.length,currentMae:RD(A(hold.map(g=>Math.abs(g.currentMargin-g.actualMargin)))),marketMae:RD(A(hold.filter(g=>g.marketMargin!=null).map(g=>Math.abs(g.marketMargin-g.actualMargin))))}},lambda:bestLambda,singles:singles.slice(0,20),pairs:pairs.slice(0,15),greedy:{selected:chosen,development:cur,steps,holdout:evaluate(dev,hold,chosen,bestLambda,"correction")},rawDifferential:rawBest.slice(0,3)});
}
