import { NextResponse } from "next/server";
import { readSportWorksheet } from "../../../../lib/sportSheets";

export const dynamic = "force-dynamic";
export const revalidate = 0;

type Row = Record<string,string>;
type G = {date:string; week:number; home:string; away:string; actualMargin:number; actualTotal:number; marketMargin:number; marketTotal:number; features:Record<string,number>};
const txt=(v:unknown)=>String(v??"").trim();
const num=(v:unknown):number|null=>{const n=Number(txt(v));return Number.isFinite(n)?n:null};
const key=(s:string)=>s.toUpperCase().replace(/[^A-Z0-9]/g,"");
const dk=(s:string)=>txt(s).slice(0,10);
const mean=(a:number[])=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0;
const mae=(a:number[])=>a.length?mean(a.map(Math.abs)):null;
const round=(x:number|null,d=4)=>x==null?null:Number(x.toFixed(d));
function slateKey(r:Row){const id=txt(r["Game ID"]);return id?`id:${id}`:`${dk(r.Date)}|${key(txt(r["Away Team"]))}|${key(txt(r["Home Team"]))}`}
function schedKeys(r:Row){const out:string[]=[];const id=txt(r["Game ID"]);if(id)out.push(`id:${id}`);out.push(`${dk(r["Game Date"])}|${key(txt(r["Away Team"]))}|${key(txt(r["Home Team"]))}`);return out}
function rkey(team:string,season:number,week:number){return `${season}|${week}|${key(team)}`}
function zstats(rows:G[], fs:string[]){const m:Record<string,number>={},s:Record<string,number>={};for(const f of fs){const v=rows.map(r=>r.features[f]).filter(Number.isFinite);m[f]=mean(v);const vv=mean(v.map(x=>(x-m[f])**2));s[f]=Math.sqrt(vv)||1;}return{m,s}}
function solveRidge(X:number[][],y:number[],lambda=1){const p=X[0]?.length??0;if(!p)return[];const A=Array.from({length:p},()=>Array(p).fill(0)),b=Array(p).fill(0);for(let i=0;i<X.length;i++){for(let j=0;j<p;j++){b[j]+=X[i][j]*y[i];for(let k=0;k<p;k++)A[j][k]+=X[i][j]*X[i][k];}}for(let j=0;j<p;j++)A[j][j]+=lambda;for(let i=0;i<p;i++){let pivot=i;for(let r=i+1;r<p;r++)if(Math.abs(A[r][i])>Math.abs(A[pivot][i]))pivot=r;[A[i],A[pivot]]=[A[pivot],A[i]];[b[i],b[pivot]]=[b[pivot],b[i]];const d=A[i][i]||1e-9;for(let c=i;c<p;c++)A[i][c]/=d;b[i]/=d;for(let r=0;r<p;r++){if(r===i)continue;const q=A[r][i];for(let c=i;c<p;c++)A[r][c]-=q*A[i][c];b[r]-=q*b[i];}}return b;}
function fitPredict(train:G[],test:G[],features:string[],kind:"spread"|"total",lambda=2){const {m,s}=zstats(train,features);const y=train.map(g=>kind==="spread"?g.actualMargin-g.marketMargin:g.actualTotal-g.marketTotal);const ym=mean(y);const X=train.map(g=>features.map(f=>(g.features[f]-m[f])/s[f]));const yc=y.map(v=>v-ym);const beta=solveRidge(X,yc,lambda);const preds=test.map(g=>ym+features.reduce((a,f,j)=>a+beta[j]*((g.features[f]-m[f])/s[f]),0));return{preds,beta,intercept:ym};}
function evalSet(games:G[],features:string[],kind:"spread"|"total"){
 const dates=[...new Set(games.map(g=>g.date))].sort();const folds:any[]=[];let allErr:number[]=[],baseErr:number[]=[],w=0,l=0,p=0,w1=0,l1=0,p1=0,w2=0,l2=0,p2=0;
 for(let di=2;di<dates.length;di++){const d=dates[di],train=games.filter(g=>g.date<d),test=games.filter(g=>g.date===d);if(train.length<35||test.length<3)continue;const {preds,beta}=fitPredict(train,test,features,kind);let fe:number[]=[],fb:number[]=[],fw=0,fl=0,fp=0;for(let i=0;i<test.length;i++){const g=test[i],base=kind==="spread"?g.marketMargin:g.marketTotal,actual=kind==="spread"?g.actualMargin:g.actualTotal,pred=base+preds[i];fe.push(Math.abs(pred-actual));fb.push(Math.abs(base-actual));const edge=pred-base,actualEdge=actual-base,signed=edge>=0?actualEdge:-actualEdge;if(Math.abs(signed)<1e-9){p++;fp++;}else if(signed>0){w++;fw++;}else{l++;fl++;}if(Math.abs(edge)>=1){if(Math.abs(signed)<1e-9)p1++;else if(signed>0)w1++;else l1++;}if(Math.abs(edge)>=2){if(Math.abs(signed)<1e-9)p2++;else if(signed>0)w2++;else l2++;}}
 allErr.push(...fe);baseErr.push(...fb);folds.push({date:d,n:test.length,mae:round(mae(fe)),marketMae:round(mae(fb)),improvement:round((mae(fb)??0)-(mae(fe)??0)),record:{w:fw,l:fl,p:fp},betas:features.map((f,j)=>({feature:f,beta:round(beta[j])}))}); }
 const improves=folds.filter(f=>(f.improvement??0)>0).length;const latest=folds.at(-1)??null;return{features,n:allErr.length,mae:round(mae(allErr)),marketMae:round(mae(baseErr)),improvement:round((mae(baseErr)??0)-(mae(allErr)??0)),folds:folds.length,improvingFolds:improves,improvingFoldRate:round(folds.length?improves/folds.length:0),latestFold:latest,recordAll:{w,l,p,winRate:round(w+l?w/(w+l):0)},record1Plus:{w:w1,l:l1,p:p1,winRate:round(w1+l1?w1/(w1+l1):0)},record2Plus:{w:w2,l:l2,p:p2,winRate:round(w2+l2?w2/(w2+l2):0)},foldDetails:folds};}
function forward(games:G[],candidates:string[],kind:"spread"|"total"){
 let selected:string[]=[];let current=evalSet(games,selected,kind);const steps:any[]=[];const remaining=[...candidates];for(let step=0;step<8&&remaining.length;step++){let best:any=null;for(const f of remaining){const r=evalSet(games,[...selected,f],kind);const gain=(current.mae??999)-(r.mae??999);const latestGain=(current.latestFold?.mae??999)-(r.latestFold?.mae??999);const score=gain + 0.20*(r.improvingFoldRate??0) + 0.05*Math.max(-1,Math.min(1,latestGain));if(!best||score>best.score)best={f,r,gain,latestGain,score};}if(!best)break;steps.push({candidate:best.f,incrementalMaeGain:round(best.gain),latestFoldGain:round(best.latestGain),result:best.r});if(best.gain<=0.03||best.r.improvingFoldRate<0.5||best.latestGain<-0.35)break;selected.push(best.f);remaining.splice(remaining.indexOf(best.f),1);current=best.r;}return{selected,final:current,steps};}
function uni(games:G[],cands:string[],kind:"spread"|"total"){return cands.map(f=>evalSet(games,[f],kind)).sort((a,b)=>(b.improvement??-999)-(a.improvement??-999));}

export async function GET(){
 const [slate,schedule,ratings]=await Promise.all([readSportWorksheet("NCAAF","daily_slate") as Promise<Row[]>,readSportWorksheet("NCAAF","schedule") as Promise<Row[]>,readSportWorksheet("NCAAF","team_ratings") as Promise<Row[]>]);
 const actual=new Map<string,{a:number;h:number}>();for(const r of schedule){const a=num(r["Away Score"]),h=num(r["Home Score"]);if(a==null||h==null||(a===0&&h===0))continue;for(const k of schedKeys(r))actual.set(k,{a,h});}
 const rm=new Map<string,Row>();for(const r of ratings){const season=num(r.Season)??2026,week=num(r["Projection Week"])??0;rm.set(rkey(txt(r.Team),season,week),r);}
 const dedup=new Map<string,Row>();for(const r of slate)dedup.set(slateKey(r),r);
 const spreadDiff=["Elo Rating","Power Rating","Preseason Rating","Offense Rating","Defense Rating","Special Teams Rating","Pass EPA/PPA","Rush EPA/PPA","Success Rate Offense","Explosiveness Offense","Havoc Allowed","Havoc Created","Finishing Drives Offense","Field Position Offense","Line Yards Offense","Line Yards Defense Edge","Passing Downs Offense","Third Down Rate","Red Zone TD Rate","Turnover Rate","Takeaway Rate","Sack Rate Allowed","Sack Rate Created","Points Per Drive","Points Allowed Per Drive","Points Per Game","Points Allowed Per Game","Plays Per Game","Possessions Per Game"];
 const totalAvg=["Pass EPA/PPA","Rush EPA/PPA","Success Rate Offense","Explosiveness Offense","Havoc Allowed","Havoc Created","Finishing Drives Offense","Field Position Offense","Line Yards Offense","Line Yards Defense Edge","Passing Downs Offense","Third Down Rate","Red Zone TD Rate","Turnover Rate","Takeaway Rate","Sack Rate Allowed","Sack Rate Created","Points Per Drive","Points Allowed Per Drive","Points Per Game","Points Allowed Per Game","Plays Per Game","Possessions Per Game","Talent Rating"];
 const games:G[]=[];let nonFbs=0,missing=0;
 for(const r of dedup.values()){const ac=actual.get(slateKey(r))||actual.get(`${dk(r.Date)}|${key(txt(r["Away Team"]))}|${key(txt(r["Home Team"]))}`);if(!ac)continue;const season=num(r.Season)??2026,week=num(r.Week)??0;const ar=rm.get(rkey(txt(r["Away Team"]),season,week)),hr=rm.get(rkey(txt(r["Home Team"]),season,week));if(!ar||!hr){missing++;continue;}if(txt(ar.Classification).toLowerCase()!=="fbs"||txt(hr.Classification).toLowerCase()!=="fbs"){nonFbs++;continue;}const hs=num(r["Market Home Spread"]),mt=num(r["Market Total"]);if(hs==null||mt==null)continue;const f:Record<string,number>={};for(const c of spreadDiff){const a=num(ar[c])??0,h=num(hr[c])??0;f[`${c} diff`]=h-a;}for(const c of totalAvg){const a=num(ar[c])??0,h=num(hr[c])??0;f[`${c} avg`]=(h+a)/2;}for(const c of ["Home Field Advantage","Venue HFA","Rest Adjustment","Weather Adjustment","Wind","Precipitation Probability","Expected Possessions","Away Injury Adjustment","Home Injury Adjustment","Data Confidence","Personnel Confidence","Reliability"]){f[c]=num(r[c])??0;}games.push({date:dk(r.Date),week,home:txt(r["Home Team"]),away:txt(r["Away Team"]),actualMargin:ac.h-ac.a,actualTotal:ac.h+ac.a,marketMargin:-hs,marketTotal:mt,features:f});}
 games.sort((a,b)=>a.date.localeCompare(b.date));
 const spreadCandidates=[...spreadDiff.map(c=>`${c} diff`),"Home Field Advantage","Venue HFA","Rest Adjustment","Away Injury Adjustment","Home Injury Adjustment"];
 const totalCandidates=[...totalAvg.map(c=>`${c} avg`),"Home Field Advantage","Venue HFA","Rest Adjustment","Weather Adjustment","Wind","Precipitation Probability","Expected Possessions"];
 const spreadUni=uni(games,spreadCandidates,"spread"),totalUni=uni(games,totalCandidates,"total");
 return NextResponse.json({source:{fbsGames:games.length,nonFbsExcluded:nonFbs,missingRatings:missing,dates:[...new Set(games.map(g=>g.date))]},spread:{baseline:evalSet(games,[],"spread"),univariate:spreadUni.slice(0,20),forward:forward(games,spreadCandidates,"spread")},total:{baseline:evalSet(games,[],"total"),univariate:totalUni.slice(0,20),forward:forward(games,totalCandidates,"total")}});
}
